// ── Lesson GQL-5: HTTPS, TLS & Certificates ──────────────────────────────────

import type { DemoActionContext } from '../../../types';
import { GQL } from '../../../../../shared/selectors';
import {
  GQL_HEALTH_QUERY,
  closeAuthPanelQuiet,
  configureDemoTabEndpointOverride,
  ensureHealthQuery,
  fillGqlEditor,
  getEndpointInput,
  resetGqlLessonSessionFlags,
  resetGqlLesson2SessionFlags,
  selectAuthInPanel,
} from './core';
import { resetLesson2VariablesHistoryFlags } from './lesson2-variables-history';
import { resetGqlLesson3SessionFlags } from './lesson3-mutations';
import { resetGqlLesson4SessionFlags } from './lesson4-schema-exploration';
import { resetGqlLesson5SessionFlags } from './lesson5-subscriptions';
import { resetGqlLesson6SessionFlags, LESSON6_AUTH_TOKEN_VALUE, upsertGqlDemoEnvVars } from './lesson6-auth-headers';
import { closeGqlDemoTabs, ensureGqlDemoTab, activateGqlDemoTabQuiet } from './gql-demo-tab';
import { patchDemoTabConnection, loadDemoSession } from '../../../../graphql/utils/gqlDemoWorkspace';
import { loadTabs } from '../../../../graphql/utils/tabPersistence';
import { setControlledCheckbox } from '../../setup-helpers';
import type { GqlTlsSettings } from '../../../../../shared/types/gqlTls';

// ── Endpoints & health probe ─────────────────────────────────────────────────

/** HTTPS endpoint for the Docker TLS proxy (Phase 1 — skip-cert). */
export const GQL_TLS_HTTPS_ENDPOINT = 'https://localhost:4443/graphql';
/** HTTPS/mTLS endpoint for the Docker mTLS proxy (Phase 3 — client cert). */
export const GQL_TLS_MTLS_ENDPOINT = 'https://localhost:4445/graphql';
/** HTTP health probe for PrerequisiteGate (Phase 1 TLS stack). */
export const GQL_TLS_HEALTH_PROBE = 'http://127.0.0.1:4444/health';
/** HTTP health probe for mTLS stack on port 4445 (Phase 3). */
export const GQL_TLS_MTLS_HEALTH_PROBE = 'http://127.0.0.1:4446/health';
/** Both Docker stacks required before GQL-5 can start (TLS proxy + mTLS proxy). */
export const GQL_TLS_DOCKER_HEALTH_PROBES = [
  GQL_TLS_HEALTH_PROBE,
  GQL_TLS_MTLS_HEALTH_PROBE,
] as const;
/** Plain HTTP restore endpoint after TLS steps. */
export const GQL_PLAIN_HTTP = 'http://localhost:4010/graphql';
/** Bearer token template for auth-over-TLS step. */
export const GQL_TLS_BEARER_TEMPLATE = '{{authToken}}';

// ── Embedded TLS certificates (generated by generate-cert.sh) ────────────────

/** GraphQL Dev Root CA — validates the TLS proxy server leaf cert. */
export const GQL_TLS_CA_CERT = `-----BEGIN CERTIFICATE-----
MIIDjzCCAnegAwIBAgIUUAZMhLebbWwzOyIJ/B/ShuUjm90wDQYJKoZIhvcNAQEL
BQAwVzEhMB8GA1UEAwwYUmVkZmlyZUZvcmdlIERldiBSb290IENBMRkwFwYDVQQK
DBBSZWRmaXJlRm9yZ2UgRGV2MRcwFQYDVQQLDA5HcmFwaFFMIFN0dWRpbzAeFw0y
NjA2MjAyMTM0MDFaFw0yODA5MjIyMTM0MDFaMFcxITAfBgNVBAMMGFJlZGZpcmVG
b3JnZSBEZXYgUm9vdCBDQTEZMBcGA1UECgwQUmVkZmlyZUZvcmdlIERldjEXMBUG
A1UECwwOR3JhcGhRTCBTdHVkaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQCkwyavpT5KZvH8V3pbyDjbxIWJaEc8Noa5LHVthm7RUpk4qei7F8XbbYMT
RI23kATUnMxTxLs2WI2XlCBJGPbP62cer3cpSfp+Pfevx+STX+/wWiMoeSqljZfB
gon5SG/rIGK/37/6K9f7qvlVaFmV3QzgVUN2/N+9IB7IFGHujh4pIuIHHagPOfSX
aRaNSti6Oju2KxgTCq6lCcF61rbEvv9yFEzD43lkRQu9pmggf0bvOoC6wv8ZxOsD
AKZzecKl7E1XS/V7u7NQzoRWfYMjyMnbUMVLg4vdTpJZsaZfDGmRUekLJJpjOQSb
B6KT2jkGJCPrSMdz+X8y+piccIEpAgMBAAGjUzBRMB0GA1UdDgQWBBTuZ/uOUreG
TMzPjJeCOWRSw5HjbjAfBgNVHSMEGDAWgBTuZ/uOUreGTMzPjJeCOWRSw5HjbjAP
BgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAKp0T+nO9NXGuzc5tW
M37FWivDQqbrf0Xkmq+Wt4QxV6CW/p1e1vM9kvpBiFw09LWUbYBTRTw5WfQepX4l
PkqygUn5IsOZf6/TMZnCQTEicf5lzPhCehBt16VeMmxL4LU21CppNDzEM6k+DLbj
J4DPPSDtYr2Pj3/BAfU3vkS0x+x6D5gQF8uqo4Xcknd7p2hvN9kvthqQ6rYhGWRR
6R9V38tWZG9WGrOynJmBV6AHncBVEFB2eYM+fD6nmTiH4/vLQl82VSev8AAkgPeR
jeGpY6Z45xe3v/G8SSIYPiGqVt+qA5aEDYAAYhssHrXgtfc4VoIoOIHTdTsT7jR+
rY0+
-----END CERTIFICATE-----`;

/** Client leaf cert signed by GraphQL Dev Root CA — for future mTLS Phase 3. */
export const GQL_TLS_CLIENT_CERT = `-----BEGIN CERTIFICATE-----
MIIDqzCCApOgAwIBAgIUMbGN2ntemao3bukDPtVTdhoG6TYwDQYJKoZIhvcNAQEL
BQAwVzEhMB8GA1UEAwwYUmVkZmlyZUZvcmdlIERldiBSb290IENBMRkwFwYDVQQK
DBBSZWRmaXJlRm9yZ2UgRGV2MRcwFQYDVQQLDA5HcmFwaFFMIFN0dWRpbzAeFw0y
NjA2MjAyMTM0MDFaFw0yODA5MjIyMTM0MDFaMFcxITAfBgNVBAMMGFJlZGZpcmVG
b3JnZSBUZXN0IENsaWVudDEZMBcGA1UECgwQUmVkZmlyZUZvcmdlIERldjEXMBUG
A1UECwwOR3JhcGhRTCBTdHVkaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDt2wCQczyiSIRzNtwL/TMrUgQN03XRrws+Tq3phx2YR3TNJ0lYJcTfuSzk
2AcRJTSP0EcNSqjKdajxWTuIRX05j3EBDV//rWDuABitKVAzrpBCaZ0Y9xpLoWbo
VDM+nBCiXRtLtexWCZzKlCSvZJd89vXHNF5iCK62ul1RJPenU2Q8cZ20h6o3wHl+
L/aki1tBJINDNGDIjr4wg19iPPcbAGgBWvb3D1ILdCHNT745lH/I9+CRapixIRdi
jwc83LgYdIaka1zwgZXEEmGFHwWNbSDCk2js/GOL4kSaZlNsbCMOOzate9LxRUog
sFvQ/cX4m5sq04O4CG9BA8dG0OL5AgMBAAGjbzBtMAkGA1UdEwQCMAAwCwYDVR0P
BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMCMB0GA1UdDgQWBBQlAjbPv1nlqxZ9
W0Qmxt6+XUvajTAfBgNVHSMEGDAWgBTuZ/uOUreGTMzPjJeCOWRSw5HjbjANBgkq
hkiG9w0BAQsFAAOCAQEAAtDBsFK7q5dn3lOs7vYV8s4RycTyd/o6ViffIjJSBm8U
chzYYUGR2mWVJl2IJsBZYE80aV9KGetzxv21kzYMmjsYrAJo09RI0OywMx2JeLVT
fj49c5BdI3ZSRUtTXRhSBs8qtGH+dBc4y4Mt0LzthlWVNguWRRaMbWWDTiMoGP0j
SiE8++OCq4JCE84EDNhfxpTyVyadfWjO8WwOO/7yvMyfM2Rr00nu4cZmqWdW/mv5
Z/THQzq0zdW27MSGcDTfpShTVrunJYmK4FWrWoMuLRjwnA/hgifcK+LFkiYwlEVp
8IG8wRabzvGea14uM8atsZeuZeCAQMZpr9fh/emjHg==
-----END CERTIFICATE-----`;

/** Client private key — paired with GQL_TLS_CLIENT_CERT for future mTLS. */
export const GQL_TLS_CLIENT_KEY = `-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDt2wCQczyiSIRz
NtwL/TMrUgQN03XRrws+Tq3phx2YR3TNJ0lYJcTfuSzk2AcRJTSP0EcNSqjKdajx
WTuIRX05j3EBDV//rWDuABitKVAzrpBCaZ0Y9xpLoWboVDM+nBCiXRtLtexWCZzK
lCSvZJd89vXHNF5iCK62ul1RJPenU2Q8cZ20h6o3wHl+L/aki1tBJINDNGDIjr4w
g19iPPcbAGgBWvb3D1ILdCHNT745lH/I9+CRapixIRdijwc83LgYdIaka1zwgZXE
EmGFHwWNbSDCk2js/GOL4kSaZlNsbCMOOzate9LxRUogsFvQ/cX4m5sq04O4CG9B
A8dG0OL5AgMBAAECggEANGlCiZHq9XN3RA/9kuK7KLuMyyMiXg7tMlCR/9hXDBwK
v739amAALrAWFWMIw51oJJxnW6Vs5hfhHzVjadauDkXuR6YT1jn1FtyMk3N8CbdY
cFnnVP32HF43V9Bd7ljjTXOotRkkN50soHLeVoua2d1tMPT4Ky/wl7EfKOc1bvgD
Xm1F5Cd92eTb25pToviQkRMF9cZUV0bSmGkte061W2r/zPJLjrQuJUbviK4c+hXb
9mtKyRG5Lu1WMbgXakS0LxGt/QxwuiBrIW440EV6RMlpiOlzPpeaFm+YQIsEDb5R
85UKYSpp30WOnV3uB15OJzxrNFZQSwgMrVXlUuLMFQKBgQD9332r7ZdRp9GbfSvi
Ad1o5Hbs0F1KqVdyNvLdGMmb8/1h33CiQg+bKVOe5yRg5f08DGwffF/NFxzHEk8P
KTPrxo9QFdPHpM5TAApnhEdVpRkw2cnPuVYE8ezQ9ZFjHx10A7aIXVmXxIPOxrt6
OasHXXN7I4ISTtPBZJYJwWt4HwKBgQDv2Sggw728AW2szXGmGbb6Zh3D9UpP1M/F
ht9zVY4TuhI66Fpk20tlGWGuJI7bNGBBhAJPkV9ZnwrMvY0mvxSN7H9i7uopM8iV
CnSa7Eqaipv5p1IhoV3seOu1DiCSDNghAvv8gSdD2VvjgCq/WrmyC6lrljDm+Oo6
yUpu/jSh5wKBgQCsLAuws/sxl5yh1OwT5Kvh3T+CL3V1kw8JGJbwt0TTjU9ENyLO
B/tJgWeClsOnK5LoTIxvdgwKrSgJIjOX1putxQWgjI0KEo0S4S4tMhqmzMceyDUD
uW/K/r9an5AwJwP0kCgUpyqBsParH0A6Di4dWpVc56HpBKi7uZm/l/tohQKBgC4D
jkRC6TqRV5YoT95a3pTJVHqMq3YHUNkHWAULa9dzAh5VB0qEG8HIjcnX76Q0Nyc6
iSr0q8NI1MyUrOi7DdlwfrvfNAM1kQyu1dIG9QUTBHtv0zzqdVdxl17D2BHM7wXe
SbOWn47Pu2Y453qQkEGNJTKjvLwDEwS2K1aB5F0PAoGABIC1wypyNjm77N0Kf/lz
surObiNUF5KRuFe/UZq/Ha7pIJZ6M57ryXCVelJh1/ak7OBH1+xz+eQmSP7bJw9T
PM2juvsbCzwhMpn1CKT0Qd70X0osdj0Fsek1iIgPRi7f2pSArt0tFTo9En96EOFV
sTloHM6sF25hgEFsV4J0XMc=
-----END PRIVATE KEY-----`;

// ── Session flags ─────────────────────────────────────────────────────────────

let _gqltEnvReady = false;
let _gqltEndpointSet = false;
let _gqltSkipCertEnabled = false;
let _gqltIntrospected = false;
let _gqltAuthConfigured = false;
let _gqltAuthExecuted = false;
let _gqltCaConfigured = false;
let _gqltCaIntrospected = false;
let _gqltMtlsConfigured = false;
let _gqltMtlsIntrospected = false;

export function resetGqlTlsSessionFlags(): void {
  _gqltEnvReady = false;
  _gqltEndpointSet = false;
  _gqltSkipCertEnabled = false;
  _gqltIntrospected = false;
  _gqltAuthConfigured = false;
  _gqltAuthExecuted = false;
  _gqltCaConfigured = false;
  _gqltCaIntrospected = false;
  _gqltMtlsConfigured = false;
  _gqltMtlsIntrospected = false;
}

// ── DOM helpers ───────────────────────────────────────────────────────────────

function endpointValue(): string {
  return (getEndpointInput()?.value ?? '').trim();
}

function endpointIsHttpsTls(): boolean {
  const v = endpointValue().toLowerCase();
  return v.startsWith('https://') && v.includes(':4443');
}

function endpointIsMtls(): boolean {
  return endpointValue().includes(':4445');
}

function isTlsToggleActive(): boolean {
  const btn = document.querySelector<HTMLButtonElement>(GQL.TLS_TOGGLE);
  return btn?.getAttribute('aria-pressed') === 'true';
}

function isSkipCertDisabledInDom(): boolean {
  if (isTlsToggleActive()) return false;
  const checkbox = document.querySelector<HTMLInputElement>(`${GQL.TLS_SKIP_CERT} input[type="checkbox"]`);
  if (checkbox?.checked) return false;
  return true;
}

function isTlsCaConfiguredInDom(): boolean {
  if (isTlsToggleActive()) return false;
  if (document.querySelector(GQL.TLS_INDICATOR_CA)) return true;
  const ca = document.querySelector<HTMLTextAreaElement>(GQL.TLS_CA_CERT);
  return !!(ca?.value?.includes('BEGIN CERTIFICATE') && isSkipCertDisabledInDom());
}

function isMtlsConfiguredInDom(): boolean {
  if (!isSkipCertDisabledInDom()) return false;
  if (document.querySelector(GQL.TLS_INDICATOR_MTLS)) return true;
  const cert = document.querySelector<HTMLTextAreaElement>(GQL.TLS_CLIENT_CERT);
  const key = document.querySelector<HTMLTextAreaElement>(GQL.TLS_CLIENT_KEY);
  return !!(cert?.value?.includes('BEGIN CERTIFICATE') && key?.value?.includes('BEGIN'));
}

function applyGqlTlsViaDemoBridge(patch: Partial<GqlTlsSettings>): boolean {
  const bridge = (window as unknown as Record<string, unknown>).__demoApplyGqlTlsSettings as
    | ((p: Partial<GqlTlsSettings>) => void)
    | undefined;
  if (!bridge) return false;
  bridge(patch);
  return true;
}

async function ensureGqlTlsPanelOpen(ctx: DemoActionContext): Promise<void> {
  if (!document.querySelector(GQL.TLS_CONFIGURE)) {
    // Never revert an mTLS endpoint (4445) back to the TLS-only port (4443).
    if (endpointIsMtls()) {
      await ctx.waitFor(GQL.TLS_CONFIGURE, 5000);
    } else {
      await ensureTlsEndpoint(ctx);
    }
  }
  await ctx.waitFor(GQL.TLS_CONFIGURE, 5000);
  if (!document.querySelector(GQL.TLS_BODY)) {
    await ctx.click(GQL.TLS_CONFIGURE);
    await ctx.waitFor(GQL.TLS_BODY, 5000);
    await ctx.delay(600);
  }
}

async function setGqlSkipCertInModal(ctx: DemoActionContext, checked: boolean, pauseMs = 400): Promise<void> {
  await ctx.waitFor(`${GQL.TLS_SKIP_CERT} input[type="checkbox"]`, 3000);
  const checkbox = document.querySelector<HTMLInputElement>(`${GQL.TLS_SKIP_CERT} input[type="checkbox"]`);
  if (checkbox && checkbox.checked !== checked) {
    setControlledCheckbox(checkbox, checked);
    await ctx.delay(pauseMs);
  }
}

async function closeGqlTlsModal(ctx: DemoActionContext, opts: { visible?: boolean } = {}): Promise<void> {
  const visible = opts.visible !== false;
  if (!document.querySelector(GQL.TLS_BODY)) return;
  const closeSel = document.querySelector(GQL.TLS_CLOSE) ? GQL.TLS_CLOSE : GQL.TLS_SAVE;
  if (visible) {
    await ctx.click(closeSel);
    await ctx.delay(700);
  } else {
    const closeBtn = document.querySelector<HTMLButtonElement>(GQL.TLS_CLOSE);
    if (closeBtn) {
      closeBtn.click();
    } else {
      await ctx.click(GQL.TLS_SAVE);
    }
    for (let i = 0; i < 20 && document.querySelector(GQL.TLS_BODY); i++) {
      await ctx.delay(50);
    }
    await ctx.delay(100);
  }
}

/** Human-paced Phase 2 demo — open TLS modal, disable skip-cert, paste CA, close (~8–10s at 1×). */
async function runTlsCaCertDemoAction(ctx: DemoActionContext): Promise<void> {
  await ctx.waitFor(GQL.TLS_CONFIGURE, 5000);
  if (!document.querySelector(GQL.TLS_BODY)) {
    await ctx.click(GQL.TLS_CONFIGURE);
    await ctx.waitFor(GQL.TLS_BODY, 5000);
    await ctx.delay(800);
  }

  if (isTlsToggleActive()) {
    await ctx.click(GQL.TLS_TOGGLE);
    await ctx.delay(800);
  }

  await setGqlSkipCertInModal(ctx, false, 500);
  await ctx.delay(600);

  await ctx.fill(GQL.TLS_CLIENT_CERT, '');
  await ctx.delay(300);
  await ctx.fill(GQL.TLS_CLIENT_KEY, '');
  await ctx.delay(300);
  const caField = document.querySelector(GQL.TLS_CA_CERT);
  caField?.scrollIntoView?.({ block: 'center' });
  await ctx.delay(400);

  if (applyGqlTlsViaDemoBridge({
    skipTlsVerify: false,
    caCert: GQL_TLS_CA_CERT,
    clientCert: undefined,
    clientKey: undefined,
  })) {
    await ctx.waitFor(GQL.TLS_INDICATOR_CA, 5000);
  } else {
    await ctx.fill(GQL.TLS_CA_CERT, GQL_TLS_CA_CERT);
  }
  await ctx.delay(2000);

  await closeGqlTlsModal(ctx, { visible: true });
  _gqltSkipCertEnabled = false;
  _gqltCaConfigured = true;
}

/** Human-paced Phase 3 demo — open TLS modal, confirm CA, paste client cert + key (~12–15s at 1×). */
async function runMtlsCredsDemoAction(ctx: DemoActionContext): Promise<void> {
  await ctx.waitFor(GQL.TLS_CONFIGURE, 5000);
  if (!document.querySelector(GQL.TLS_BODY)) {
    await ctx.click(GQL.TLS_CONFIGURE);
    await ctx.waitFor(GQL.TLS_BODY, 5000);
    await ctx.delay(600);
  }

  if (isTlsToggleActive()) {
    await ctx.click(GQL.TLS_TOGGLE);
    await ctx.delay(800);
  }

  await setGqlSkipCertInModal(ctx, false, 500);
  await ctx.delay(600);

  document.querySelector(GQL.TLS_CA_CERT)?.scrollIntoView?.({ block: 'center' });
  await ctx.delay(600);
  const caField = document.querySelector<HTMLTextAreaElement>(GQL.TLS_CA_CERT);
  if (!caField?.value?.trim()) {
    await ctx.fill(GQL.TLS_CA_CERT, GQL_TLS_CA_CERT);
    await ctx.delay(1500);
  } else {
    await ctx.delay(800);
  }

  document.querySelector(GQL.TLS_CLIENT_CERT)?.scrollIntoView?.({ block: 'center' });
  await ctx.delay(600);

  // Re-animate: clear then re-fill so viewers see each paste moment (never use demo bridge here).
  await ctx.fill(GQL.TLS_CLIENT_CERT, '');
  await ctx.delay(400);
  await ctx.fill(GQL.TLS_CLIENT_CERT, GQL_TLS_CLIENT_CERT);
  await ctx.delay(1500);

  document.querySelector(GQL.TLS_CLIENT_KEY)?.scrollIntoView?.({ block: 'center' });
  await ctx.delay(400);
  await ctx.fill(GQL.TLS_CLIENT_KEY, '');
  await ctx.delay(400);
  await ctx.fill(GQL.TLS_CLIENT_KEY, GQL_TLS_CLIENT_KEY);
  await ctx.delay(1500);

  await ctx.waitFor(GQL.TLS_INDICATOR_MTLS, 5000);
  await ctx.delay(700);

  await closeGqlTlsModal(ctx, { visible: true });
  _gqltMtlsConfigured = true;
}

/** Turn off skip-cert in both the connection-bar SSL toggle and the TLS modal. */
async function ensureSkipCertDisabled(ctx: DemoActionContext): Promise<void> {
  applyGqlTlsViaDemoBridge({ skipTlsVerify: false });

  if (isTlsToggleActive()) {
    await ctx.click(GQL.TLS_TOGGLE);
    await ctx.delay(500);
  }

  await ensureGqlTlsPanelOpen(ctx);
  await setGqlSkipCertInModal(ctx, false);
  await ctx.delay(500);

  if (isTlsToggleActive()) {
    applyGqlTlsViaDemoBridge({ skipTlsVerify: false });
    await ctx.click(GQL.TLS_TOGGLE);
    await ctx.delay(500);
  }

  _gqltSkipCertEnabled = false;
}

async function clearGqlTlsCertFields(ctx: DemoActionContext): Promise<void> {
  await ctx.fill(GQL.TLS_CA_CERT, '');
  await ctx.fill(GQL.TLS_CLIENT_CERT, '');
  await ctx.fill(GQL.TLS_CLIENT_KEY, '');
  await ctx.delay(150);
}

async function saveGqlTlsModal(ctx: DemoActionContext): Promise<void> {
  await closeGqlTlsModal(ctx, { visible: false });
}

/** Phase 2 prerequisites — HTTPS endpoint + prior auth step (sidebar jump recovery). */
export async function ensureTlsPhase2Ready(ctx: DemoActionContext): Promise<void> {
  await ensureTlsAuthExecuted(ctx);
  await ensureTlsEndpoint(ctx);
}

/** Disable skip-cert and paste the dev CA certificate (Phase 2). */
export async function ensureTlsCaConfigured(
  ctx: DemoActionContext,
  opts: { visible?: boolean } = {},
): Promise<void> {
  const visible = opts.visible !== false;
  await ensureTlsPhase2Ready(ctx);
  if (_gqltCaConfigured && isTlsCaConfiguredInDom()) return;
  _gqltCaConfigured = false;

  if (!visible && applyGqlTlsViaDemoBridge({
    skipTlsVerify: false,
    caCert: GQL_TLS_CA_CERT,
    clientCert: undefined,
    clientKey: undefined,
  })) {
    await ctx.waitFor(GQL.TLS_INDICATOR_CA, 5000);
    _gqltSkipCertEnabled = false;
    _gqltCaConfigured = true;
    return;
  }

  if (visible) {
    await runTlsCaCertDemoAction(ctx);
    return;
  }

  await ensureSkipCertDisabled(ctx);
  await clearGqlTlsCertFields(ctx);
  await ctx.fill(GQL.TLS_CA_CERT, GQL_TLS_CA_CERT);
  await saveGqlTlsModal(ctx);
  _gqltSkipCertEnabled = false;
  _gqltCaConfigured = true;
}

/** Introspect with CA validation on port 4443 (Phase 2). */
export async function ensureTlsCaIntrospected(ctx: DemoActionContext): Promise<void> {
  // Port 4445 requires client credentials — introspect belongs to Phase 3 helpers.
  if (endpointIsMtls()) return;
  await ensureTlsCaConfigured(ctx, { visible: false });
  if (_gqltCaIntrospected && document.querySelector(GQL.SCHEMA_BADGE_OK)) return;
  const schemaTab = document.querySelector<HTMLElement>(GQL.RIGHT_TAB_SCHEMA);
  if (schemaTab?.getAttribute('aria-selected') === 'true') {
    await ctx.click(GQL.RIGHT_TAB_RESPONSE);
    await ctx.delay(400);
  }
  await ctx.click(GQL.INTROSPECT_BTN);
  await ctx.waitFor(GQL.SCHEMA_BADGE_OK, 25000);
  await ctx.delay(800);
  _gqltCaIntrospected = true;
}

/** Human-paced Phase 2 introspect — Custom CA badge → schema tab → Introspect → badge (~6–8s at 1×). */
export async function runTlsCaIntrospectDemoAction(ctx: DemoActionContext): Promise<void> {
  await ctx.waitFor(GQL.TLS_INDICATOR_CA, 5000);
  await ctx.delay(1000);

  const schemaTab = document.querySelector<HTMLElement>(GQL.RIGHT_TAB_SCHEMA);
  if (schemaTab && schemaTab.getAttribute('aria-selected') !== 'true') {
    await ctx.click(GQL.RIGHT_TAB_SCHEMA);
    await ctx.delay(800);
  } else {
    await ctx.delay(600);
  }

  await ctx.delay(800);
  await ctx.click(GQL.INTROSPECT_BTN);
  await ctx.waitFor(GQL.SCHEMA_BADGE_OK, 25000);
  await ctx.delay(2400);
  _gqltCaIntrospected = true;
}

/** Switch to the mTLS endpoint on port 4445. */
export async function ensureMtlsEndpoint(ctx: DemoActionContext): Promise<void> {
  if (endpointIsMtls()) return;
  await ensureTlsCaIntrospected(ctx);
  await configureDemoTabEndpointOverride(ctx, GQL_TLS_MTLS_ENDPOINT);
  await ctx.waitFor(GQL.TLS_CONFIGURE, 5000);
  await ctx.delay(800);
}

/** Configure CA + client cert + key for mTLS (Phase 3). */
export async function ensureMtlsConfigured(
  ctx: DemoActionContext,
  opts: { visible?: boolean } = {},
): Promise<void> {
  const visible = opts.visible !== false;
  await ensureMtlsEndpoint(ctx);
  if (_gqltMtlsConfigured && isMtlsConfiguredInDom()) return;
  _gqltMtlsConfigured = false;

  if (!visible && applyGqlTlsViaDemoBridge({
    skipTlsVerify: false,
    caCert: GQL_TLS_CA_CERT,
    clientCert: GQL_TLS_CLIENT_CERT,
    clientKey: GQL_TLS_CLIENT_KEY,
  })) {
    await ctx.waitFor(GQL.TLS_INDICATOR_MTLS, 5000);
    _gqltMtlsConfigured = true;
    return;
  }

  if (visible) {
    await runMtlsCredsDemoAction(ctx);
    return;
  }

  await ensureSkipCertDisabled(ctx);
  await ctx.fill(GQL.TLS_CA_CERT, GQL_TLS_CA_CERT);
  await ctx.delay(400);
  await ctx.fill(GQL.TLS_CLIENT_CERT, GQL_TLS_CLIENT_CERT);
  await ctx.delay(400);
  document.querySelector(GQL.TLS_CLIENT_KEY)?.scrollIntoView?.({ block: 'center' });
  await ctx.fill(GQL.TLS_CLIENT_KEY, GQL_TLS_CLIENT_KEY);
  await ctx.delay(200);
  await saveGqlTlsModal(ctx);
  _gqltMtlsConfigured = true;
}

/** Introspect over mTLS on port 4445 (Phase 3). */
export async function ensureMtlsIntrospected(ctx: DemoActionContext): Promise<void> {
  await ensureMtlsConfigured(ctx, { visible: false });
  if (_gqltMtlsIntrospected && document.querySelector(GQL.SCHEMA_BADGE_OK)) return;
  await ctx.click(GQL.INTROSPECT_BTN);
  await ctx.waitFor(GQL.SCHEMA_BADGE_OK, 25000);
  await ctx.delay(800);
  _gqltMtlsIntrospected = true;
}

/** Reset demo tab to plain HTTP before the HTTPS endpoint switch (step 2). */
export async function ensurePlainHttpEndpoint(ctx: DemoActionContext): Promise<void> {
  const v = endpointValue().toLowerCase();
  const isPlainHttpDom =
    v.startsWith('http://') && !v.includes(':4443') && !v.includes(':4445');
  const session = await loadDemoSession();
  let storagePlain = false;
  if (session?.demoTabId) {
    const tab = (await loadTabs()).find((t) => t.id === session.demoTabId);
    storagePlain = tab?.endpoint === GQL_PLAIN_HTTP;
  }
  if (isPlainHttpDom && storagePlain && !document.querySelector(GQL.TLS_TOGGLE)) return;

  await patchDemoTabConnection({
    endpoint: GQL_PLAIN_HTTP,
    skipTlsVerify: undefined,
    tlsCaCert: undefined,
    tlsClientCert: undefined,
    tlsClientKey: undefined,
  });
  await activateGqlDemoTabQuiet(ctx);
  await ctx.delay(500);

  const after = endpointValue().toLowerCase();
  const stillHttps =
    after.startsWith('https://') || after.includes(':4443') || after.includes(':4445');
  if (stillHttps || document.querySelector(GQL.TLS_TOGGLE)) {
    await configureDemoTabEndpointOverride(ctx, GQL_PLAIN_HTTP);
  }
  await ctx.delay(200);
  _gqltEndpointSet = false;
  _gqltSkipCertEnabled = false;
}

/** Fill the HTTPS TLS endpoint if not already set. */
export async function ensureTlsEndpoint(ctx: DemoActionContext): Promise<void> {
  // Re-apply when session flags say "done" but the tab reverted to plain HTTP
  // (e.g. {{graphqlUrl}} inherit) — TLS controls are hidden without https://.
  // Also recover from a stale mTLS port (4445) left on the tab from a prior run.
  const onTlsOnlyPort = endpointIsHttpsTls() && !endpointIsMtls();
  if (_gqltEndpointSet && onTlsOnlyPort) return;
  await configureDemoTabEndpointOverride(ctx, GQL_TLS_HTTPS_ENDPOINT);
  await ctx.waitFor(GQL.TLS_TOGGLE, 5000);
  await ctx.delay(200);
  _gqltEndpointSet = true;
}

/** Enable skip-cert toggle if not already enabled. */
export async function ensureSkipCertEnabled(ctx: DemoActionContext): Promise<void> {
  await ensureTlsEndpoint(ctx);
  if (_gqltSkipCertEnabled && isTlsToggleActive()) return;
  if (!document.querySelector(GQL.TLS_TOGGLE)) {
    _gqltSkipCertEnabled = false;
  }
  const btn = document.querySelector<HTMLButtonElement>(GQL.TLS_TOGGLE);
  if (btn && btn.getAttribute('aria-pressed') !== 'true') {
    btn.click();
    await ctx.delay(400);
  }
  _gqltSkipCertEnabled = true;
}

/** Introspect the TLS endpoint with skip-cert enabled. */
export async function ensureTlsIntrospected(ctx: DemoActionContext): Promise<void> {
  await ensureTlsSkipIntrospectOutcome(ctx);
}

/** Click Introspect only — outcome verified in the following observe step. */
export async function runTlsIntrospectClickOnly(ctx: DemoActionContext): Promise<void> {
  await ctx.click(GQL.INTROSPECT_BTN);
  await ctx.delay(400);
}

/** Ensure Phase 1 skip-cert introspect reached green schema badge. */
export async function ensureTlsSkipIntrospectOutcome(ctx: DemoActionContext): Promise<void> {
  await ensureSkipCertEnabled(ctx);
  if (_gqltIntrospected && document.querySelector(GQL.SCHEMA_BADGE_OK)) return;
  if (!document.querySelector(GQL.SCHEMA_BADGE_OK)) {
    await ctx.click(GQL.INTROSPECT_BTN);
    await ctx.waitFor(GQL.SCHEMA_BADGE_OK, 25000);
    await ctx.delay(800);
  }
  _gqltIntrospected = true;
}

export async function prepareGqltSkipIntrospectReading(ctx: DemoActionContext): Promise<void> {
  await ensureSkipCertEnabled(ctx);
}

/** Ensure Phase 2 CA-validated introspect outcome. */
export async function ensureTlsCaIntrospectOutcome(ctx: DemoActionContext): Promise<void> {
  if (endpointIsMtls()) return;
  await ensureTlsCaConfigured(ctx, { visible: false });
  if (_gqltCaIntrospected && document.querySelector(GQL.SCHEMA_BADGE_OK)) return;
  if (!document.querySelector(GQL.SCHEMA_BADGE_OK)) {
    const schemaTab = document.querySelector<HTMLElement>(GQL.RIGHT_TAB_SCHEMA);
    if (schemaTab?.getAttribute('aria-selected') === 'true') {
      await ctx.click(GQL.RIGHT_TAB_RESPONSE);
      await ctx.delay(400);
    }
    await ctx.click(GQL.INTROSPECT_BTN);
    await ctx.waitFor(GQL.SCHEMA_BADGE_OK, 25000);
    await ctx.delay(800);
  }
  _gqltCaIntrospected = true;
}

export async function prepareGqltCaIntrospectReading(ctx: DemoActionContext): Promise<void> {
  await ensureTlsCaConfigured(ctx, { visible: false });
}

/** Ensure Phase 3 mTLS introspect outcome. */
export async function ensureMtlsIntrospectOutcome(ctx: DemoActionContext): Promise<void> {
  await ensureMtlsConfigured(ctx, { visible: false });
  if (_gqltMtlsIntrospected && document.querySelector(GQL.SCHEMA_BADGE_OK)) return;
  if (!document.querySelector(GQL.SCHEMA_BADGE_OK)) {
    await ctx.click(GQL.INTROSPECT_BTN);
    await ctx.waitFor(GQL.SCHEMA_BADGE_OK, 25000);
    await ctx.delay(800);
  }
  _gqltMtlsIntrospected = true;
}

export async function prepareGqltMtlsIntrospectReading(ctx: DemoActionContext): Promise<void> {
  await ensureMtlsConfigured(ctx, { visible: false });
}

/** Ensure plain HTTP restore + introspect outcome. */
export async function ensurePlainRestoreIntrospectOutcome(ctx: DemoActionContext): Promise<void> {
  await ensureMtlsIntrospected(ctx);
  const v = endpointValue().toLowerCase();
  if (!v.startsWith('http://') || v.includes(':4443') || v.includes(':4445')) {
    await configureDemoTabEndpointOverride(ctx, GQL_PLAIN_HTTP);
    await ctx.delay(500);
  }
  if (!document.querySelector(GQL.SCHEMA_BADGE_OK)) {
    await ctx.click(GQL.INTROSPECT_BTN);
    await ctx.waitFor(GQL.SCHEMA_BADGE_OK, 25000);
    await ctx.delay(600);
  }
}

export async function prepareGqltRestoreReading(ctx: DemoActionContext): Promise<void> {
  await ensureMtlsIntrospected(ctx);
}

/** Seed Demo env with authToken so {{authToken}} resolves during auth-over-TLS. */
export async function ensureTlsEnvReady(ctx: DemoActionContext): Promise<void> {
  if (_gqltEnvReady) return;
  await upsertGqlDemoEnvVars(ctx, [{ key: 'authToken', value: LESSON6_AUTH_TOKEN_VALUE }]);
  _gqltEnvReady = true;
}

/** Configure Bearer auth for the auth-over-TLS step. */
export async function ensureTlsAuthConfigured(ctx: DemoActionContext): Promise<void> {
  await ensureTlsIntrospected(ctx);
  if (_gqltAuthConfigured) return;
  await ensureTlsEnvReady(ctx);
  await selectAuthInPanel(ctx, 'bearer');
  await ctx.fill(GQL.AUTH_BEARER_INPUT, GQL_TLS_BEARER_TEMPLATE);
  await ctx.delay(500);
  await closeAuthPanelQuiet(ctx);
  _gqltAuthConfigured = true;
}

/** Execute with TLS auth and confirm the header appears in Metadata. */
export async function ensureTlsAuthExecuted(ctx: DemoActionContext): Promise<void> {
  await ensureTlsAuthConfigured(ctx);
  if (_gqltAuthExecuted) return;
  await ensureHealthQuery(ctx);
  await ctx.click(GQL.EXECUTE_BTN);
  await ctx.waitFor(GQL.RESPONSE_VIEWER, 15000);
  await ctx.delay(500);
  await ctx.click(GQL.RV_TAB_METADATA);
  await ctx.waitFor(GQL.RV_REQUEST_HEADERS, 5000);
  await ctx.delay(600);
  _gqltAuthExecuted = true;
}

/** Ensure mTLS endpoint is set (quiet preAction — modal opens during action). */
export async function ensureMtlsPanelReady(ctx: DemoActionContext): Promise<void> {
  await ensureMtlsEndpoint(ctx);
}

/** Setup for Lesson GQL-5 — demo tab, health query, modals closed. */
export async function gqlTlsLessonSetup(ctx: DemoActionContext): Promise<void> {
  resetGqlLessonSessionFlags();
  resetGqlLesson2SessionFlags();
  resetLesson2VariablesHistoryFlags();
  resetGqlLesson3SessionFlags();
  resetGqlLesson4SessionFlags();
  resetGqlLesson5SessionFlags();
  resetGqlLesson6SessionFlags();
  resetGqlTlsSessionFlags();

  // Close any open auth panel
  await closeAuthPanelQuiet(ctx);

  const editorBtn = document.querySelector<HTMLElement>(GQL.MODE_EDITOR);
  if (editorBtn && !editorBtn.classList.contains('gql-mode-btn--active')) {
    editorBtn.click();
  }
  const responseTab = document.querySelector<HTMLElement>(GQL.RIGHT_TAB_RESPONSE);
  if (responseTab && responseTab.getAttribute('aria-selected') !== 'true') {
    responseTab.click();
  }
  await ctx.delay(200);
  const historyBtn = document.querySelector<HTMLElement>(GQL.ACTIVITY_HISTORY);
  if (historyBtn?.classList.contains('gql-activity-tab--active')) {
    historyBtn.click();
    await ctx.delay(200);
  }

  await ensureGqlDemoTab(ctx, 'gql-https-tls', 'HTTPS, TLS & Certificates');
  await ensurePlainHttpEndpoint(ctx);
  await fillGqlEditor(ctx, GQL_HEALTH_QUERY, { focus: false });
}

/** Cleanup for Lesson GQL-5 — close demo tab (HTTPS/skip-cert stay on demo tab only). */
export async function gqlTlsLessonCleanup(ctx: DemoActionContext): Promise<void> {
  resetGqlTlsSessionFlags();
  await closeGqlDemoTabs(ctx, 'gql-https-tls');
}
