// ── Lesson GQL-5: HTTPS, TLS & Certificates ──────────────────────────────────

import type { DemoActionContext } from '../../../types';
import { GQL } from '../../../../../shared/selectors';
import {
  GQL_HEALTH_QUERY,
  closeAuthPanelQuiet,
  configureDemoTabEndpointOverride,
  ensureHealthQuery,
  fillGqlEditor,
  resetGqlLessonSessionFlags,
  resetGqlLesson2SessionFlags,
  selectAuthInPanel,
} from './core';
import { resetLesson2VariablesHistoryFlags } from './lesson2-variables-history';
import { resetGqlLesson3SessionFlags } from './lesson3-mutations';
import { resetGqlLesson4SessionFlags } from './lesson4-schema-exploration';
import { resetGqlLesson5SessionFlags } from './lesson5-subscriptions';
import { resetGqlLesson6SessionFlags } from './lesson6-auth-headers';
import { closeGqlDemoTabs, ensureGqlDemoTab } from './gql-demo-tab';

// ── Endpoints & health probe ─────────────────────────────────────────────────

/** HTTPS endpoint for the Docker TLS proxy (Phase 1 — skip-cert). */
export const GQL_TLS_HTTPS_ENDPOINT = 'https://localhost:4443/graphql';
/** HTTPS/mTLS endpoint for the Docker mTLS proxy (Phase 3 — client cert). */
export const GQL_TLS_MTLS_ENDPOINT = 'https://localhost:4445/graphql';
/** HTTP health probe for PrerequisiteGate (Phase 1 TLS stack). */
export const GQL_TLS_HEALTH_PROBE = 'http://127.0.0.1:4444/health';
/** HTTP health probe for mTLS stack on port 4445 (Phase 3). */
export const GQL_TLS_MTLS_HEALTH_PROBE = 'http://127.0.0.1:4446/health';
/** Both Docker stacks required before GQL-5 can start (TLS proxy + mTLS proxy). */
export const GQL_TLS_DOCKER_HEALTH_PROBES = [
  GQL_TLS_HEALTH_PROBE,
  GQL_TLS_MTLS_HEALTH_PROBE,
] as const;
/** Plain HTTP restore endpoint after TLS steps. */
export const GQL_PLAIN_HTTP = 'http://localhost:4010/graphql';
/** Bearer token template for auth-over-TLS step. */
export const GQL_TLS_BEARER_TEMPLATE = '{{authToken}}';

// ── Embedded TLS certificates (generated by generate-cert.sh) ────────────────

/** GraphQL Dev Root CA — validates the TLS proxy server leaf cert. */
export const GQL_TLS_CA_CERT = `-----BEGIN CERTIFICATE-----
MIIDjzCCAnegAwIBAgIUUAZMhLebbWwzOyIJ/B/ShuUjm90wDQYJKoZIhvcNAQEL
BQAwVzEhMB8GA1UEAwwYUmVkZmlyZUZvcmdlIERldiBSb290IENBMRkwFwYDVQQK
DBBSZWRmaXJlRm9yZ2UgRGV2MRcwFQYDVQQLDA5HcmFwaFFMIFN0dWRpbzAeFw0y
NjA2MjAyMTM0MDFaFw0yODA5MjIyMTM0MDFaMFcxITAfBgNVBAMMGFJlZGZpcmVG
b3JnZSBEZXYgUm9vdCBDQTEZMBcGA1UECgwQUmVkZmlyZUZvcmdlIERldjEXMBUG
A1UECwwOR3JhcGhRTCBTdHVkaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQCkwyavpT5KZvH8V3pbyDjbxIWJaEc8Noa5LHVthm7RUpk4qei7F8XbbYMT
RI23kATUnMxTxLs2WI2XlCBJGPbP62cer3cpSfp+Pfevx+STX+/wWiMoeSqljZfB
gon5SG/rIGK/37/6K9f7qvlVaFmV3QzgVUN2/N+9IB7IFGHujh4pIuIHHagPOfSX
aRaNSti6Oju2KxgTCq6lCcF61rbEvv9yFEzD43lkRQu9pmggf0bvOoC6wv8ZxOsD
AKZzecKl7E1XS/V7u7NQzoRWfYMjyMnbUMVLg4vdTpJZsaZfDGmRUekLJJpjOQSb
B6KT2jkGJCPrSMdz+X8y+piccIEpAgMBAAGjUzBRMB0GA1UdDgQWBBTuZ/uOUreG
TMzPjJeCOWRSw5HjbjAfBgNVHSMEGDAWgBTuZ/uOUreGTMzPjJeCOWRSw5HjbjAP
BgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAKp0T+nO9NXGuzc5tW
M37FWivDQqbrf0Xkmq+Wt4QxV6CW/p1e1vM9kvpBiFw09LWUbYBTRTw5WfQepX4l
PkqygUn5IsOZf6/TMZnCQTEicf5lzPhCehBt16VeMmxL4LU21CppNDzEM6k+DLbj
J4DPPSDtYr2Pj3/BAfU3vkS0x+x6D5gQF8uqo4Xcknd7p2hvN9kvthqQ6rYhGWRR
6R9V38tWZG9WGrOynJmBV6AHncBVEFB2eYM+fD6nmTiH4/vLQl82VSev8AAkgPeR
jeGpY6Z45xe3v/G8SSIYPiGqVt+qA5aEDYAAYhssHrXgtfc4VoIoOIHTdTsT7jR+
rY0+
-----END CERTIFICATE-----`;

/** Client leaf cert signed by GraphQL Dev Root CA — for future mTLS Phase 3. */
export const GQL_TLS_CLIENT_CERT = `-----BEGIN CERTIFICATE-----
MIIDqzCCApOgAwIBAgIUMbGN2ntemao3bukDPtVTdhoG6TYwDQYJKoZIhvcNAQEL
BQAwVzEhMB8GA1UEAwwYUmVkZmlyZUZvcmdlIERldiBSb290IENBMRkwFwYDVQQK
DBBSZWRmaXJlRm9yZ2UgRGV2MRcwFQYDVQQLDA5HcmFwaFFMIFN0dWRpbzAeFw0y
NjA2MjAyMTM0MDFaFw0yODA5MjIyMTM0MDFaMFcxITAfBgNVBAMMGFJlZGZpcmVG
b3JnZSBUZXN0IENsaWVudDEZMBcGA1UECgwQUmVkZmlyZUZvcmdlIERldjEXMBUG
A1UECwwOR3JhcGhRTCBTdHVkaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDt2wCQczyiSIRzNtwL/TMrUgQN03XRrws+Tq3phx2YR3TNJ0lYJcTfuSzk
2AcRJTSP0EcNSqjKdajxWTuIRX05j3EBDV//rWDuABitKVAzrpBCaZ0Y9xpLoWbo
VDM+nBCiXRtLtexWCZzKlCSvZJd89vXHNF5iCK62ul1RJPenU2Q8cZ20h6o3wHl+
L/aki1tBJINDNGDIjr4wg19iPPcbAGgBWvb3D1ILdCHNT745lH/I9+CRapixIRdi
jwc83LgYdIaka1zwgZXEEmGFHwWNbSDCk2js/GOL4kSaZlNsbCMOOzate9LxRUog
sFvQ/cX4m5sq04O4CG9BA8dG0OL5AgMBAAGjbzBtMAkGA1UdEwQCMAAwCwYDVR0P
BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMCMB0GA1UdDgQWBBQlAjbPv1nlqxZ9
W0Qmxt6+XUvajTAfBgNVHSMEGDAWgBTuZ/uOUreGTMzPjJeCOWRSw5HjbjANBgkq
hkiG9w0BAQsFAAOCAQEAAtDBsFK7q5dn3lOs7vYV8s4RycTyd/o6ViffIjJSBm8U
chzYYUGR2mWVJl2IJsBZYE80aV9KGetzxv21kzYMmjsYrAJo09RI0OywMx2JeLVT
fj49c5BdI3ZSRUtTXRhSBs8qtGH+dBc4y4Mt0LzthlWVNguWRRaMbWWDTiMoGP0j
SiE8++OCq4JCE84EDNhfxpTyVyadfWjO8WwOO/7yvMyfM2Rr00nu4cZmqWdW/mv5
Z/THQzq0zdW27MSGcDTfpShTVrunJYmK4FWrWoMuLRjwnA/hgifcK+LFkiYwlEVp
8IG8wRabzvGea14uM8atsZeuZeCAQMZpr9fh/emjHg==
-----END CERTIFICATE-----`;

/** Client private key — paired with GQL_TLS_CLIENT_CERT for future mTLS. */
export const GQL_TLS_CLIENT_KEY = `-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDt2wCQczyiSIRz
NtwL/TMrUgQN03XRrws+Tq3phx2YR3TNJ0lYJcTfuSzk2AcRJTSP0EcNSqjKdajx
WTuIRX05j3EBDV//rWDuABitKVAzrpBCaZ0Y9xpLoWboVDM+nBCiXRtLtexWCZzK
lCSvZJd89vXHNF5iCK62ul1RJPenU2Q8cZ20h6o3wHl+L/aki1tBJINDNGDIjr4w
g19iPPcbAGgBWvb3D1ILdCHNT745lH/I9+CRapixIRdijwc83LgYdIaka1zwgZXE
EmGFHwWNbSDCk2js/GOL4kSaZlNsbCMOOzate9LxRUogsFvQ/cX4m5sq04O4CG9B
A8dG0OL5AgMBAAECggEANGlCiZHq9XN3RA/9kuK7KLuMyyMiXg7tMlCR/9hXDBwK
v739amAALrAWFWMIw51oJJxnW6Vs5hfhHzVjadauDkXuR6YT1jn1FtyMk3N8CbdY
cFnnVP32HF43V9Bd7ljjTXOotRkkN50soHLeVoua2d1tMPT4Ky/wl7EfKOc1bvgD
Xm1F5Cd92eTb25pToviQkRMF9cZUV0bSmGkte061W2r/zPJLjrQuJUbviK4c+hXb
9mtKyRG5Lu1WMbgXakS0LxGt/QxwuiBrIW440EV6RMlpiOlzPpeaFm+YQIsEDb5R
85UKYSpp30WOnV3uB15OJzxrNFZQSwgMrVXlUuLMFQKBgQD9332r7ZdRp9GbfSvi
Ad1o5Hbs0F1KqVdyNvLdGMmb8/1h33CiQg+bKVOe5yRg5f08DGwffF/NFxzHEk8P
KTPrxo9QFdPHpM5TAApnhEdVpRkw2cnPuVYE8ezQ9ZFjHx10A7aIXVmXxIPOxrt6
OasHXXN7I4ISTtPBZJYJwWt4HwKBgQDv2Sggw728AW2szXGmGbb6Zh3D9UpP1M/F
ht9zVY4TuhI66Fpk20tlGWGuJI7bNGBBhAJPkV9ZnwrMvY0mvxSN7H9i7uopM8iV
CnSa7Eqaipv5p1IhoV3seOu1DiCSDNghAvv8gSdD2VvjgCq/WrmyC6lrljDm+Oo6
yUpu/jSh5wKBgQCsLAuws/sxl5yh1OwT5Kvh3T+CL3V1kw8JGJbwt0TTjU9ENyLO
B/tJgWeClsOnK5LoTIxvdgwKrSgJIjOX1putxQWgjI0KEo0S4S4tMhqmzMceyDUD
uW/K/r9an5AwJwP0kCgUpyqBsParH0A6Di4dWpVc56HpBKi7uZm/l/tohQKBgC4D
jkRC6TqRV5YoT95a3pTJVHqMq3YHUNkHWAULa9dzAh5VB0qEG8HIjcnX76Q0Nyc6
iSr0q8NI1MyUrOi7DdlwfrvfNAM1kQyu1dIG9QUTBHtv0zzqdVdxl17D2BHM7wXe
SbOWn47Pu2Y453qQkEGNJTKjvLwDEwS2K1aB5F0PAoGABIC1wypyNjm77N0Kf/lz
surObiNUF5KRuFe/UZq/Ha7pIJZ6M57ryXCVelJh1/ak7OBH1+xz+eQmSP7bJw9T
PM2juvsbCzwhMpn1CKT0Qd70X0osdj0Fsek1iIgPRi7f2pSArt0tFTo9En96EOFV
sTloHM6sF25hgEFsV4J0XMc=
-----END PRIVATE KEY-----`;

// ── Session flags ─────────────────────────────────────────────────────────────

let _gqltEndpointSet = false;
let _gqltSkipCertEnabled = false;
let _gqltIntrospected = false;
let _gqltAuthConfigured = false;
let _gqltAuthExecuted = false;
let _gqltCaConfigured = false;
let _gqltCaIntrospected = false;
let _gqltMtlsEndpointSet = false;
let _gqltMtlsConfigured = false;
let _gqltMtlsIntrospected = false;

export function resetGqlTlsSessionFlags(): void {
  _gqltEndpointSet = false;
  _gqltSkipCertEnabled = false;
  _gqltIntrospected = false;
  _gqltAuthConfigured = false;
  _gqltAuthExecuted = false;
  _gqltCaConfigured = false;
  _gqltCaIntrospected = false;
  _gqltMtlsEndpointSet = false;
  _gqltMtlsConfigured = false;
  _gqltMtlsIntrospected = false;
}

// ── DOM helpers ───────────────────────────────────────────────────────────────

function isTlsToggleActive(): boolean {
  const btn = document.querySelector<HTMLButtonElement>(GQL.TLS_TOGGLE);
  return btn?.getAttribute('aria-pressed') === 'true';
}

// ── Guard helpers ─────────────────────────────────────────────────────────────

function endpointIsMtls(): boolean {
  const input = document.querySelector<HTMLInputElement>(GQL.ENDPOINT_INPUT);
  return !!(input?.value?.includes(':4445'));
}

async function ensureGqlTlsPanelOpen(ctx: DemoActionContext): Promise<void> {
  await ctx.waitFor(GQL.TLS_CONFIGURE, 3000);
  if (!document.querySelector(GQL.TLS_BODY)) {
    await ctx.click(GQL.TLS_CONFIGURE);
    await ctx.waitFor(GQL.TLS_BODY, 3000);
    await ctx.delay(600);
  }
}

async function setGqlSkipCertInModal(ctx: DemoActionContext, checked: boolean): Promise<void> {
  await ctx.waitFor(`${GQL.TLS_SKIP_CERT} input[type="checkbox"]`, 3000);
  const checkbox = document.querySelector<HTMLInputElement>(`${GQL.TLS_SKIP_CERT} input[type="checkbox"]`);
  if (checkbox && checkbox.checked !== checked) {
    checkbox.click();
    await ctx.delay(400);
  }
}

async function clearGqlTlsCertFields(ctx: DemoActionContext): Promise<void> {
  await ctx.fill(GQL.TLS_CA_CERT, '');
  await ctx.fill(GQL.TLS_CLIENT_CERT, '');
  await ctx.fill(GQL.TLS_CLIENT_KEY, '');
  await ctx.delay(150);
}

async function saveGqlTlsModal(ctx: DemoActionContext): Promise<void> {
  // Changes apply live via onTlsChange — Close dismisses the modal (Save may be disabled when !dirty).
  const closeBtn = document.querySelector<HTMLButtonElement>(GQL.TLS_CLOSE);
  if (closeBtn) {
    closeBtn.click();
  } else {
    await ctx.click(GQL.TLS_SAVE);
  }
  for (let i = 0; i < 20 && document.querySelector(GQL.TLS_BODY); i++) {
    await ctx.delay(50);
  }
  await ctx.delay(100);
}

/** Disable skip-cert and paste the dev CA certificate (Phase 2). */
export async function ensureTlsCaConfigured(ctx: DemoActionContext): Promise<void> {
  await ensureTlsAuthExecuted(ctx);
  if (_gqltCaConfigured) return;
  await ensureGqlTlsPanelOpen(ctx);
  await setGqlSkipCertInModal(ctx, false);
  if (isTlsToggleActive()) {
    const btn = document.querySelector<HTMLButtonElement>(GQL.TLS_TOGGLE);
    btn?.click();
    await ctx.delay(400);
  }
  await clearGqlTlsCertFields(ctx);
  await ctx.fill(GQL.TLS_CA_CERT, GQL_TLS_CA_CERT);
  await ctx.delay(500);
  await saveGqlTlsModal(ctx);
  _gqltSkipCertEnabled = false;
  _gqltCaConfigured = true;
}

/** Introspect with CA validation on port 4443 (Phase 2). */
export async function ensureTlsCaIntrospected(ctx: DemoActionContext): Promise<void> {
  await ensureTlsCaConfigured(ctx);
  if (_gqltCaIntrospected && document.querySelector(GQL.SCHEMA_BADGE_OK)) return;
  await ctx.click(GQL.INTROSPECT_BTN);
  await ctx.waitFor(GQL.SCHEMA_BADGE_OK, 25000);
  await ctx.delay(800);
  _gqltCaIntrospected = true;
}

/** Switch to the mTLS endpoint on port 4445. */
export async function ensureMtlsEndpoint(ctx: DemoActionContext): Promise<void> {
  await ensureTlsCaIntrospected(ctx);
  if (_gqltMtlsEndpointSet && endpointIsMtls()) return;
  await configureDemoTabEndpointOverride(ctx, GQL_TLS_MTLS_ENDPOINT);
  await ctx.waitFor(GQL.TLS_CONFIGURE, 3000);
  await ctx.delay(800);
  _gqltMtlsEndpointSet = true;
}

/** Configure CA + client cert + key for mTLS (Phase 3). */
export async function ensureMtlsConfigured(ctx: DemoActionContext): Promise<void> {
  await ensureMtlsEndpoint(ctx);
  if (_gqltMtlsConfigured) return;
  await ensureGqlTlsPanelOpen(ctx);
  await setGqlSkipCertInModal(ctx, false);
  await ctx.fill(GQL.TLS_CA_CERT, GQL_TLS_CA_CERT);
  await ctx.delay(400);
  await ctx.fill(GQL.TLS_CLIENT_CERT, GQL_TLS_CLIENT_CERT);
  await ctx.delay(400);
  await ctx.fill(GQL.TLS_CLIENT_KEY, GQL_TLS_CLIENT_KEY);
  await ctx.delay(500);
  await saveGqlTlsModal(ctx);
  _gqltMtlsConfigured = true;
}

/** Introspect over mTLS on port 4445 (Phase 3). */
export async function ensureMtlsIntrospected(ctx: DemoActionContext): Promise<void> {
  await ensureMtlsConfigured(ctx);
  if (_gqltMtlsIntrospected && document.querySelector(GQL.SCHEMA_BADGE_OK)) return;
  await ctx.click(GQL.INTROSPECT_BTN);
  await ctx.waitFor(GQL.SCHEMA_BADGE_OK, 25000);
  await ctx.delay(800);
  _gqltMtlsIntrospected = true;
}

/** Fill the HTTPS TLS endpoint if not already set. */
export async function ensureTlsEndpoint(ctx: DemoActionContext): Promise<void> {
  // Flag alone is the guard — once Phase 1 endpoint has been set, don't re-run
  // even if we're currently on a different endpoint (e.g. Phase 3 mTLS 4445).
  if (_gqltEndpointSet) return;
  await configureDemoTabEndpointOverride(ctx, GQL_TLS_HTTPS_ENDPOINT);
  await ctx.delay(200);
  _gqltEndpointSet = true;
}

/** Enable skip-cert toggle if not already enabled. */
export async function ensureSkipCertEnabled(ctx: DemoActionContext): Promise<void> {
  await ensureTlsEndpoint(ctx);
  if (_gqltSkipCertEnabled && isTlsToggleActive()) return;
  const btn = document.querySelector<HTMLButtonElement>(GQL.TLS_TOGGLE);
  if (btn && btn.getAttribute('aria-pressed') !== 'true') {
    btn.click();
    await ctx.delay(400);
  }
  _gqltSkipCertEnabled = true;
}

/** Introspect the TLS endpoint with skip-cert enabled. */
export async function ensureTlsIntrospected(ctx: DemoActionContext): Promise<void> {
  await ensureSkipCertEnabled(ctx);
  if (_gqltIntrospected && document.querySelector(GQL.SCHEMA_BADGE_OK)) return;
  await ctx.click(GQL.INTROSPECT_BTN);
  await ctx.waitFor(GQL.SCHEMA_BADGE_OK, 25000);
  await ctx.delay(600);
  _gqltIntrospected = true;
}

/** Configure Bearer auth for the auth-over-TLS step. */
export async function ensureTlsAuthConfigured(ctx: DemoActionContext): Promise<void> {
  await ensureTlsIntrospected(ctx);
  if (_gqltAuthConfigured) return;
  await selectAuthInPanel(ctx, 'bearer');
  await ctx.fill(GQL.AUTH_BEARER_INPUT, GQL_TLS_BEARER_TEMPLATE);
  await ctx.delay(500);
  await closeAuthPanelQuiet(ctx);
  _gqltAuthConfigured = true;
}

/** Execute with TLS auth and confirm the header appears in Metadata. */
export async function ensureTlsAuthExecuted(ctx: DemoActionContext): Promise<void> {
  await ensureTlsAuthConfigured(ctx);
  if (_gqltAuthExecuted) return;
  await ensureHealthQuery(ctx);
  await ctx.click(GQL.EXECUTE_BTN);
  await ctx.waitFor(GQL.RESPONSE_VIEWER, 15000);
  await ctx.delay(500);
  await ctx.click(GQL.RV_TAB_METADATA);
  await ctx.waitFor(GQL.RV_REQUEST_HEADERS, 5000);
  await ctx.delay(600);
  _gqltAuthExecuted = true;
}

/** Setup for Lesson GQL-5 — demo tab, health query, modals closed. */
export async function gqlTlsLessonSetup(ctx: DemoActionContext): Promise<void> {
  resetGqlLessonSessionFlags();
  resetGqlLesson2SessionFlags();
  resetLesson2VariablesHistoryFlags();
  resetGqlLesson3SessionFlags();
  resetGqlLesson4SessionFlags();
  resetGqlLesson5SessionFlags();
  resetGqlLesson6SessionFlags();
  resetGqlTlsSessionFlags();

  // Close any open auth panel
  await closeAuthPanelQuiet(ctx);

  const editorBtn = document.querySelector<HTMLElement>(GQL.MODE_EDITOR);
  if (editorBtn && !editorBtn.classList.contains('gql-mode-btn--active')) {
    editorBtn.click();
  }
  const responseTab = document.querySelector<HTMLElement>(GQL.RIGHT_TAB_RESPONSE);
  if (responseTab && responseTab.getAttribute('aria-selected') !== 'true') {
    responseTab.click();
  }
  await ctx.delay(200);
  const historyBtn = document.querySelector<HTMLElement>(GQL.ACTIVITY_HISTORY);
  if (historyBtn?.classList.contains('gql-activity-tab--active')) {
    historyBtn.click();
    await ctx.delay(200);
  }

  await ensureGqlDemoTab(ctx, 'gql-https-tls', 'HTTPS, TLS & Certificates');
  await fillGqlEditor(ctx, GQL_HEALTH_QUERY, { focus: false });
}

/** Cleanup for Lesson GQL-5 — close demo tab (HTTPS/skip-cert stay on demo tab only). */
export async function gqlTlsLessonCleanup(ctx: DemoActionContext): Promise<void> {
  resetGqlTlsSessionFlags();
  await closeGqlDemoTabs(ctx, 'gql-https-tls');
}
