/**
 * API Mock Studio selectors — single source for demos / E2E / lessons.
 * Values are CSS selectors usable with document.querySelector / Playwright.
 */
export const API_MOCK = {
  // ── Page shell ───────────────────────────────────────────────────────────
  STUDIO: '[data-testid="api-mock-studio"]',
  LIVE_REGION: '[data-testid="api-mock-live-region"]',
  EMPTY: '[data-testid="api-mock-empty"]',
  CREATE_FIRST: '[data-testid="api-mock-create-first"]',
  TITLEBAR: '[data-testid="api-mock-titlebar"]',
  OPEN_LIBRARY: '[data-testid="api-mock-open-library"]',
  LIBRARY_LANDING: '[data-testid="api-mock-library-landing"]',
  LIBRARY: '[data-testid="api-mock-library"]',
  LIBRARY_SEARCH: '[data-testid="api-mock-library-search"]',
  LIBRARY_CREATE: '[data-testid="api-mock-library-create"]',
  LIBRARY_MODAL: '[data-testid="api-mock-library-modal"]',
  LIBRARY_CLOSE: '[data-testid="api-mock-library-close"]',
  LIBRARY_LIST: '[data-testid="api-mock-library-list"]',
  LIBRARY_EMPTY: '[data-testid="api-mock-library-empty"]',
  LIBRARY_COUNT: '[data-testid="api-mock-library-count"]',
  /** Number of saved servers with no open tab; absent when every server is open. */
  PARKED_COUNT: '[data-testid="api-mock-parked-count"]',
  LIBRARY_ROW: '[data-testid="api-mock-library-list"] > li',
  libraryRow: (id: string) => `[data-testid="api-mock-library-row-${id}"]`,
  libraryOpen: (id: string) => `[data-testid="api-mock-library-open-${id}"]`,
  libraryDelete: (id: string) => `[data-testid="api-mock-library-delete-${id}"]`,

  // ── Workspace nav (Studio / Runtime / Conflicts) ──────────────────────────
  WORKSPACE_NAV: '[data-testid="api-mock-workspace-nav"]',
  VIEW_STUDIO: '[data-testid="api-mock-view-studio"]',
  VIEW_RUNTIME: '[data-testid="api-mock-view-runtime"]',
  VIEW_CONFLICTS: '[data-testid="api-mock-view-conflicts"]',
  IMPORT_MENU: '[data-testid="api-mock-import-menu"]',
  EXPORT: '[data-testid="api-mock-export"]',
  EXPORT_MENU: '[data-testid="api-mock-export-menu-panel"]',
  EXPORT_WORKSPACE: '[data-testid="api-mock-export-workspace"]',
  EXPORT_WORKSPACE_YAML: '[data-testid="api-mock-export-workspace-yaml"]',
  EXPORT_SERVERS: '[data-testid="api-mock-export-servers"]',
  EXPORT_ROUTES: '[data-testid="api-mock-export-routes"]',
  EXPORT_WIREMOCK: '[data-testid="api-mock-export-wiremock"]',
  EXPORT_HAR: '[data-testid="api-mock-export-har"]',
  EXPORT_GROUP_WORKSPACE: '[data-testid="api-mock-export-group-workspace"]',
  EXPORT_GROUP_SERVER: '[data-testid="api-mock-export-group-server"]',
  EXPORT_GROUP_INTEROP: '[data-testid="api-mock-export-group-interop"]',
  EXPORT_CONFIRM: '[data-testid="api-mock-export-confirm"]',
  EXPORT_REDACTION: '[data-testid="api-mock-export-redaction"]',
  EXPORT_TLS_KEY: '[data-testid="api-mock-export-tls-key"]',
  EXPORT_SECRET: '[data-testid="api-mock-export-secret"]',
  EXPORT_PREVIEW: '[data-testid="api-mock-export-preview"]',
  EXPORT_LOSS: '[data-testid="api-mock-export-loss"]',
  EXPORT_HAR_COUNT: '[data-testid="api-mock-export-har-count"]',
  EXPORT_MAPPING_COUNT: '[data-testid="api-mock-export-mapping-count"]',
  EXPORT_CLI: '[data-testid="api-mock-export-cli"]',
  EXPORT_CLOSE: '[data-testid="api-mock-export-close"]',
  EXPORT_COPY: '[data-testid="api-mock-export-copy"]',
  EXPORT_FILENAME: '[data-testid="api-mock-export-filename"]',
  IMPORT_LAST_EXPORT: '[data-testid="api-mock-import-last-export"]',
  CLI_SIMULATE: '[data-testid="api-mock-cli-simulate"]',
  CLI_SIMULATE_COPY: '[data-testid="api-mock-cli-simulate-copy"]',
  CLI_VERIFY: '[data-testid="api-mock-cli-verify"]',
  CLI_VERIFY_COPY: '[data-testid="api-mock-cli-verify-copy"]',
  EXPORT_CLI_VERIFY: '[data-testid="api-mock-export-cli-verify"]',
  COPIED_ROUTE: '[data-testid="api-mock-route-explorer"] button.am-route-item[data-copied="true"]',

  // ── Server tabs / bar ───────────────────────────────────────────────────
  SERVER_TABS: '[data-testid="api-mock-server-tabs"]',
  TAB_ADD: '[data-testid="api-mock-tab-add"]',
  SERVER_BAR: '[data-testid="api-mock-server-bar"]',
  ADDRESS: '[data-testid="api-mock-address"]',
  COPY_ADDRESS: '[data-testid="api-mock-copy-address"]',
  HTTP2_BADGE: '[data-testid="api-mock-http2-badge"]',
  DIRTY_BADGE: '[data-testid="api-mock-dirty-badge"]',
  STATUS_LABEL: '[data-testid="api-mock-status-label"]',
  GENERATION: '[data-testid="api-mock-generation"]',
  START: '[data-testid="api-mock-start"]',
  STOP: '[data-testid="api-mock-stop"]',
  APPLY: '[data-testid="api-mock-apply"]',
  RESTART: '[data-testid="api-mock-restart"]',
  SETTINGS: '[data-testid="api-mock-settings"]',
  OPEN_ROUTES: '[data-testid="api-mock-open-routes"]',
  SERVER_ERROR: '[data-testid="api-mock-server-error"]',
  NATIVE_WARNINGS: '[data-testid="api-mock-native-warnings"]',
  tab: (id: string) => `[data-testid="api-mock-tab-${id}"]`,
  tabClose: (id: string) => `[data-testid="api-mock-tab-close-${id}"]`,
  /** Inline rename input, mounted only while a tab is being renamed (F2 / double-click). */
  tabRename: (id: string) => `[data-testid="api-mock-tab-rename-${id}"]`,
  /** Any tab's rename input — use when the server id is not known up front. */
  TAB_RENAME_INPUT: '[data-testid="api-mock-server-tabs"] input[data-testid^="api-mock-tab-rename-"]',
  /** Active server tab button (aria-selected). */
  ACTIVE_TAB: '[data-testid="api-mock-server-tabs"] [data-testid^="api-mock-tab-"][aria-selected="true"]',
  /** Every server tab, in visual (workspace) order. */
  SERVER_TAB: '[data-testid="api-mock-server-tabs"] [role="tab"]',
  /** Tab matched by server name — each tab's `title` starts with the server name. */
  tabTitled: (name: string) => `[data-testid="api-mock-server-tabs"] [role="tab"][title^="${name}"]`,
  /** Per-tab runtime dot — one green dot per running listener. */
  TAB_STATUS_DOT: '[data-testid="api-mock-server-tabs"] [role="tab"] .am-status-dot',
  TAB_STATUS_DOT_RUNNING: '[data-testid="api-mock-server-tabs"] [role="tab"] .am-status-dot.running',

  // ── Server tab context menu (right-click) ────────────────────────────────
  TAB_CTX_MENU: '[data-testid="studio-tab-ctx-menu"]',
  TAB_CTX_RENAME: '[data-testid="studio-tab-ctx-rename"]',
  TAB_CTX_DUPLICATE: '[data-testid="studio-tab-ctx-duplicate"]',
  TAB_CTX_COPY_LABEL: '[data-testid="studio-tab-ctx-copy-label"]',
  TAB_CTX_CLOSE: '[data-testid="studio-tab-ctx-close"]',
  TAB_CTX_CLOSE_OTHERS: '[data-testid="studio-tab-ctx-close-others"]',
  TAB_CTX_CLOSE_RIGHT: '[data-testid="studio-tab-ctx-close-right"]',

  // ── Confirm dialog (shared app chrome — stop-and-close, tab limit) ────────
  CONFIRM_DIALOG: '[data-testid="confirm-dialog"]',
  CONFIRM_TITLE: '[data-testid="confirm-title"]',
  CONFIRM_ACCEPT: '[data-testid="confirm-accept"]',
  CONFIRM_CANCEL: '[data-testid="confirm-cancel"]',

  // ── Route explorer ───────────────────────────────────────────────────────
  ROUTE_EXPLORER: '[data-testid="api-mock-route-explorer"]',
  ADD_ROUTE: '[data-testid="api-mock-add-route"]',
  ADD_FOLDER: '[data-testid="api-mock-add-folder"]',
  ROUTE_SEARCH: '[data-testid="api-mock-route-search"]',
  ROUTE_FILTER: '[data-testid="api-mock-route-filter"]',
  ROUTE_FILTER_PANEL: '[data-testid="api-mock-route-filter-panel"]',
  FILTER_SHOW_DISABLED: '[data-testid="api-mock-filter-show-disabled"]',
  FILTER_CONFLICTS_ONLY: '[data-testid="api-mock-filter-conflicts-only"]',
  FILTER_METHOD: '[data-testid="api-mock-filter-method"]',
  CLOSE_ROUTES: '[data-testid="api-mock-close-routes"]',
  ROUTES_EMPTY: '[data-testid="api-mock-routes-empty"]',
  ROUTES_NO_MATCH: '[data-testid="api-mock-routes-no-match"]',
  /** Explorer rule rows only — never filter/search/add (`api-mock-route-filter` etc.). */
  ROUTE_ROW: '[data-testid="api-mock-route-explorer"] button.am-route-item[role="treeitem"]',
  /** First rule row — same as ROUTE_ROW; querySelector returns the first. */
  FIRST_ROUTE: '[data-testid="api-mock-route-explorer"] button.am-route-item[role="treeitem"]',
  ANALYZE: '[data-testid="api-mock-analyze"]',
  route: (id: string) => `[data-testid="api-mock-route-${id}"]`,
  /** Total rule count badge in the explorer head. */
  RULES_COUNT: '[data-testid="api-mock-rules-count"]',
  /** Conflict count badge — mounted only after Analyze finds overlaps. */
  CONFLICTS_COUNT: '[data-testid="api-mock-conflicts-count"]',
  /** Per-row trash affordance (opens the delete confirm). */
  routeDelete: (id: string) => `[data-testid="api-mock-route-delete-${id}"]`,
  /** First row's method chip / path / priority badge — row anatomy spotlights. */
  ROUTE_METHOD_CHIP: '[data-testid="api-mock-route-explorer"] button.am-route-item .am-method',
  ROUTE_PATH: '[data-testid="api-mock-route-explorer"] button.am-route-item .am-route-path',
  ROUTE_PRIORITY_BADGE: '[data-testid="api-mock-route-explorer"] button.am-route-item .am-badge',
  /** Rows the analyzer flagged as overlapping. */
  CONFLICT_ROUTE_ROW: '[data-testid="api-mock-route-explorer"] button.am-route-item.conflict[role="treeitem"]',

  // ── Route folders ────────────────────────────────────────────────────────
  /** Folder block (header + children). Class-based: the testid prefix also
   *  matches the folder rename / add / delete controls. */
  FOLDER_BLOCK: '[data-testid="api-mock-route-explorer"] .am-tree-folder-block',
  folder: (id: string) => `[data-testid="api-mock-folder-${id}"]`,
  /** Folder block by name — folder ids are minted at runtime. */
  folderNamed: (name: string) => `[data-testid="api-mock-route-explorer"] .am-tree-folder-block[data-folder-name="${name}"]`,
  /** Expand / collapse header (double-click renames). */
  folderToggle: (id: string) => `[data-testid="api-mock-folder-toggle-${id}"]`,
  FOLDER_TOGGLE: '[data-testid="api-mock-route-explorer"] button.am-tree-folder',
  FOLDER_NAME: '[data-testid="api-mock-route-explorer"] .am-folder-name',
  /** Inline rename input, mounted only while a folder is being renamed. */
  folderRenameInput: (id: string) => `[data-testid="api-mock-folder-rename-input-${id}"]`,
  FOLDER_RENAME_INPUT: '[data-testid="api-mock-route-explorer"] input.am-folder-rename',
  folderAddRoute: (id: string) => `[data-testid="api-mock-folder-add-route-${id}"]`,
  folderDelete: (id: string) => `[data-testid="api-mock-folder-delete-${id}"]`,
  folderEmpty: (id: string) => `[data-testid="api-mock-folder-empty-${id}"]`,
  /** Drop zone for unfiled rules — rendered only when at least one folder exists. */
  UNGROUPED_ZONE: '[data-testid="api-mock-ungrouped-zone"]',
  UNGROUPED_LABEL: '[data-testid="api-mock-ungrouped-label"]',

  // ── Route editor ─────────────────────────────────────────────────────────
  NO_ROUTE: '[data-testid="api-mock-no-route"]',
  NO_ROUTE_CREATE: '[data-testid="api-mock-no-route-create"]',
  ROUTE_EDITOR: '[data-testid="api-mock-route-editor"]',
  ROUTE_TITLE: '[data-testid="api-mock-route-title"]',
  ROUTE_NAME: '[data-testid="api-mock-route-name"]',
  ROUTE_ENABLED: '[data-testid="api-mock-route-enabled"]',
  METHOD_SELECT: '[data-testid="api-mock-method-select"]',
  PATH_INPUT: '[data-testid="api-mock-path-input"]',
  PATH_KIND: '[data-testid="api-mock-path-kind"]',
  PATH_TOOLBOX: '[data-testid="api-mock-path-toolbox"]',
  PRIORITY_INPUT: '[data-testid="api-mock-priority-input"]',
  ADD_CONDITION: '[data-testid="api-mock-add-condition"]',
  ADD_GROUP: '[data-testid="api-mock-add-group"]',
  CONDITIONS_EMPTY: '[data-testid="api-mock-conditions-empty"]',
  /** First Match condition row (excludes nested control testids). */
  FIRST_CONDITION: '[data-testid="api-mock-route-editor"] .am-matcher-row[data-testid^="api-mock-condition-"]',
  /** Last Match condition row after Add conditions. */
  LAST_CONDITION: '[data-testid="api-mock-route-editor"] .am-matcher-group .am-matcher-leaf:last-of-type .am-matcher-row',
  /** Every Match condition row, in render order — ids are minted per row. */
  CONDITION_ROWS: '[data-testid="api-mock-route-editor"] .am-matcher-row[data-testid^="api-mock-condition-"]',
  conditionRow: (predId: string) => `[data-testid="api-mock-condition-${predId}"]`,
  /** Source picker — Query / Header / Cookie / Security / Body / Path parameter / Transport. */
  conditionSource: (predId: string) => `[data-testid="api-mock-condition-source-${predId}"]`,
  /** Key being read: a free-text name, or the facet dropdown when the source is Security. */
  conditionSelector: (predId: string) => `[data-testid="api-mock-condition-selector-${predId}"]`,
  conditionOperator: (predId: string) => `[data-testid="api-mock-condition-operator-${predId}"]`,
  /** Expected value — disabled for the Present / Absent operators. */
  conditionValue: (predId: string) => `[data-testid="api-mock-condition-value-${predId}"]`,
  /**
   * First box of a two-part matcher: the JSONPath / XPath expression, or the field
   * name for form and multipart operators. The second box is `conditionValue`.
   */
  conditionExpr: (predId: string) => `[data-testid="api-mock-condition-expr-${predId}"]`,
  /** Body textarea for JSON subset / strict and the JSON / XML Schema operators. */
  conditionSchema: (predId: string) => `[data-testid="api-mock-condition-schema-${predId}"]`,
  conditionValueExpand: (predId: string) => `[data-testid="api-mock-condition-value-${predId}-expand"]`,
  conditionSchemaExpand: (predId: string) => `[data-testid="api-mock-condition-schema-${predId}-expand"]`,
  TEXT_EXPAND_MODAL: '[data-testid="api-mock-text-expand-modal"]',
  TEXT_EXPAND_EDITOR: '[data-testid="api-mock-text-expand-editor"]',
  TEXT_EXPAND_SEARCH: '[data-testid="api-mock-text-expand-search"]',
  TEXT_EXPAND_COUNT: '[data-testid="api-mock-text-expand-count"]',
  TEXT_EXPAND_PREV: '[data-testid="api-mock-text-expand-prev"]',
  TEXT_EXPAND_NEXT: '[data-testid="api-mock-text-expand-next"]',
  TEXT_EXPAND_PRETTY: '[data-testid="api-mock-text-expand-pretty"]',
  TEXT_EXPAND_UNDO: '[data-testid="api-mock-text-expand-undo"]',
  TEXT_EXPAND_REDO: '[data-testid="api-mock-text-expand-redo"]',
  TEXT_EXPAND_APPLY: '[data-testid="api-mock-text-expand-apply"]',
  TEXT_EXPAND_CLOSE: '[data-testid="api-mock-text-expand-close"]',
  /** equals ↔ contains on a JSONPath / XPath equals row (`options.matchStyle`). */
  conditionMatchStyle: (predId: string) => `[data-testid="api-mock-condition-matchstyle-${predId}"]`,
  /** Wand beside regex / glob / JSONPath / schema conditions. */
  conditionToolbox: (predId: string) => `[data-testid="api-mock-condition-toolbox-${predId}"]`,
  conditionRemove: (predId: string) => `[data-testid="api-mock-condition-remove-${predId}"]`,
  /** Boolean group shell — All of / Any of / None of. */
  group: (groupId: string) => `[data-testid="api-mock-group-${groupId}"]`,
  groupCombinator: (groupId: string) => `[data-testid="api-mock-group-combinator-${groupId}"]`,
  /** Live leaf tally in a group header — grows as conditions are added. */
  groupCount: (groupId: string) => `[data-testid="api-mock-group-count-${groupId}"]`,
  groupAddCondition: (groupId: string) => `[data-testid="api-mock-group-add-condition-${groupId}"]`,
  /** Nested groups only — `[ ] Group` inside a group (the root button is `ADD_GROUP`). */
  groupAddGroup: (groupId: string) => `[data-testid="api-mock-group-add-group-${groupId}"]`,
  groupRemove: (groupId: string) => `[data-testid="api-mock-group-remove-${groupId}"]`,
  /** Nested empty-group hint — an empty group does not affect matching. */
  groupEmpty: (groupId: string) => `[data-testid="api-mock-group-empty-${groupId}"]`,
  /** Shown when a group's combinator is None of — the evaluator fails closed on unevaluated children. */
  groupFailClosed: (groupId: string) => `[data-testid="api-mock-group-failclosed-${groupId}"]`,
  /** Nested groups only — the root group is never rendered with this class. */
  NESTED_GROUPS: '[data-testid="api-mock-route-editor"] .am-matcher-group.nested',
  /** POST /users Create User rule (Users gallery). */
  CREATE_USER_ROUTE: '[data-testid="api-mock-route-explorer"] button.am-route-item:has(.am-method.post)',
  /** Route editor body tabs (id-based — no data-testid on tab buttons). */
  BTAB_MATCH: '#api-mock-btab-match',
  BTAB_RESPONSE: '#api-mock-btab-response',
  BTAB_BEHAVIOR: '#api-mock-btab-behavior',
  BTAB_EXAMPLES: '#api-mock-btab-examples',
  BTAB_DOCS: '#api-mock-btab-docs',
  /** Documentation tab — contract metadata carried into exports and filters. */
  DOCS_FOLDER: '[data-testid="api-mock-docs-folder"]',
  DOCS_SUMMARY: '[data-testid="api-mock-docs-summary"]',
  DOCS_OPERATION_ID: '[data-testid="api-mock-docs-operation-id"]',
  DOCS_TAGS: '[data-testid="api-mock-docs-tags"]',
  SIMULATE: '[data-testid="api-mock-simulate"]',
  REVIEW_CONFLICTS: '[data-testid="api-mock-review-conflicts"]',
  CONFLICT_NOTICE: '[data-testid="api-mock-conflict-notice"]',
  RESPONSE_EDITOR: '[data-testid="api-mock-response-editor"]',
  VARIANT_BODY: '[data-testid="api-mock-variant-body"]',
  VARIANT_STATUS: '[data-testid="api-mock-variant-status"]',
  /** Editable HTTP reason phrase next to the status code (legacy clients read it). */
  VARIANT_STATUS_REASON: '[data-testid="api-mock-variant-status-reason"]',
  /** Status quick chips beside the status field (200 / 201 / 400 / 404 / 500). */
  variantStatusQuick: (code: number | string) => `[data-testid="api-mock-variant-status-quick-${code}"]`,
  VARIANT_STATUS_QUICK_200: '[data-testid="api-mock-variant-status-quick-200"]',
  VARIANT_STATUS_QUICK_201: '[data-testid="api-mock-variant-status-quick-201"]',
  VARIANT_STATUS_QUICK_404: '[data-testid="api-mock-variant-status-quick-404"]',
  VARIANT_NAME: '[data-testid="api-mock-variant-name"]',
  VARIANT_CONTENT_TYPE_SELECT: '[data-testid="api-mock-variant-content-type-select"]',
  /** Byte-size counter under the body editor — proves the body actually landed. */
  BODY_SIZE: '[data-testid="api-mock-body-size"]',
  BODY_FORMAT: '[data-testid="api-mock-body-format"]',
  BODY_TEMPLATE_BADGE: '[data-testid="api-mock-body-template-badge"]',
  /** Map request helpers onto a JSON body via the Data Mapper. */
  BODY_MAP: '[data-testid="api-mock-body-map"]',
  BODY_MAPPER: '[data-testid="api-mock-body-mapper"]',
  BODY_MAPPER_AUTOMAP: '[data-testid="api-mock-body-mapper"] .dm-toolbar .dm-toolbar-btn--primary',
  BODY_MAPPER_APPLY: '[data-testid="api-mock-body-mapper"] .dm-modal-footer .dm-modal-btn--primary',
  BODY_MAPPER_CANCEL: '[data-testid="api-mock-body-mapper"] .dm-modal-btn--secondary, [data-testid="api-mock-body-mapper-cancel"]',
  /** Monaco `{{` completion widget — mounted while the suggest list is open. */
  BODY_COMPLETIONS: '.suggest-widget.visible',
  BODY_BINARY_HINT: '[data-testid="api-mock-body-binary-hint"]',
  /** Right-hand response preview pane (status line, headers tally, rendered body). */
  RESPONSE_PREVIEW: '[data-testid="api-mock-response-preview"]',
  PREVIEW_STATUS: '[data-testid="api-mock-preview-status"]',
  PREVIEW_HEADERS: '[data-testid="api-mock-preview-headers"]',
  PREVIEW_COOKIES: '[data-testid="api-mock-preview-cookies"]',
  PREVIEW_BODY: '[data-testid="api-mock-preview-body"]',
  /** Sample request the preview uses to evaluate `{{helpers}}`. */
  PREVIEW_SAMPLE: '[data-testid="api-mock-preview-sample"]',
  /** Inline template diagnostic in the preview pane (broken helper). */
  TEMPLATE_ERROR: '[data-testid="api-mock-template-error"]',
  DIAG_TEMPLATE_ERRORS: '[data-testid="api-mock-template-error"]',
  RESPONSE_TAB_CONTENT: '[data-testid="api-mock-response-tab-content"]',
  RESPONSE_TAB_HEADERS: '[data-testid="api-mock-response-tab-headers"]',
  RESPONSE_TAB_TIMING: '[data-testid="api-mock-response-tab-timing"]',
  RESPONSE_TAB_FAULTS: '[data-testid="api-mock-response-tab-faults"]',
  RESPONSE_TAB_SELECTION: '[data-testid="api-mock-response-tab-selection"]',
  RESPONSE_TAB_OUTBOUND: '[data-testid="api-mock-response-tab-outbound"]',
  RESPONSE_MODE_BAR: '[data-testid="api-mock-response-mode-bar"]',
  RESPONSE_MODE_RULES: '[data-testid="api-mock-response-mode-rules"]',
  RESPONSE_MODE_SEQUENCE: '[data-testid="api-mock-response-mode-sequence"]',
  RESPONSE_MODE_WEIGHTED: '[data-testid="api-mock-response-mode-weighted"]',
  RESPONSE_MODE_STATE: '[data-testid="api-mock-response-mode-state"]',
  SEQUENCE_ORDER_NOTE: '[data-testid="api-mock-sequence-order-note"]',
  SEQUENCE_POSITION: '[data-testid="api-mock-sequence-position"]',
  ADD_HEADER: '[data-testid="api-mock-add-header"]',
  HEADER_LIST: '[data-testid="api-mock-header-list"]',
  HEADER_ROW: '[data-testid="api-mock-header-row"]',
  HEADER_KEY: '[data-testid="api-mock-header-key"]',
  HEADER_VALUE: '[data-testid="api-mock-header-value"]',
  HEADER_KEY_LAST: '[data-testid="api-mock-header-list"] [data-testid="api-mock-header-row"]:last-child [data-testid="api-mock-header-key"]',
  HEADER_VALUE_LAST: '[data-testid="api-mock-header-list"] [data-testid="api-mock-header-row"]:last-child [data-testid="api-mock-header-value"]',
  ADD_COOKIE: '[data-testid="api-mock-add-cookie"]',
  COOKIE_ROW: '[data-testid="api-mock-cookie-row"]',
  COOKIE_NAME: '[data-testid="api-mock-cookie-name"]',
  COOKIE_VALUE: '[data-testid="api-mock-cookie-value"]',
  COOKIE_HTTPONLY: '[data-testid="api-mock-cookie-httpOnly"]',
  ADD_VARIANT: '[data-testid="api-mock-add-variant"]',
  VARIANT_SIDEBAR: '[data-testid="api-mock-variant-sidebar"]',
  VARIANT_LIST: '[data-testid="api-mock-variant-list"]',
  VARIANT_CARD: '[data-testid="api-mock-variant-list"] [data-testid^="api-mock-variant-tab-"]',
  VARIANT_CARD_FIRST: '[data-testid="api-mock-variant-list"] [data-testid^="api-mock-variant-tab-"]:first-of-type',
  VARIANT_CARD_LAST: '[data-testid="api-mock-variant-list"] [data-testid^="api-mock-variant-tab-"]:last-of-type',
  VARIANT_DEFAULT_BADGE: '[data-testid="api-mock-variant-default-badge"]',
  SELECTION_PANEL: '[data-testid="api-mock-selection-panel"]',
  SELECTION_CONDITION: '[data-testid="api-mock-selection-condition"]',
  SELECTION_CONDITION_PATH: '[data-testid="api-mock-selection-condition-path"]',
  SELECTION_CONDITION_VALUE: '[data-testid="api-mock-selection-condition-value"]',
  SELECTION_DEFAULT: '[data-testid="api-mock-selection-default"]',
  SELECTION_DEFAULT_NOTE: '[data-testid="api-mock-selection-default-note"]',
  VARIANT_REQUIRED_STATE: '[data-testid="api-mock-variant-required-state"]',
  VARIANT_NEXT_STATE: '[data-testid="api-mock-variant-next-state"]',
  VARIANT_WEIGHT: '[data-testid="api-mock-variant-weight"]',
  COUNTER_ADD: '[data-testid="api-mock-counter-add"]',
  COUNTER_ROW: '[data-testid="api-mock-counter-row-0"]',
  COUNTER_KEY: '[data-testid="api-mock-counter-key-0"]',
  COUNTER_DELTA: '[data-testid="api-mock-counter-delta-0"]',
  TIMING_PANEL: '[data-testid="api-mock-timing-panel"]',
  VARIANT_DELAY: '[data-testid="api-mock-variant-delay"]',
  VARIANT_JITTER: '[data-testid="api-mock-variant-jitter"]',
  VARIANT_MAX_MATCHES: '[data-testid="api-mock-variant-max-matches"]',
  VARIANT_PROBABILITY: '[data-testid="api-mock-variant-probability"]',
  VARIANT_EXPIRES_AT: '[data-testid="api-mock-variant-expires-at"]',
  EXPIRES_QUICK_1H: '[data-testid="api-mock-expires-quick-1h"]',
  EXPIRES_DISPLAY: '[data-testid="api-mock-expires-display"]',
  EXPIRES_CALENDAR: '[data-testid="api-mock-expires-calendar"]',
  EXPIRES_CALENDAR_BTN: '[data-testid="api-mock-expires-calendar-btn"]',
  EXPIRES_CALENDAR_PREV: '[data-testid="api-mock-expires-cal-prev"]',
  EXPIRES_CALENDAR_NEXT: '[data-testid="api-mock-expires-cal-next"]',
  EXPIRES_CALENDAR_HOUR: '[data-testid="api-mock-expires-cal-hour"]',
  EXPIRES_CALENDAR_MINUTE: '[data-testid="api-mock-expires-cal-minute"]',
  EXPIRES_CALENDAR_TODAY: '[data-testid="api-mock-expires-cal-today"]',
  EXPIRES_CALENDAR_CLEAR: '[data-testid="api-mock-expires-cal-clear"]',
  EXPIRES_CALENDAR_APPLY: '[data-testid="api-mock-expires-cal-apply"]',
  TIMING_SPREAD: '[data-testid="api-mock-timing-spread"]',
  ELIGIBILITY_SUMMARY: '[data-testid="api-mock-eligibility-summary"]',
  FAULTS_PANEL: '[data-testid="api-mock-faults-panel"]',
  FAULT_SELECT: '[data-testid="api-mock-fault-select"]',
  fault: (id: string) => `[data-testid="api-mock-fault-${id}"]`,
  FAULT_NONE: '[data-testid="api-mock-fault-none"]',
  FAULT_TIMEOUT: '[data-testid="api-mock-fault-timeout"]',
  FAULT_RESET: '[data-testid="api-mock-fault-reset"]',
  FAULT_CLOSE: '[data-testid="api-mock-fault-close"]',
  FAULT_MALFORMED: '[data-testid="api-mock-fault-malformed"]',
  FAULT_DRIBBLE: '[data-testid="api-mock-fault-dribble"]',
  CHUNK_ADD: '[data-testid="api-mock-chunk-add"]',
  CHUNK_SCHEDULE: '[data-testid="api-mock-chunk-schedule"]',
  CHUNK_ROW: '[data-testid="api-mock-chunk-row-0"]',
  VARIANT_OUTBOUND: '[data-testid="api-mock-variant-outbound"]',
  TRANSFORM_ADD: '[data-testid="api-mock-transform-add"]',
  /** First transform row (ids are minted at add). */
  TRANSFORM_ROW: '[data-testid="api-mock-variant-outbound"] .am-transform-row',
  TRANSFORM_OP_FIRST: '[data-testid="api-mock-variant-outbound"] [data-testid^="api-mock-transform-op-"]',
  CALLBACK_ADD: '[data-testid="api-mock-callback-add"]',
  CALLBACK_URL_FIRST: '[data-testid="api-mock-variant-outbound"] [data-testid^="api-mock-callback-url-"]',
  CALLBACK_BODY_FIRST: '[data-testid="api-mock-variant-outbound"] [data-testid^="api-mock-callback-body-"]',
  CALLBACK_RETRIES_FIRST: '[data-testid="api-mock-variant-outbound"] [data-testid^="api-mock-callback-retries-"]',
  EXAMPLES_GRID: '[data-testid="api-mock-examples-grid"]',
  EXAMPLES_EMPTY: '[data-testid="api-mock-examples-empty"]',
  /** First Simulate button in the Examples grid (sample ids are minted at save). */
  EXAMPLE_SIMULATE: '[data-testid="api-mock-examples-grid"] [data-testid^="api-mock-example-simulate-"]',
  exampleSimulate: (id: string) => `[data-testid="api-mock-example-simulate-${id}"]`,
  /** First Attach on an unassociated example (ids are sample ids). */
  EXAMPLE_ATTACH: '[data-testid="api-mock-examples-grid"] [data-testid^="api-mock-example-attach-"]',
  exampleAttach: (id: string) => `[data-testid="api-mock-example-attach-${id}"]`,
  /** First Try in Requests in the Examples grid. */
  EXAMPLE_TRY_REQUESTS: '[data-testid="api-mock-examples-grid"] [data-testid^="api-mock-example-try-"]',
  exampleTry: (id: string) => `[data-testid="api-mock-example-try-${id}"]`,
  exampleRow: (id: string) => `[data-testid="api-mock-example-${id}"]`,

  // ── Live strip ───────────────────────────────────────────────────────────
  LIVE_STRIP: '[data-testid="api-mock-live-strip"]',
  LIVE_TRANSACTIONS: '[data-testid="api-mock-live-transactions"]',
  LIVE_TX_COUNT: '[data-testid="api-mock-live-transactions"] .am-count-badge',
  LIVE_CONFLICTS: '[data-testid="api-mock-live-conflicts"]',
  LIVE_VARIABLES: '[data-testid="api-mock-live-variables"]',
  LIVE_SETTINGS: '[data-testid="api-mock-live-settings"]',
  LIVE_CONSOLE: '[data-testid="api-mock-live-console"]',
  OPEN_RUNTIME: '[data-testid="api-mock-open-runtime"]',

  // ── Runtime page / dock ──────────────────────────────────────────────────
  RUNTIME_PAGE: '[data-testid="api-mock-runtime-page"]',
  DOCK: '[data-testid="api-mock-dock"]',
  dockTab: (id: string) => `[data-testid="api-mock-dock-tab-${id}"]`,
  DOCK_TAB_TRANSACTIONS: '[data-testid="api-mock-dock-tab-transactions"]',
  DOCK_TAB_STATE: '[data-testid="api-mock-dock-tab-state"]',
  DOCK_STATE: '[data-testid="api-mock-dock-state"]',
  DOCK_STATE_LIVE: '[data-testid="api-mock-dock-state-live"]',
  DOCK_SEQ_ROW: '[data-testid="api-mock-dock-seq-row"]',
  DOCK_TAB_VARIABLES: '[data-testid="api-mock-dock-tab-variables"]',
  DOCK_VARIABLES: '[data-testid="api-mock-dock-variables"]',
  VAR_ADD: '[data-testid="api-mock-var-add"]',
  VAR_ROW: '[data-testid="api-mock-dock-variables"] tbody tr[data-testid^="api-mock-var-row-"]',
  VAR_KEY_LAST: '[data-testid="api-mock-dock-variables"] tbody tr:last-child input[data-testid^="api-mock-var-key-"]',
  VAR_VALUE_LAST: '[data-testid="api-mock-dock-variables"] tbody tr:last-child input[data-testid^="api-mock-var-value-"]',
  VAR_SENSITIVE_LAST: '[data-testid="api-mock-dock-variables"] tbody tr:last-child [data-testid^="api-mock-var-sensitive-"]',
  STATE_RESET: '[data-testid="api-mock-state-reset"]',
  DOCK_TAB_SETTINGS: '[data-testid="api-mock-dock-tab-settings"]',
  DOCK_TAB_DIAGNOSTICS: '[data-testid="api-mock-dock-tab-diagnostics"]',
  DOCK_TAB_CONSOLE: '[data-testid="api-mock-dock-tab-console"]',
  CONSOLE: '[data-testid="api-mock-dock-console"]',
  CONSOLE_EMPTY: '[data-testid="api-mock-dock-console-empty"]',
  CONSOLE_LINE: '[data-testid="api-mock-dock-console"] .am-console-line',
  CONSOLE_SEARCH: '[data-testid="api-mock-console-search"]',
  CONSOLE_MATCH_COUNT: '[data-testid="api-mock-console-match-count"]',
  CONSOLE_FILTER_EMPTY: '[data-testid="api-mock-console-filter-empty"]',
  CONSOLE_CLEAR: '[data-testid="api-mock-console-clear"]',
  consoleFilter: (id: 'all' | 'started' | 'stopped' | 'applied' | 'errors') => `[data-testid="api-mock-console-filter-${id}"]`,
  JOURNAL_TOOLBAR: '[data-testid="api-mock-journal-toolbar"]',
  JOURNAL_FILTER: '[data-testid="api-mock-journal-filter"]',
  JOURNAL_EXPORT: '[data-testid="api-mock-journal-export"]',
  JOURNAL_CLEAR: '[data-testid="api-mock-journal-clear"]',
  /** First journal transaction row (table body only — never detail/action chrome). */
  JOURNAL_FIRST_ROW: '[data-testid="api-mock-dock"] table tbody tr[data-testid^="api-mock-tx-"]',
  TX_DETAIL: '[data-testid="api-mock-tx-detail"]',
  TX_OUTCOME: '[data-testid="api-mock-tx-outcome"]',
  TX_DETAIL_DURATION: '[data-testid="api-mock-tx-detail-duration"]',
  TX_DURATION: '[data-testid="api-mock-tx-duration"]',
  TX_IO: '[data-testid="api-mock-tx-io"]',
  TX_REQUEST: '[data-testid="api-mock-tx-request"]',
  TX_RESPONSE: '[data-testid="api-mock-tx-response"]',
  TX_RESPONSE_STATUS: '[data-testid="api-mock-tx-response-status"]',
  TX_SPLITTER: '[data-testid="api-mock-tx-splitter"]',
  TX_NOTICE: '[data-testid="api-mock-tx-notice"]',
  TX_CANDIDATES: '[data-testid="api-mock-tx-candidates"]',
  TX_NEAR_MISSES: '[data-testid="api-mock-tx-near-misses"]',
  TX_ACTIONS: '[data-testid="api-mock-tx-actions"]',
  TX_CREATE_ROUTE: '[data-testid="api-mock-tx-create-route"]',
  TX_SAVE_EXAMPLE: '[data-testid="api-mock-tx-save-example"]',
  TX_OPEN_REQUESTS: '[data-testid="api-mock-tx-open-requests"]',
  TX_COPY: '[data-testid="api-mock-tx-copy"]',
  TX_OPEN_CREATED: '[data-testid="api-mock-tx-open-created"]',
  TX_VIEW_EXAMPLE: '[data-testid="api-mock-tx-view-example"]',
  RUNTIME_GUIDE: '[data-testid="api-mock-runtime-guide"]',
  RUNTIME_SAMPLE_CURL: '[data-testid="api-mock-runtime-sample-curl"]',
  RUNTIME_COPY_CURL: '[data-testid="api-mock-runtime-copy-curl"]',
  RUNTIME_SETTINGS_PANEL: '[data-testid="api-mock-runtime-settings-panel"]',
  RUNTIME_SETTINGS_SAVE: '[data-testid="api-mock-runtime-settings-save"]',
  RUNTIME_SETTINGS_DIRTY: '[data-testid="api-mock-runtime-settings-dirty"]',
  RUNTIME_SETTINGS_CORS: '[data-testid="api-mock-runtime-settings-cors"]',
  RUNTIME_SETTINGS_CORS_ORIGINS: '[data-testid="api-mock-runtime-settings-cors-origins"]',
  RUNTIME_SETTINGS_INBOUND: '[data-testid="api-mock-runtime-settings-inbound"]',
  RUNTIME_SETTINGS_CONN: '[data-testid="api-mock-runtime-settings-conn"]',
  RUNTIME_SETTINGS_DRAIN: '[data-testid="api-mock-runtime-settings-drain"]',
  RUNTIME_SETTINGS_JOURNAL: '[data-testid="api-mock-runtime-settings-journal"]',
  RUNTIME_SETTINGS_JOURNAL_MAX: '[data-testid="api-mock-runtime-settings-journal-max"]',
  RUNTIME_SETTINGS_PERSIST: '[data-testid="api-mock-runtime-settings-persist"]',
  RUNTIME_SETTINGS_FALLBACK: '[data-testid="api-mock-runtime-settings-fallback"]',
  RUNTIME_SETTINGS_REDACT_HEADERS: '[data-testid="api-mock-runtime-settings-redact-headers"]',
  RUNTIME_SETTINGS_REDACT_PATHS: '[data-testid="api-mock-runtime-settings-redact-paths"]',
  JOURNAL_FILTER_EMPTY: '[data-testid="api-mock-journal-filter-empty"]',
  /** Empty journal after Clear — Runtime page uses the guide instead. */
  JOURNAL_EMPTY: '[data-testid="api-mock-dock-transactions-empty"]',
  DIAGNOSTICS: '[data-testid="api-mock-diagnostics"]',
  DIAG_MATCH_P95: '[data-testid="api-mock-diag-match-p95"]',
  DIAG_OUTCOMES: '[data-testid="api-mock-diag-outcomes"]',
  DIAG_GENERATION: '[data-testid="api-mock-diag-generation"]',
  DIAG_MATCH_LAST: '[data-testid="api-mock-diag-match-last"]',
  DIAG_JOURNAL_SIZE: '[data-testid="api-mock-diag-journal-size"]',
  tx: (id: string) => `[data-testid="api-mock-tx-${id}"]`,

  // ── Conflicts ────────────────────────────────────────────────────────────
  CONFLICTS_PAGE: '[data-testid="api-mock-conflicts-page"]',
  CONFLICTS_ANALYZE: '[data-testid="api-mock-conflicts-analyze"]',
  CONFLICT_INSPECTOR: '[data-testid="api-mock-conflict-inspector"]',
  CONFLICT_GUIDE: '[data-testid="api-mock-conflict-guide"]',
  CONFLICT_GUIDE_ANALYZE: '[data-testid="api-mock-conflict-guide-analyze"]',
  CONFLICT_SUMMARY: '[data-testid="api-mock-conflict-summary"]',
  CONFLICT_LIST: '[data-testid="api-mock-conflict-list"]',
  /** First conflict finding row in the list. */
  FIRST_FINDING: '[data-testid="api-mock-conflict-list"] button[data-testid^="api-mock-finding-"]',
  CONFLICT_DETAIL: '[data-testid="api-mock-conflict-detail"]',
  CONFLICT_WITNESS: '[data-testid="api-mock-conflict-witness"]',
  CONFLICT_POLICY_MULTIPLE: '[data-testid="api-mock-conflict-policy-multiple"]',
  CONFLICT_POLICY_EQUAL: '[data-testid="api-mock-conflict-policy-equal"]',
  CONFLICT_SIMULATE: '[data-testid="api-mock-conflict-simulate"]',
  CONFLICT_ACKNOWLEDGE: '[data-testid="api-mock-conflict-acknowledge"]',
  CONFLICT_ACK: '[data-testid="api-mock-conflict-ack"]',
  CONFLICT_ADJUST_PRIORITY: '[data-testid="api-mock-conflict-adjust-priority"]',
  CONFLICT_PRIO_MENU: '[data-testid="api-mock-conflict-prio-menu"]',
  CONFLICT_PRIO_LEFT: '[data-testid="api-mock-conflict-prio-left"]',
  CONFLICT_PRIO_RIGHT: '[data-testid="api-mock-conflict-prio-right"]',
  CONFLICT_APPLY: '[data-testid="api-mock-conflict-apply"]',
  CONFLICT_GOTO_LEFT: '[data-testid="api-mock-conflict-goto-left"]',
  CONFLICT_GOTO_RIGHT: '[data-testid="api-mock-conflict-goto-right"]',
  CONFLICT_FINGERPRINTS: '[data-testid="api-mock-conflict-fingerprints"]',
  CONFLICT_FINGERPRINTS_SUMMARY: '[data-testid="api-mock-conflict-fingerprints-summary"]',
  CONFLICT_FINGERPRINTS_OPEN: '[data-testid="api-mock-conflict-fingerprints"][open]',
  CONFLICT_FINGERPRINT_HASHES: '[data-testid="api-mock-conflict-fingerprint-hashes"]',
  CONFLICT_FINGERPRINT_LEFT: '[data-testid="api-mock-conflict-fingerprint-left"]',
  CONFLICT_FINGERPRINT_RIGHT: '[data-testid="api-mock-conflict-fingerprint-right"]',
  CONFLICT_FINGERPRINT_RELATION: '[data-testid="api-mock-conflict-fingerprint-relation"]',
  CONFLICT_STALE: '[data-testid="api-mock-conflict-stale"]',
  CONFLICT_COMPARE: '[data-testid="api-mock-conflict-compare"]',
  CONFLICT_DIMENSIONS: '[data-testid="api-mock-conflict-dimensions"]',
  CONFLICT_DIM_ROW: '[data-testid="api-mock-conflict-dim-row"]',
  CONFLICT_DIM_UNKNOWN: '[data-testid="api-mock-conflict-dim-row"][data-result="unknown"]',
  CONFLICT_FILTER_EMPTY: '[data-testid="api-mock-conflict-filter-empty"]',
  conflictFilter: (kind: string) => `[data-testid="api-mock-conflict-filter-${kind}"]`,
  finding: (id: string) => `[data-testid="api-mock-finding-${id}"]`,

  // ── Pattern Toolbox ──────────────────────────────────────────────────────
  PATTERN_TOOLBOX: '[data-testid="api-mock-pattern-toolbox"]',
  TOOLBOX_APPLY: '[data-testid="api-mock-toolbox-apply"]',
  TOOLBOX_CANCEL: '[data-testid="api-mock-toolbox-cancel"]',
  TOOLBOX_TAB_JSONPATH: '[data-testid="api-mock-toolbox-tab-jsonpath"]',
  TOOLBOX_TAB_CONSTRAINTS: '[data-testid="api-mock-toolbox-tab-constraints"]',
  TOOLBOX_TAB_REGEX: '[data-testid="api-mock-toolbox-tab-regex"]',
  TOOLBOX_TAB_PATH: '[data-testid="api-mock-toolbox-tab-path"]',
  TOOLBOX_TAB_XPATH: '[data-testid="api-mock-toolbox-tab-xpath"]',
  TOOLBOX_TAB_SCHEMA: '[data-testid="api-mock-toolbox-tab-schema"]',
  TOOLBOX_JSON_SAMPLE: '[data-testid="api-mock-toolbox-json-sample"]',
  /** Valid / Invalid JSON badge above the sample body editor. */
  TOOLBOX_JSON_VALID: '[data-testid="api-mock-toolbox-json-valid"]',
  TOOLBOX_JSONPATH: '[data-testid="api-mock-toolbox-jsonpath"]',
  TOOLBOX_JSON_RESOLVED: '[data-testid="api-mock-toolbox-json-resolved"]',
  TOOLBOX_JSON_EXPECTED: '[data-testid="api-mock-toolbox-json-expected"]',
  TOOLBOX_JSON_RESULT: '[data-testid="api-mock-toolbox-json-result"]',
  TOOLBOX_REGEX: '[data-testid="api-mock-toolbox-regex"]',
  TOOLBOX_SAMPLE: '[data-testid="api-mock-toolbox-sample"]',
  /** XPath tab panel root. */
  TOOLBOX_XPATH: '[data-testid="api-mock-toolbox-xpath"]',
  /** XPath tab — sample XML the expression is tested against. */
  TOOLBOX_XPATH_SAMPLE: '[data-testid="api-mock-toolbox-xpath-sample"]',
  /** XPath tab — expand Sample XML into the full-text popup. */
  TOOLBOX_XPATH_SAMPLE_EXPAND: '[data-testid="api-mock-toolbox-xpath-sample-expand"]',
  /** XPath tab — well-formed / not-XML badge on the sample pane. */
  TOOLBOX_XPATH_VALID: '[data-testid="api-mock-toolbox-xpath-valid"]',
  /** XPath tab — the expression being composed. */
  TOOLBOX_XPATH_EXPR: '[data-testid="api-mock-toolbox-xpath-expr"]',
  /** XPath tab — what the expression selects from the sample (read-only). */
  TOOLBOX_XPATH_RESOLVED: '[data-testid="api-mock-toolbox-xpath-resolved"]',
  /** XPath tab — optional equals value; empty applies `xpath_exists`. */
  TOOLBOX_XPATH_VALUE: '[data-testid="api-mock-toolbox-xpath-value"]',
  /** XPath tab — live ✓ / × verdict for the expression against the sample. */
  TOOLBOX_XPATH_RESULT: '[data-testid="api-mock-toolbox-xpath-result"]',
  /** XPath tab presets — `Root element`, `Local name`, `Text value`. */
  toolboxXPathPreset: (name: string) => `[data-testid="api-mock-toolbox-xpath-preset-${name}"]`,
  /** Schema tab panel root. */
  TOOLBOX_SCHEMA: '[data-testid="api-mock-toolbox-schema"]',
  /** Schema tab — the schema being composed (JSON Schema, or XML element names). */
  TOOLBOX_SCHEMA_EDITOR: '[data-testid="api-mock-toolbox-schema-editor"]',
  TOOLBOX_SCHEMA_KIND_JSON: '[data-testid="api-mock-toolbox-schema-kind-json"]',
  TOOLBOX_SCHEMA_KIND_XML: '[data-testid="api-mock-toolbox-schema-kind-xml"]',
  /** Schema tab presets — `JSON object`, `Required id`, `XML names`. */
  toolboxSchemaPreset: (name: string) => `[data-testid="api-mock-toolbox-schema-preset-${name}"]`,
  toolboxTab: (id: string) => `[data-testid="api-mock-toolbox-tab-${id}"]`,
  /** Path tab — explicit kind select (Exact / Parameterized / Glob / Regex). */
  TOOLBOX_KIND: '[data-testid="api-mock-toolbox-kind"]',
  /** Path tab — the pattern being composed (not yet applied to the rule). */
  TOOLBOX_PATTERN: '[data-testid="api-mock-toolbox-pattern"]',
  /** Path tab — case-insensitive matching toggle. */
  TOOLBOX_CI: '[data-testid="api-mock-toolbox-ci"]',
  /** Path tab — live match verdict for the Test path, incl. captured params. */
  TOOLBOX_RESULT: '[data-testid="api-mock-toolbox-result"]',
  /** Path tab — Generalize block: one button per path segment. */
  TOOLBOX_SEGMENTS: '[data-testid="api-mock-toolbox-segments"]',
  toolboxSegment: (index: number) => `[data-testid="api-mock-toolbox-segment-${index}"]`,
  /** Path tab — the template the product suggests for the imported path. */
  TOOLBOX_SUGGESTED: '[data-testid="api-mock-toolbox-suggested"]',
  /** Path tab — captured path parameters for the current Test path. */
  TOOLBOX_EXTRACTION: '[data-testid="api-mock-toolbox-extraction"]',
  toolboxPreset: (label: string) => `[data-testid="api-mock-toolbox-preset-${label}"]`,
  /** Regex tab — pattern library search box. */
  TOOLBOX_LIBRARY_SEARCH: '[data-testid="api-mock-toolbox-library-search"]',
  toolboxLib: (name: string) => `[data-testid="api-mock-toolbox-lib-${name}"]`,
  /** Regex tab — Valid / Invalid badge for the composed expression. */
  TOOLBOX_SAFETY: '[data-testid="api-mock-toolbox-safety"]',
  /** Regex tab — Ignore case / Case sensitive flag chips. */
  TOOLBOX_FLAG_CI: '[data-testid="api-mock-toolbox-flag-ci"]',
  TOOLBOX_FLAG_CS: '[data-testid="api-mock-toolbox-flag-cs"]',
  /** Regex tab — live sample rows (ids `p0`/`f0`… after a library pick). */
  TOOLBOX_SAMPLE_ROWS: '[data-testid="api-mock-pattern-toolbox"] .am-sample-list .am-sample-row',
  toolboxSampleRow: (id: string) => `[data-testid="api-mock-toolbox-sample-row-${id}"]`,
  toolboxSampleValue: (id: string) => `[data-testid="api-mock-toolbox-sample-value-${id}"]`,
  toolboxSampleExpect: (id: string) => `[data-testid="api-mock-toolbox-sample-expect-${id}"]`,
  /** Query & headers tab — composes match conditions instead of a path pattern. */
  TOOLBOX_ADD_CONSTRAINT: '[data-testid="api-mock-toolbox-add-constraint"]',
  /** Pending constraint rows — the tab opens with one blank row (`c1`). */
  TOOLBOX_CONSTRAINT_ROWS: '[data-testid="api-mock-pattern-toolbox"] .am-constraint-row',
  toolboxConstraint: (id: string) => `[data-testid="api-mock-toolbox-constraint-${id}"]`,
  toolboxConstraintSource: (id: string) => `[data-testid="api-mock-toolbox-constraint-source-${id}"]`,
  toolboxConstraintName: (id: string) => `[data-testid="api-mock-toolbox-constraint-name-${id}"]`,
  toolboxConstraintOperator: (id: string) => `[data-testid="api-mock-toolbox-constraint-operator-${id}"]`,
  toolboxConstraintValue: (id: string) => `[data-testid="api-mock-toolbox-constraint-value-${id}"]`,

  // ── Import review ────────────────────────────────────────────────────────
  IMPORT_REVIEW: '[data-testid="api-mock-import-review"]',
  IMPORT_CLOSE: '[data-testid="api-mock-import-close"]',
  IMPORT_CONFIRM: '[data-testid="api-mock-import-confirm"]',
  IMPORT_CANCEL: '[data-testid="api-mock-import-cancel"]',
  IMPORT_MODE_MERGE: '[data-testid="api-mock-import-mode-merge"]',
  IMPORT_MODE_REPLACE: '[data-testid="api-mock-import-mode-replace"]',
  IMPORT_MODE_COPY: '[data-testid="api-mock-import-mode-copy"]',
  IMPORT_PREVIEW: '[data-testid="api-mock-import-preview-block"]',
  IMPORT_ROUTE_LIST: '[data-testid="api-mock-import-route-list"]',
  CURL_INPUT: '[data-testid="api-mock-curl-input"]',
  CURL_PARSE: '[data-testid="api-mock-curl-parse"]',
  IMPORT_PASTE: '[data-testid="api-mock-import-paste"]',
  IMPORT_PARSE: '[data-testid="api-mock-import-parse"]',
  IMPORT_SOURCES: '[data-testid="api-mock-import-sources"]',
  IMPORT_FOLDER: '[data-testid="api-mock-import-folder"]',
  IMPORT_FOLDER_MENU: '[data-testid="api-mock-import-folder-menu"]',
  IMPORT_FOLDER_NEW: '[data-testid="api-mock-import-folder-new"]',
  IMPORT_NEW_FOLDER_NAME: '[data-testid="api-mock-import-new-folder-name"]',
  IMPORT_PRIORITY: '[data-testid="api-mock-import-priority"]',
  IMPORT_GENERALIZE: '[data-testid="api-mock-import-generalize"]',
  IMPORT_LOSS: '[data-testid="api-mock-import-loss"]',
  IMPORT_REPLACE_WARNING: '[data-testid="api-mock-import-replace-warning"]',
  IMPORT_PREVIEW_PATH: '[data-testid="api-mock-import-preview-path"]',
  IMPORT_CATALOG_LIST: '[data-testid="api-mock-import-catalog-list"]',
  IMPORT_CATALOG_FILTER: '[data-testid="api-mock-import-catalog-filter"]',
  IMPORT_CATALOG_SELECT_ALL: '[data-testid="api-mock-import-catalog-select-all"]',
  IMPORT_REQUESTS_LIST: '[data-testid="api-mock-import-requests-list"]',
  IMPORT_REQUESTS_FILTER: '[data-testid="api-mock-import-requests-filter"]',
  IMPORT_REQUESTS_SELECT_ALL: '[data-testid="api-mock-import-requests-select-all"]',
  importSource: (id: string) => `[data-testid="api-mock-import-source-${id}"]`,
  /** Disabled / draft explorer rows (imports land enabled:false). */
  DRAFT_ROUTE: '[data-testid="api-mock-route-explorer"] button.am-route-item.disabled[role="treeitem"]',
  /** First draft row — same as DRAFT_ROUTE (querySelector returns first). */
  FIRST_DRAFT_ROUTE: '[data-testid="api-mock-route-explorer"] button.am-route-item.disabled[role="treeitem"]',
  /** Explorer footer draft tally text. */
  ROUTES_FOOTER: '[data-testid="api-mock-routes-footer"]',

  // ── Simulate ─────────────────────────────────────────────────────────────
  SIMULATE_WORKSPACE: '[data-testid="api-mock-simulate-workspace"]',
  SIMULATE_RUN: '[data-testid="api-mock-simulate-run"]',
  SIMULATE_RUN_ALL: '[data-testid="api-mock-simulate-run-all"]',
  SIMULATE_EXPORT: '[data-testid="api-mock-simulate-export"]',
  SIMULATE_SEED: '[data-testid="api-mock-simulate-seed"]',
  SIMULATE_CLOSE: '[data-testid="api-mock-simulate-close"]',
  SIMULATE_PATH: '[data-testid="api-mock-simulate-path"]',
  SIMULATE_METHOD: '[data-testid="api-mock-simulate-method"]',
  SIMULATE_HEADERS: '[data-testid="api-mock-simulate-headers"]',
  SIMULATE_BODY: '[data-testid="api-mock-simulate-body"]',
  SIMULATE_CERT_SUBJECT: '[data-testid="api-mock-simulate-cert-subject"]',
  SIMULATE_BODY_EXPAND: '[data-testid="api-mock-simulate-body-expand"]',
  SIMULATE_RESULT: '[data-testid="api-mock-simulate-result"]',
  SIMULATE_SAMPLES: '[data-testid="api-mock-sim-samples"]',
  SIMULATE_SAMPLE_STATE: '[data-testid="api-mock-sim-sample-state"]',
  SIMULATE_SAMPLE_HEALTH: '[data-testid="api-mock-sim-sample-sample-health"]',
  SIMULATE_SUMMARY: '[data-testid="api-mock-simulate-summary"]',
  SIMULATE_TAB_TRACE: '[data-testid="api-mock-sim-tab-trace"]',
  SIMULATE_TAB_REQUEST: '[data-testid="api-mock-sim-tab-request"]',
  SIMULATE_TAB_RENDERED: '[data-testid="api-mock-sim-tab-rendered"]',
  SIMULATE_TAB_ASSERTIONS: '[data-testid="api-mock-sim-tab-assertions"]',
  SIMULATE_TIMELINE_FIRST: '[data-testid="api-mock-sim-timeline-1"]',
  SIMULATE_TIMELINE_DELAY: '[data-testid="api-mock-sim-timeline-5"]',
  SIMULATE_TIMELINE_FAULT: '[data-testid="api-mock-sim-timeline-6"]',
  SIMULATE_VIRTUAL_DELAY: '[data-testid="api-mock-sim-virtual-delay"]',
  SIMULATE_FAULT_BADGE: '[data-testid="api-mock-sim-fault-badge"]',
  SIMULATE_FAULT_TIMELINE: '[data-testid="api-mock-sim-fault-timeline"]',
  SIMULATE_NORMALIZED: '[data-testid="api-mock-sim-normalized"]',
  SIMULATE_RENDERED: '[data-testid="api-mock-sim-rendered"]',
  SIMULATE_RENDERED_BODY: '[data-testid="api-mock-sim-rendered-body"]',
  SIMULATE_RENDERED_FORMAT: '[data-testid="api-mock-sim-rendered-format"]',
  SIMULATE_RENDERED_STATUS: '[data-testid="api-mock-sim-rendered-status"]',
  SIMULATE_ASSERTIONS: '[data-testid="api-mock-sim-assertions"]',
  SIMULATE_SAVE_SAMPLE: '[data-testid="api-mock-simulate-save-sample"]',
  SIMULATE_SAMPLE_NAME: '[data-testid="api-mock-simulate-sample-name"]',
  SIMULATE_SAMPLE_ADHOC: '[data-testid="api-mock-sim-sample-adhoc"]',
  SIMULATE_SAMPLE_ADHOC_BTN: '[data-testid="api-mock-sim-sample-adhoc"] .am-sim-sample-btn',
  SIMULATE_MAIN: '[data-testid="api-mock-sim-main"]',
  SIMULATE_SECTION_SAVED: '[data-testid="api-mock-sim-section-saved"]',
  SIMULATE_SECTION_SCRATCH: '[data-testid="api-mock-sim-section-scratch"]',
  SIMULATE_SECTION_FROM_RULES: '[data-testid="api-mock-sim-section-from-rules"]',
  simSample: (id: string) => `[data-testid="api-mock-sim-sample-${id}"]`,
  simSampleBtn: (id: string) => `[data-testid="api-mock-sim-sample-${id}"] .am-sim-sample-btn`,
  /** First FAIL badge on a saved sample after an expectation mismatch. */
  SIMULATE_FAIL_BADGE: '[data-testid="api-mock-sim-sample-fail"]',
  SIMULATE_ASSERT_ROW_OUTCOME: '[data-testid="api-mock-sim-assert-row-outcome"]',
  SIMULATE_ASSERT_ROW_STATUS: '[data-testid="api-mock-sim-assert-row-status"]',
  SIMULATE_ASSERT_ROW_BODY: '[data-testid="api-mock-sim-assert-row-body"]',
  SIMULATE_ASSERT_STATUS: '[data-testid="api-mock-sim-assert-status"]',
  SIMULATE_ASSERT_BODY: '[data-testid="api-mock-sim-assert-body"]',
  SIMULATE_ASSERT_FAIL: '[data-testid="api-mock-sim-assert-fail"]',
  SIMULATE_EXPORT_CONFIRM: '[data-testid="api-mock-sim-export-confirm"]',
  SIMULATE_EXPORT_PREVIEW: '[data-testid="api-mock-sim-export-preview"]',
  SIMULATE_EXPORT_FILENAME: '[data-testid="api-mock-sim-export-filename"]',
  SIMULATE_VIEW_REQUEST: '[data-testid="api-mock-sim-view-request"]',
  SIMULATE_VIEW_RESULTS: '[data-testid="api-mock-sim-view-results"]',
  simTab: (id: 'trace' | 'request' | 'rendered' | 'assertions') => `[data-testid="api-mock-sim-tab-${id}"]`,
  /** Decision-trace outcome badge — MATCHED / UNMATCHED / AMBIGUOUS / FAULT. */
  SIMULATE_OUTCOME: '[data-testid="api-mock-sim-outcome"]',
  /** Winner badge on the selected candidate. */
  SIMULATE_WINNER: '[data-testid="api-mock-sim-winner"]',
  /** Specificity score list — only when two or more rules tied at the highest priority. */
  SIMULATE_SPECIFICITY: '[data-testid="api-mock-sim-specificity"]',
  simSpecificityRow: (routeId: string) => `[data-testid="api-mock-sim-specificity-${routeId}"]`,
  /** Timeline step 3 — Apply selection policy. */
  SIMULATE_TIMELINE_POLICY: '[data-testid="api-mock-sim-timeline-3"]',
  /** Every evaluated candidate row in the decision trace. */
  SIMULATE_CANDIDATES: '[data-testid="api-mock-simulate-result"] .am-candidate',
  simCandidate: (routeId: string) => `[data-testid="api-mock-sim-candidate-${routeId}"]`,
  /** Per-predicate tick rows inside the trace — method, path, then one per condition. */
  SIMULATE_PREDICATE_ROWS: '[data-testid="api-mock-simulate-result"] .am-candidate .am-predicate',
  simPredicateRows: (routeId: string) => `[data-testid="api-mock-sim-candidate-${routeId}"] .am-predicate`,

  // ── Server settings (TLS / Proxy) ─────────────────────────────────────────
  SETTINGS_MODAL: '[data-testid="api-mock-settings-modal"]',
  SETTINGS_NAME: '[data-testid="api-mock-settings-name"]',
  SETTINGS_PORT: '[data-testid="api-mock-settings-port"]',
  /** Inline error when the typed port is already claimed by another saved mock. */
  SETTINGS_PORT_TAKEN: '[data-testid="api-mock-settings-port-taken"]',
  SETTINGS_SAVE: '[data-testid="api-mock-settings-save"]',
  SETTINGS_CANCEL: '[data-testid="api-mock-settings-cancel"]',
  settingsTab: (id: string) => `[data-testid="api-mock-settings-tab-${id}"]`,
  SETTINGS_TAB_GENERAL: '[data-testid="api-mock-settings-tab-general"]',
  SETTINGS_PANEL_GENERAL: '[data-testid="api-mock-settings-panel-general"]',
  SETTINGS_TAB_SELECTION: '[data-testid="api-mock-settings-tab-selection"]',
  SETTINGS_PANEL_SELECTION: '[data-testid="api-mock-settings-panel-selection"]',
  SETTINGS_MULTIPLE_MATCH: '[data-testid="api-mock-settings-multiple-match"]',
  SETTINGS_EQUAL_POLICY: '[data-testid="api-mock-settings-equal-priority"]',
  SETTINGS_AMBIGUITY_STATUS: '[data-testid="api-mock-settings-ambiguity-status"]',
  SETTINGS_AMBIGUITY_BODY: '[data-testid="api-mock-settings-ambiguity-body"]',
  /** Host select (CustomSelect — 127.0.0.1 / localhost / 0.0.0.0). */
  SETTINGS_HOST: '[data-testid="api-mock-settings-host"]',
  /** LAN-exposure warning, shown only while host is `0.0.0.0`. */
  SETTINGS_HOST_WARNING: '[data-testid="api-mock-settings-host-warning"]',
  SETTINGS_BASE_PATH: '[data-testid="api-mock-settings-basepath"]',
  /** Live listen-URL preview at the top of the modal — updates as fields change. */
  SETTINGS_LISTEN_URL: '[data-testid="api-mock-settings-listen-url"]',
  SETTINGS_PANEL_TLS: '[data-testid="api-mock-settings-panel-tls"]',
  SETTINGS_TAB_TLS: '[data-testid="api-mock-settings-tab-tls"]',
  SETTINGS_TLS_ENABLED: '[data-testid="api-mock-settings-tls-enabled"]',
  SETTINGS_TLS_GENERATE: '[data-testid="api-mock-settings-tls-generate"]',
  SETTINGS_TLS_CERT: '[data-testid="api-mock-settings-tls-cert"]',
  SETTINGS_TLS_KEY: '[data-testid="api-mock-settings-tls-key"]',
  SETTINGS_TAB_PROXY: '[data-testid="api-mock-settings-tab-proxy"]',
  SETTINGS_PANEL_PROXY: '[data-testid="api-mock-settings-panel-proxy"]',
  SETTINGS_PROXY_ENABLED: '[data-testid="api-mock-settings-proxy-enabled"]',
  SETTINGS_PROXY_DENY: '[data-testid="api-mock-settings-proxy-deny"]',
  SETTINGS_PROXY_ALLOWLIST: '[data-testid="api-mock-settings-proxy-allowlist"]',
  SETTINGS_PROXY_PRIVATE: '[data-testid="api-mock-settings-proxy-private"]',
  SETTINGS_PROXY_FORWARD_AUTH: '[data-testid="api-mock-settings-proxy-forward-auth"]',
  SETTINGS_PROXY_RECORD: '[data-testid="api-mock-settings-proxy-record"]',
  SETTINGS_PROXY_LOOP: '[data-testid="api-mock-settings-proxy-loop"]',
  SETTINGS_CALLBACKS: '[data-testid="api-mock-settings-callbacks"]',
  SETTINGS_CALLBACK_ALLOWLIST: '[data-testid="api-mock-settings-callback-allowlist"]',
  SETTINGS_FALLBACK_MODE: '[data-testid="api-mock-settings-fallback-mode"]',
  SETTINGS_MTLS_ENABLED: '[data-testid="api-mock-settings-mtls-enabled"]',
  SETTINGS_MTLS_CN: '[data-testid="api-mock-settings-mtls-cn"]',
  SETTINGS_MTLS_GENERATE: '[data-testid="api-mock-settings-mtls-generate"]',
  SETTINGS_MTLS_ISSUED: '[data-testid="api-mock-settings-mtls-issued"]',
  SETTINGS_MTLS_DOWNLOAD_CERT: '[data-testid="api-mock-settings-mtls-download-cert"]',
  SETTINGS_MTLS_DOWNLOAD_KEY: '[data-testid="api-mock-settings-mtls-download-key"]',
  SETTINGS_MTLS_DOWNLOAD_CA: '[data-testid="api-mock-settings-mtls-download-ca"]',

  // ── Workflow Designer API Mock nodes ─────────────────────────────────────
  WF_START_CONFIG: '[data-testid="api-mock-start-config"]',
  WF_APPLY_CONFIG: '[data-testid="api-mock-apply-config"]',
  WF_RESET_CONFIG: '[data-testid="api-mock-reset-config"]',
  WF_ASSERT_CONFIG: '[data-testid="api-mock-assert-config"]',
  WF_STOP_CONFIG: '[data-testid="api-mock-stop-config"]',
  WF_SERVER: '[data-testid="api-mock-wf-server"]',
  WF_PORT_OVERRIDE: '[data-testid="api-mock-wf-port-override"]',
  WF_ISOLATE: '[data-testid="api-mock-wf-isolate"]',
  WF_PORT_VARS: '[data-testid="api-mock-wf-port-vars"]',
  WF_SAVE_PORT: '[data-testid="api-mock-wf-save-port"]',
  WF_SAVE_BASE_URL: '[data-testid="api-mock-wf-save-base-url"]',
  WF_APPLY_ISOLATE_HINT: '[data-testid="api-mock-wf-apply-isolate-hint"]',
  WF_RESET_OPTION: '[data-testid="api-mock-wf-reset-option"]',
  WF_ASSERT_MIN: '[data-testid="api-mock-wf-assert-min"]',
  WF_ASSERT_STATUS: '[data-testid="api-mock-wf-assert-status"]',
  WF_ASSERT_BODY: '[data-testid="api-mock-wf-assert-body"]',
  WF_ASSERT_HEADER: '[data-testid="api-mock-wf-assert-header"]',
  WF_ASSERT_HEADER_VALUE: '[data-testid="api-mock-wf-assert-header-value"]',
  WF_ASSERT_RECENCY: '[data-testid="api-mock-wf-assert-recency"]',
  CANVAS_START: '[data-testid="api-mock-canvas-apiMockStart"]',
  CANVAS_APPLY: '[data-testid="api-mock-canvas-apiMockApply"]',
  CANVAS_RESET: '[data-testid="api-mock-canvas-apiMockResetState"]',
  CANVAS_ASSERT: '[data-testid="api-mock-canvas-apiMockAssertCalls"]',
  CANVAS_STOP: '[data-testid="api-mock-canvas-apiMockStop"]',

  // ── Undo toast ───────────────────────────────────────────────────────────
  UNDO_TOAST: '[data-testid="api-mock-undo-toast"]',
  UNDO_RESTORE: '[data-testid="api-mock-undo-restore"]',
  UNDO_DISMISS: '[data-testid="api-mock-undo-dismiss"]',

  // ── App navigation helpers ───────────────────────────────────────────────
  APP_SUBNAV: '[data-testid="nav-tab-api-mock-studio"]',
} as const;

/** @deprecated Prefer `API_MOCK` — kept as a short alias for lesson narration. */
export const AMS = API_MOCK;
