/**
 * API Mock Studio selectors — single source for demos / E2E / lessons.
 * Values are CSS selectors usable with document.querySelector / Playwright.
 */
export const API_MOCK_STUDIO = {
  // ── Page shell ───────────────────────────────────────────────────────────
  STUDIO: '[data-testid="api-mock-studio"]',
  LIVE_REGION: '[data-testid="api-mock-live-region"]',
  EMPTY: '[data-testid="api-mock-empty"]',
  CREATE_FIRST: '[data-testid="api-mock-create-first"]',
  TITLEBAR: '[data-testid="api-mock-titlebar"]',
  OPEN_LIBRARY: '[data-testid="api-mock-open-library"]',
  LIBRARY_LANDING: '[data-testid="api-mock-library-landing"]',
  LIBRARY: '[data-testid="api-mock-library"]',
  LIBRARY_SEARCH: '[data-testid="api-mock-library-search"]',
  LIBRARY_CREATE: '[data-testid="api-mock-library-create"]',
  LIBRARY_MODAL: '[data-testid="api-mock-library-modal"]',
  LIBRARY_CLOSE: '[data-testid="api-mock-library-close"]',
  LIBRARY_LIST: '[data-testid="api-mock-library-list"]',
  LIBRARY_EMPTY: '[data-testid="api-mock-library-empty"]',
  LIBRARY_COUNT: '[data-testid="api-mock-library-count"]',
  /** Number of saved servers with no open tab; absent when every server is open. */
  PARKED_COUNT: '[data-testid="api-mock-parked-count"]',
  LIBRARY_ROW: '[data-testid="api-mock-library-list"] > li',
  libraryRow: (id: string) => `[data-testid="api-mock-library-row-${id}"]`,
  libraryOpen: (id: string) => `[data-testid="api-mock-library-open-${id}"]`,
  libraryDelete: (id: string) => `[data-testid="api-mock-library-delete-${id}"]`,

  // ── Workspace nav (Studio / Runtime / Conflicts) ──────────────────────────
  WORKSPACE_NAV: '[data-testid="api-mock-workspace-nav"]',
  VIEW_STUDIO: '[data-testid="api-mock-view-studio"]',
  VIEW_RUNTIME: '[data-testid="api-mock-view-runtime"]',
  VIEW_CONFLICTS: '[data-testid="api-mock-view-conflicts"]',
  IMPORT_MENU: '[data-testid="api-mock-import-menu"]',
  EXPORT: '[data-testid="api-mock-export"]',
  EXPORT_MENU: '[data-testid="api-mock-export-menu-panel"]',
  EXPORT_WORKSPACE: '[data-testid="api-mock-export-workspace"]',
  EXPORT_WORKSPACE_YAML: '[data-testid="api-mock-export-workspace-yaml"]',
  EXPORT_SERVERS: '[data-testid="api-mock-export-servers"]',
  EXPORT_ROUTES: '[data-testid="api-mock-export-routes"]',
  EXPORT_WIREMOCK: '[data-testid="api-mock-export-wiremock"]',
  EXPORT_HAR: '[data-testid="api-mock-export-har"]',
  EXPORT_GROUP_WORKSPACE: '[data-testid="api-mock-export-group-workspace"]',
  EXPORT_GROUP_SERVER: '[data-testid="api-mock-export-group-server"]',
  EXPORT_GROUP_INTEROP: '[data-testid="api-mock-export-group-interop"]',
  EXPORT_CONFIRM: '[data-testid="api-mock-export-confirm"]',
  EXPORT_REDACTION: '[data-testid="api-mock-export-redaction"]',
  EXPORT_TLS_KEY: '[data-testid="api-mock-export-tls-key"]',
  EXPORT_SECRET: '[data-testid="api-mock-export-secret"]',
  EXPORT_PREVIEW: '[data-testid="api-mock-export-preview"]',
  EXPORT_LOSS: '[data-testid="api-mock-export-loss"]',
  EXPORT_HAR_COUNT: '[data-testid="api-mock-export-har-count"]',
  EXPORT_MAPPING_COUNT: '[data-testid="api-mock-export-mapping-count"]',
  EXPORT_CLI: '[data-testid="api-mock-export-cli"]',
  EXPORT_CLOSE: '[data-testid="api-mock-export-close"]',
  EXPORT_COPY: '[data-testid="api-mock-export-copy"]',
  EXPORT_FILENAME: '[data-testid="api-mock-export-filename"]',
  IMPORT_LAST_EXPORT: '[data-testid="api-mock-import-last-export"]',
  CLI_SIMULATE: '[data-testid="api-mock-cli-simulate"]',
  CLI_SIMULATE_COPY: '[data-testid="api-mock-cli-simulate-copy"]',
  CLI_VERIFY: '[data-testid="api-mock-cli-verify"]',
  CLI_VERIFY_COPY: '[data-testid="api-mock-cli-verify-copy"]',
  EXPORT_CLI_VERIFY: '[data-testid="api-mock-export-cli-verify"]',
  COPIED_ROUTE: '[data-testid="api-mock-route-explorer"] button.am-route-item[data-copied="true"]',

  // ── Server tabs / bar ───────────────────────────────────────────────────
  SERVER_TABS: '[data-testid="api-mock-server-tabs"]',
  TAB_ADD: '[data-testid="api-mock-tab-add"]',
  SERVER_BAR: '[data-testid="api-mock-server-bar"]',
  ADDRESS: '[data-testid="api-mock-address"]',
  COPY_ADDRESS: '[data-testid="api-mock-copy-address"]',
  HTTP2_BADGE: '[data-testid="api-mock-http2-badge"]',
  DIRTY_BADGE: '[data-testid="api-mock-dirty-badge"]',
  STATUS_LABEL: '[data-testid="api-mock-status-label"]',
  GENERATION: '[data-testid="api-mock-generation"]',
  START: '[data-testid="api-mock-start"]',
  STOP: '[data-testid="api-mock-stop"]',
  APPLY: '[data-testid="api-mock-apply"]',
  RESTART: '[data-testid="api-mock-restart"]',
  SETTINGS: '[data-testid="api-mock-settings"]',
  OPEN_ROUTES: '[data-testid="api-mock-open-routes"]',
  SERVER_ERROR: '[data-testid="api-mock-server-error"]',
  NATIVE_WARNINGS: '[data-testid="api-mock-native-warnings"]',
  tab: (id: string) => `[data-testid="api-mock-tab-${id}"]`,
  tabClose: (id: string) => `[data-testid="api-mock-tab-close-${id}"]`,
  /** Inline rename input, mounted only while a tab is being renamed (F2 / double-click). */
  tabRename: (id: string) => `[data-testid="api-mock-tab-rename-${id}"]`,
  /** Any tab's rename input — use when the server id is not known up front. */
  TAB_RENAME_INPUT: '[data-testid="api-mock-server-tabs"] input[data-testid^="api-mock-tab-rename-"]',
  /** Active server tab button (aria-selected). */
  ACTIVE_TAB: '[data-testid="api-mock-server-tabs"] [data-testid^="api-mock-tab-"][aria-selected="true"]',
  /** Every server tab, in visual (workspace) order. */
  SERVER_TAB: '[data-testid="api-mock-server-tabs"] [role="tab"]',
  /** Tab matched by server name — each tab's `title` starts with the server name. */
  tabTitled: (name: string) => `[data-testid="api-mock-server-tabs"] [role="tab"][title^="${name}"]`,
  /** Per-tab runtime dot — one green dot per running listener. */
  TAB_STATUS_DOT: '[data-testid="api-mock-server-tabs"] [role="tab"] .am-status-dot',
  TAB_STATUS_DOT_RUNNING: '[data-testid="api-mock-server-tabs"] [role="tab"] .am-status-dot.running',

  // ── Server tab context menu (right-click) ────────────────────────────────
  TAB_CTX_MENU: '[data-testid="studio-tab-ctx-menu"]',
  TAB_CTX_RENAME: '[data-testid="studio-tab-ctx-rename"]',
  TAB_CTX_DUPLICATE: '[data-testid="studio-tab-ctx-duplicate"]',
  TAB_CTX_COPY_LABEL: '[data-testid="studio-tab-ctx-copy-label"]',
  TAB_CTX_CLOSE: '[data-testid="studio-tab-ctx-close"]',
  TAB_CTX_CLOSE_OTHERS: '[data-testid="studio-tab-ctx-close-others"]',
  TAB_CTX_CLOSE_RIGHT: '[data-testid="studio-tab-ctx-close-right"]',

  // ── Confirm dialog (shared app chrome — stop-and-close, tab limit) ────────
  CONFIRM_DIALOG: '[data-testid="confirm-dialog"]',
  CONFIRM_TITLE: '[data-testid="confirm-title"]',
  CONFIRM_ACCEPT: '[data-testid="confirm-accept"]',
  CONFIRM_CANCEL: '[data-testid="confirm-cancel"]',

  // ── Route explorer ───────────────────────────────────────────────────────
  ROUTE_EXPLORER: '[data-testid="api-mock-route-explorer"]',
  EXPLORER_SPLITTER: '[data-testid="api-mock-explorer-splitter"]',
  ADD_ROUTE: '[data-testid="api-mock-add-route"]',
  ADD_FOLDER: '[data-testid="api-mock-add-folder"]',
  ROUTE_SEARCH: '[data-testid="api-mock-route-search"]',
  ROUTE_FILTER: '[data-testid="api-mock-route-filter"]',
  ROUTE_FILTER_PANEL: '[data-testid="api-mock-route-filter-panel"]',
  FILTER_SHOW_DISABLED: '[data-testid="api-mock-filter-show-disabled"]',
  FILTER_CONFLICTS_ONLY: '[data-testid="api-mock-filter-conflicts-only"]',
  FILTER_METHOD: '[data-testid="api-mock-filter-method"]',
  CLOSE_ROUTES: '[data-testid="api-mock-close-routes"]',
  ROUTES_EMPTY: '[data-testid="api-mock-routes-empty"]',
  ROUTES_NO_MATCH: '[data-testid="api-mock-routes-no-match"]',
  /** Explorer rule rows only — never filter/search/add (`api-mock-route-filter` etc.). */
  ROUTE_ROW: '[data-testid="api-mock-route-explorer"] button.am-route-item[role="treeitem"]',
  /** First rule row — same as ROUTE_ROW; querySelector returns the first. */
  FIRST_ROUTE: '[data-testid="api-mock-route-explorer"] button.am-route-item[role="treeitem"]',
  ANALYZE: '[data-testid="api-mock-analyze"]',
  route: (id: string) => `[data-testid="api-mock-route-${id}"]`,
  /** Explorer row by rule name — route ids are minted on gallery import. */
  routeNamed: (name: string) => `[data-testid="api-mock-route-explorer"] button.am-route-item[data-route-name="${name}"]`,
  /** Total rule count badge in the explorer head. */
  RULES_COUNT: '[data-testid="api-mock-rules-count"]',
  /** Conflict count badge — mounted only after Analyze finds overlaps. */
  CONFLICTS_COUNT: '[data-testid="api-mock-conflicts-count"]',
  /** Per-row trash affordance (opens the delete confirm). */
  routeDelete: (id: string) => `[data-testid="api-mock-route-delete-${id}"]`,
  /** First row's method chip / path / priority badge — row anatomy spotlights. */
  ROUTE_METHOD_CHIP: '[data-testid="api-mock-route-explorer"] button.am-route-item .am-method',
  ROUTE_PATH: '[data-testid="api-mock-route-explorer"] button.am-route-item .am-route-path',
  ROUTE_PRIORITY_BADGE: '[data-testid="api-mock-route-explorer"] button.am-route-item .am-badge',
  /** Rows the analyzer flagged as overlapping. */
  CONFLICT_ROUTE_ROW: '[data-testid="api-mock-route-explorer"] button.am-route-item.conflict[role="treeitem"]',

  // ── Route folders ────────────────────────────────────────────────────────
  /** Folder block (header + children). Class-based: the testid prefix also
   *  matches the folder rename / add / delete controls. */
  FOLDER_BLOCK: '[data-testid="api-mock-route-explorer"] .am-tree-folder-block',
  folder: (id: string) => `[data-testid="api-mock-folder-${id}"]`,
  /** Folder block by name — folder ids are minted at runtime. */
  folderNamed: (name: string) => `[data-testid="api-mock-route-explorer"] .am-tree-folder-block[data-folder-name="${name}"]`,
  /** Expand / collapse header (double-click renames). */
  folderToggle: (id: string) => `[data-testid="api-mock-folder-toggle-${id}"]`,
  FOLDER_TOGGLE: '[data-testid="api-mock-route-explorer"] button.am-tree-folder',
  FOLDER_NAME: '[data-testid="api-mock-route-explorer"] .am-folder-name',
  /** Inline rename input, mounted only while a folder is being renamed. */
  folderRenameInput: (id: string) => `[data-testid="api-mock-folder-rename-input-${id}"]`,
  FOLDER_RENAME_INPUT: '[data-testid="api-mock-route-explorer"] input.am-folder-rename',
  folderAddRoute: (id: string) => `[data-testid="api-mock-folder-add-route-${id}"]`,
  folderDelete: (id: string) => `[data-testid="api-mock-folder-delete-${id}"]`,
  folderEmpty: (id: string) => `[data-testid="api-mock-folder-empty-${id}"]`,
  /** Drop zone for unfiled rules — rendered only when at least one folder exists. */
  UNGROUPED_ZONE: '[data-testid="api-mock-ungrouped-zone"]',
  UNGROUPED_LABEL: '[data-testid="api-mock-ungrouped-label"]',

  // ── Route editor ─────────────────────────────────────────────────────────
  NO_ROUTE: '[data-testid="api-mock-no-route"]',
  NO_ROUTE_CREATE: '[data-testid="api-mock-no-route-create"]',
  ROUTE_EDITOR: '[data-testid="api-mock-route-editor"]',
  ROUTE_TITLE: '[data-testid="api-mock-route-title"]',
  ROUTE_NAME: '[data-testid="api-mock-route-name"]',
  ROUTE_ENABLED: '[data-testid="api-mock-route-enabled"]',
  METHOD_SELECT: '[data-testid="api-mock-method-select"]',
  PATH_INPUT: '[data-testid="api-mock-path-input"]',
  PATH_KIND: '[data-testid="api-mock-path-kind"]',
  PATH_TOOLBOX: '[data-testid="api-mock-path-toolbox"]',
  PRIORITY_INPUT: '[data-testid="api-mock-priority-input"]',
  ADD_CONDITION: '[data-testid="api-mock-add-condition"]',
  ADD_GROUP: '[data-testid="api-mock-add-group"]',
  CONDITIONS_EMPTY: '[data-testid="api-mock-conditions-empty"]',
  /** First Match condition row (excludes nested control testids). */
  FIRST_CONDITION: '[data-testid="api-mock-route-editor"] .am-matcher-row[data-testid^="api-mock-condition-"]',
  /** Last Match condition row after Add conditions. */
  LAST_CONDITION: '[data-testid="api-mock-route-editor"] .am-matcher-group .am-matcher-leaf:last-of-type .am-matcher-row',
  /** Every Match condition row, in render order — ids are minted per row. */
  CONDITION_ROWS: '[data-testid="api-mock-route-editor"] .am-matcher-row[data-testid^="api-mock-condition-"]',
  conditionRow: (predId: string) => `[data-testid="api-mock-condition-${predId}"]`,
  /** Source picker — Query / Header / Cookie / Security / Body / Path parameter / Transport. */
  conditionSource: (predId: string) => `[data-testid="api-mock-condition-source-${predId}"]`,
  /** Key being read: a free-text name, or the facet dropdown when the source is Security. */
  conditionSelector: (predId: string) => `[data-testid="api-mock-condition-selector-${predId}"]`,
  conditionOperator: (predId: string) => `[data-testid="api-mock-condition-operator-${predId}"]`,
  /** Expected value — disabled for the Present / Absent operators. */
  conditionValue: (predId: string) => `[data-testid="api-mock-condition-value-${predId}"]`,
  /**
   * First box of a two-part matcher: the JSONPath / XPath expression, or the field
   * name for form and multipart operators. The second box is `conditionValue`.
   */
  conditionExpr: (predId: string) => `[data-testid="api-mock-condition-expr-${predId}"]`,
  /** Body textarea for JSON subset / strict and the JSON / XML Schema operators. */
  conditionSchema: (predId: string) => `[data-testid="api-mock-condition-schema-${predId}"]`,
  conditionValueExpand: (predId: string) => `[data-testid="api-mock-condition-value-${predId}-expand"]`,
  conditionSchemaExpand: (predId: string) => `[data-testid="api-mock-condition-schema-${predId}-expand"]`,
  TEXT_EXPAND_MODAL: '[data-testid="api-mock-text-expand-modal"]',
  TEXT_EXPAND_EDITOR: '[data-testid="api-mock-text-expand-editor"]',
  TEXT_EXPAND_SEARCH: '[data-testid="api-mock-text-expand-search"]',
  TEXT_EXPAND_COUNT: '[data-testid="api-mock-text-expand-count"]',
  TEXT_EXPAND_PREV: '[data-testid="api-mock-text-expand-prev"]',
  TEXT_EXPAND_NEXT: '[data-testid="api-mock-text-expand-next"]',
  TEXT_EXPAND_PRETTY: '[data-testid="api-mock-text-expand-pretty"]',
  TEXT_EXPAND_UNDO: '[data-testid="api-mock-text-expand-undo"]',
  TEXT_EXPAND_REDO: '[data-testid="api-mock-text-expand-redo"]',
  TEXT_EXPAND_APPLY: '[data-testid="api-mock-text-expand-apply"]',
  TEXT_EXPAND_CLOSE: '[data-testid="api-mock-text-expand-close"]',
  /** Equals / Contains radios on a JSONPath or XPath equals row. */
  conditionMatchStyle: (predId: string) => `[data-testid="api-mock-condition-matchstyle-${predId}"]`,
  conditionMatchStyleEquals: (predId: string) => `[data-testid="api-mock-condition-matchstyle-equals-${predId}"]`,
  conditionMatchStyleContains: (predId: string) => `[data-testid="api-mock-condition-matchstyle-contains-${predId}"]`,
  /** Wand beside regex / glob / JSONPath / schema conditions. */
  conditionToolbox: (predId: string) => `[data-testid="api-mock-condition-toolbox-${predId}"]`,
  conditionRemove: (predId: string) => `[data-testid="api-mock-condition-remove-${predId}"]`,
  /** Boolean group shell — All of / Any of / None of. */
  group: (groupId: string) => `[data-testid="api-mock-group-${groupId}"]`,
  groupCombinator: (groupId: string) => `[data-testid="api-mock-group-combinator-${groupId}"]`,
  /** Live leaf tally in a group header — grows as conditions are added. */
  groupCount: (groupId: string) => `[data-testid="api-mock-group-count-${groupId}"]`,
  groupAddCondition: (groupId: string) => `[data-testid="api-mock-group-add-condition-${groupId}"]`,
  /** Nested groups only — `[ ] Group` inside a group (the root button is `ADD_GROUP`). */
  groupAddGroup: (groupId: string) => `[data-testid="api-mock-group-add-group-${groupId}"]`,
  groupRemove: (groupId: string) => `[data-testid="api-mock-group-remove-${groupId}"]`,
  /** Nested empty-group hint — an empty group does not affect matching. */
  groupEmpty: (groupId: string) => `[data-testid="api-mock-group-empty-${groupId}"]`,
  /** Shown when a group's combinator is None of — the evaluator fails closed on unevaluated children. */
  groupFailClosed: (groupId: string) => `[data-testid="api-mock-group-failclosed-${groupId}"]`,
  /** Nested groups only — the root group is never rendered with this class. */
  NESTED_GROUPS: '[data-testid="api-mock-route-editor"] .am-matcher-group.nested',
  /** POST /users Create User rule (Users gallery). */
  CREATE_USER_ROUTE: '[data-testid="api-mock-route-explorer"] button.am-route-item:has(.am-method.post)',
  /** Route editor body tabs (id-based — no data-testid on tab buttons). */
  BTAB_MATCH: '#api-mock-btab-match',
  BTAB_RESPONSE: '#api-mock-btab-response',
  BTAB_BEHAVIOR: '#api-mock-btab-behavior',
  BTAB_EXAMPLES: '#api-mock-btab-examples',
  BTAB_DOCS: '#api-mock-btab-docs',
  /** Documentation tab — contract metadata carried into exports and filters. */
  DOCS_FOLDER: '[data-testid="api-mock-docs-folder"]',
  DOCS_SUMMARY: '[data-testid="api-mock-docs-summary"]',
  DOCS_OPERATION_ID: '[data-testid="api-mock-docs-operation-id"]',
  DOCS_TAGS: '[data-testid="api-mock-docs-tags"]',
  SIMULATE: '[data-testid="api-mock-simulate"]',
  REVIEW_CONFLICTS: '[data-testid="api-mock-review-conflicts"]',
  CONFLICT_NOTICE: '[data-testid="api-mock-conflict-notice"]',
  RESPONSE_EDITOR: '[data-testid="api-mock-response-editor"]',
  VARIANT_BODY: '[data-testid="api-mock-variant-body"]',
  VARIANT_STATUS: '[data-testid="api-mock-variant-status"]',
  /** Editable HTTP reason phrase next to the status code (legacy clients read it). */
  VARIANT_STATUS_REASON: '[data-testid="api-mock-variant-status-reason"]',
  /** Status quick chips beside the status field (200 / 201 / 400 / 404 / 500). */
  variantStatusQuick: (code: number | string) => `[data-testid="api-mock-variant-status-quick-${code}"]`,
  VARIANT_STATUS_QUICK_200: '[data-testid="api-mock-variant-status-quick-200"]',
  VARIANT_STATUS_QUICK_201: '[data-testid="api-mock-variant-status-quick-201"]',
  VARIANT_STATUS_QUICK_404: '[data-testid="api-mock-variant-status-quick-404"]',
  VARIANT_NAME: '[data-testid="api-mock-variant-name"]',
  VARIANT_CONTENT_TYPE_SELECT: '[data-testid="api-mock-variant-content-type-select"]',
  /** Byte-size counter under the body editor — proves the body actually landed. */
  BODY_SIZE: '[data-testid="api-mock-body-size"]',
  BODY_FORMAT: '[data-testid="api-mock-body-format"]',
  BODY_TEMPLATE_BADGE: '[data-testid="api-mock-body-template-badge"]',
  /** Map request helpers onto a JSON body via the Data Mapper. */
  BODY_MAP: '[data-testid="api-mock-body-map"]',
  BODY_MAPPER: '[data-testid="api-mock-body-mapper"]',
  BODY_MAPPER_AUTOMAP: '[data-testid="api-mock-body-mapper"] .dm-toolbar .dm-toolbar-btn--primary',
  BODY_MAPPER_APPLY: '[data-testid="api-mock-body-mapper"] .dm-modal-footer .dm-modal-btn--primary',
  BODY_MAPPER_CANCEL: '[data-testid="api-mock-body-mapper"] .dm-modal-btn--secondary, [data-testid="api-mock-body-mapper-cancel"]',
  /** Monaco `{{` completion widget — mounted while the suggest list is open. */
  BODY_COMPLETIONS: '.suggest-widget.visible',
  BODY_BINARY_HINT: '[data-testid="api-mock-body-binary-hint"]',
  /** Browse-helpers catalog under the response body editor. */
  TEMPLATE_HELPERS_BROWSE: '[data-testid="api-mock-template-helpers-browse"]',
  TEMPLATE_HELPERS_MODAL: '[data-testid="api-mock-template-helpers-modal"]',
  TEMPLATE_HELPERS_SEARCH: '[data-testid="api-mock-template-helpers-search"]',
  TEMPLATE_HELPERS_COUNT: '[data-testid="api-mock-template-helpers-count"]',
  TEMPLATE_HELPERS_PREV: '[data-testid="api-mock-template-helpers-prev"]',
  TEMPLATE_HELPERS_NEXT: '[data-testid="api-mock-template-helpers-next"]',
  TEMPLATE_HELPERS_ROW: '[data-testid="api-mock-template-helpers-row"]',
  TEMPLATE_HELPERS_INSERT: '[data-testid="api-mock-template-helpers-insert"]',
  TEMPLATE_HELPERS_COPY: '[data-testid="api-mock-template-helpers-copy"]',
  TEMPLATE_HELPERS_CLOSE: '[data-testid="api-mock-template-helpers-close"]',
  TEMPLATE_HELPERS_EMPTY: '[data-testid="api-mock-template-helpers-empty"]',
  TEMPLATE_HELPERS_NAV: '[data-testid="api-mock-template-helpers-nav"]',
  TEMPLATE_HELPERS_CATALOG: '[data-testid="api-mock-template-helpers-catalog"]',
  templateHelpersGroup: (category: string) => `[data-testid="api-mock-template-helpers-group-${category}"]`,
  templateHelpersCat: (category: string) => `[data-testid="api-mock-template-helpers-cat-${category}"]`,
  templateHelpersRow: (id: string) => `[data-testid="api-mock-template-helpers-row"][data-helper-id="${id}"]`,
  /** Right-hand response preview pane (status line, headers tally, rendered body). */
  RESPONSE_PREVIEW: '[data-testid="api-mock-response-preview"]',
  PREVIEW_STATUS: '[data-testid="api-mock-preview-status"]',
  PREVIEW_HEADERS: '[data-testid="api-mock-preview-headers"]',
  PREVIEW_COOKIES: '[data-testid="api-mock-preview-cookies"]',
  PREVIEW_BODY: '[data-testid="api-mock-preview-body"]',
  /** Sample request the preview uses to evaluate `{{helpers}}`. */
  PREVIEW_SAMPLE: '[data-testid="api-mock-preview-sample"]',
  /** Inline template diagnostic in the preview pane (broken helper). */
  TEMPLATE_ERROR: '[data-testid="api-mock-template-error"]',
  DIAG_TEMPLATE_ERRORS: '[data-testid="api-mock-template-error"]',
  RESPONSE_TAB_CONTENT: '[data-testid="api-mock-response-tab-content"]',
  RESPONSE_TAB_HEADERS: '[data-testid="api-mock-response-tab-headers"]',
  RESPONSE_TAB_TIMING: '[data-testid="api-mock-response-tab-timing"]',
  RESPONSE_TAB_FAULTS: '[data-testid="api-mock-response-tab-faults"]',
  RESPONSE_TAB_SELECTION: '[data-testid="api-mock-response-tab-selection"]',
  RESPONSE_TAB_OUTBOUND: '[data-testid="api-mock-response-tab-outbound"]',
  RESPONSE_MODE_BAR: '[data-testid="api-mock-response-mode-bar"]',
  RESPONSE_MODE_RULES: '[data-testid="api-mock-response-mode-rules"]',
  RESPONSE_MODE_SEQUENCE: '[data-testid="api-mock-response-mode-sequence"]',
  RESPONSE_MODE_WEIGHTED: '[data-testid="api-mock-response-mode-weighted"]',
  RESPONSE_MODE_STATE: '[data-testid="api-mock-response-mode-state"]',
  SEQUENCE_ORDER_NOTE: '[data-testid="api-mock-sequence-order-note"]',
  SEQUENCE_POSITION: '[data-testid="api-mock-sequence-position"]',
  ADD_HEADER: '[data-testid="api-mock-add-header"]',
  HEADER_LIST: '[data-testid="api-mock-header-list"]',
  HEADER_ROW: '[data-testid="api-mock-header-row"]',
  HEADER_KEY: '[data-testid="api-mock-header-key"]',
  HEADER_VALUE: '[data-testid="api-mock-header-value"]',
  HEADER_KEY_LAST: '[data-testid="api-mock-header-list"] [data-testid="api-mock-header-row"]:last-child [data-testid="api-mock-header-key"]',
  HEADER_VALUE_LAST: '[data-testid="api-mock-header-list"] [data-testid="api-mock-header-row"]:last-child [data-testid="api-mock-header-value"]',
  ADD_COOKIE: '[data-testid="api-mock-add-cookie"]',
  COOKIE_ROW: '[data-testid="api-mock-cookie-row"]',
  COOKIE_NAME: '[data-testid="api-mock-cookie-name"]',
  COOKIE_VALUE: '[data-testid="api-mock-cookie-value"]',
  COOKIE_HTTPONLY: '[data-testid="api-mock-cookie-httpOnly"]',
  ADD_VARIANT: '[data-testid="api-mock-add-variant"]',
  VARIANT_SIDEBAR: '[data-testid="api-mock-variant-sidebar"]',
  VARIANT_LIST: '[data-testid="api-mock-variant-list"]',
  VARIANT_CARD: '[data-testid="api-mock-variant-list"] [data-testid^="api-mock-variant-tab-"]',
  VARIANT_CARD_FIRST: '[data-testid="api-mock-variant-list"] [data-testid^="api-mock-variant-tab-"]:first-of-type',
  VARIANT_CARD_LAST: '[data-testid="api-mock-variant-list"] [data-testid^="api-mock-variant-tab-"]:last-of-type',
  VARIANT_DEFAULT_BADGE: '[data-testid="api-mock-variant-default-badge"]',
  SELECTION_PANEL: '[data-testid="api-mock-selection-panel"]',
  SELECTION_CONDITION: '[data-testid="api-mock-selection-condition"]',
  SELECTION_CONDITION_PATH: '[data-testid="api-mock-selection-condition-path"]',
  SELECTION_CONDITION_VALUE: '[data-testid="api-mock-selection-condition-value"]',
  SELECTION_DEFAULT: '[data-testid="api-mock-selection-default"]',
  SELECTION_DEFAULT_NOTE: '[data-testid="api-mock-selection-default-note"]',
  VARIANT_REQUIRED_STATE: '[data-testid="api-mock-variant-required-state"]',
  VARIANT_NEXT_STATE: '[data-testid="api-mock-variant-next-state"]',
  VARIANT_WEIGHT: '[data-testid="api-mock-variant-weight"]',
  COUNTER_ADD: '[data-testid="api-mock-counter-add"]',
  COUNTER_ROW: '[data-testid="api-mock-counter-row-0"]',
  COUNTER_KEY: '[data-testid="api-mock-counter-key-0"]',
  COUNTER_DELTA: '[data-testid="api-mock-counter-delta-0"]',
  TIMING_PANEL: '[data-testid="api-mock-timing-panel"]',
  VARIANT_DELAY: '[data-testid="api-mock-variant-delay"]',
  VARIANT_JITTER: '[data-testid="api-mock-variant-jitter"]',
  VARIANT_MAX_MATCHES: '[data-testid="api-mock-variant-max-matches"]',
  VARIANT_PROBABILITY: '[data-testid="api-mock-variant-probability"]',
  VARIANT_EXPIRES_AT: '[data-testid="api-mock-variant-expires-at"]',
  EXPIRES_QUICK_1H: '[data-testid="api-mock-expires-quick-1h"]',
  EXPIRES_DISPLAY: '[data-testid="api-mock-expires-display"]',
  EXPIRES_CALENDAR: '[data-testid="api-mock-expires-calendar"]',
  EXPIRES_CALENDAR_BTN: '[data-testid="api-mock-expires-calendar-btn"]',
  EXPIRES_CALENDAR_PREV: '[data-testid="api-mock-expires-cal-prev"]',
  EXPIRES_CALENDAR_NEXT: '[data-testid="api-mock-expires-cal-next"]',
  EXPIRES_CALENDAR_HOUR: '[data-testid="api-mock-expires-cal-hour"]',
  EXPIRES_CALENDAR_MINUTE: '[data-testid="api-mock-expires-cal-minute"]',
  EXPIRES_CALENDAR_TODAY: '[data-testid="api-mock-expires-cal-today"]',
  EXPIRES_CALENDAR_CLEAR: '[data-testid="api-mock-expires-cal-clear"]',
  EXPIRES_CALENDAR_APPLY: '[data-testid="api-mock-expires-cal-apply"]',
  TIMING_SPREAD: '[data-testid="api-mock-timing-spread"]',
  ELIGIBILITY_SUMMARY: '[data-testid="api-mock-eligibility-summary"]',
  FAULTS_PANEL: '[data-testid="api-mock-faults-panel"]',
  FAULT_SELECT: '[data-testid="api-mock-fault-select"]',
  fault: (id: string) => `[data-testid="api-mock-fault-${id}"]`,
  FAULT_NONE: '[data-testid="api-mock-fault-none"]',
  FAULT_TIMEOUT: '[data-testid="api-mock-fault-timeout"]',
  FAULT_RESET: '[data-testid="api-mock-fault-reset"]',
  FAULT_CLOSE: '[data-testid="api-mock-fault-close"]',
  FAULT_MALFORMED: '[data-testid="api-mock-fault-malformed"]',
  FAULT_DRIBBLE: '[data-testid="api-mock-fault-dribble"]',
  CHUNK_ADD: '[data-testid="api-mock-chunk-add"]',
  CHUNK_SCHEDULE: '[data-testid="api-mock-chunk-schedule"]',
  CHUNK_ROW: '[data-testid="api-mock-chunk-row-0"]',
  VARIANT_OUTBOUND: '[data-testid="api-mock-variant-outbound"]',
  TRANSFORM_ADD: '[data-testid="api-mock-transform-add"]',
  /** First transform row (ids are minted at add). */
  TRANSFORM_ROW: '[data-testid="api-mock-variant-outbound"] .am-transform-row',
  TRANSFORM_OP_FIRST: '[data-testid="api-mock-variant-outbound"] [data-testid^="api-mock-transform-op-"]',
  CALLBACK_ADD: '[data-testid="api-mock-callback-add"]',
  CALLBACK_URL_FIRST: '[data-testid="api-mock-variant-outbound"] [data-testid^="api-mock-callback-url-"]',
  CALLBACK_BODY_FIRST: '[data-testid="api-mock-variant-outbound"] [data-testid^="api-mock-callback-body-"]',
  CALLBACK_RETRIES_FIRST: '[data-testid="api-mock-variant-outbound"] [data-testid^="api-mock-callback-retries-"]',
  EXAMPLES_GRID: '[data-testid="api-mock-examples-grid"]',
  EXAMPLES_EMPTY: '[data-testid="api-mock-examples-empty"]',
  EXAMPLE_BODY_PRETTY: '[data-testid="api-mock-examples-grid"] [data-testid^="api-mock-example-body-pretty-"]',
  exampleBodyPretty: (id: string) => `[data-testid="api-mock-example-body-pretty-${id}"]`,
  /** First Simulate button in the Examples grid (sample ids are minted at save). */
  EXAMPLE_SIMULATE: '[data-testid="api-mock-examples-grid"] [data-testid^="api-mock-example-simulate-"]',
  exampleSimulate: (id: string) => `[data-testid="api-mock-example-simulate-${id}"]`,
  /** First Attach on an unassociated example (ids are sample ids). */
  EXAMPLE_ATTACH: '[data-testid="api-mock-examples-grid"] [data-testid^="api-mock-example-attach-"]',
  exampleAttach: (id: string) => `[data-testid="api-mock-example-attach-${id}"]`,
  /** First Try in Requests in the Examples grid. */
  EXAMPLE_TRY_REQUESTS: '[data-testid="api-mock-examples-grid"] [data-testid^="api-mock-example-try-"]',
  exampleTry: (id: string) => `[data-testid="api-mock-example-try-${id}"]`,
  exampleRow: (id: string) => `[data-testid="api-mock-example-${id}"]`,

  // ── Live strip ───────────────────────────────────────────────────────────
  LIVE_STRIP: '[data-testid="api-mock-live-strip"]',
  LIVE_TRANSACTIONS: '[data-testid="api-mock-live-transactions"]',
  LIVE_TX_COUNT: '[data-testid="api-mock-live-transactions"] .am-count-badge',
  LIVE_CONFLICTS: '[data-testid="api-mock-live-conflicts"]',
  LIVE_VARIABLES: '[data-testid="api-mock-live-variables"]',
  LIVE_SETTINGS: '[data-testid="api-mock-live-settings"]',
  LIVE_CONSOLE: '[data-testid="api-mock-live-console"]',
  OPEN_RUNTIME: '[data-testid="api-mock-open-runtime"]',
} as const;
