/**
 * API Mock Studio selectors — single source for demos / E2E / lessons.
 * Values are CSS selectors usable with document.querySelector / Playwright.
 */
export const API_MOCK = {
  // ── Page shell ───────────────────────────────────────────────────────────
  STUDIO: '[data-testid="api-mock-studio"]',
  LIVE_REGION: '[data-testid="api-mock-live-region"]',
  EMPTY: '[data-testid="api-mock-empty"]',
  CREATE_FIRST: '[data-testid="api-mock-create-first"]',
  TITLEBAR: '[data-testid="api-mock-titlebar"]',

  // ── Workspace nav (Studio / Runtime / Conflicts) ──────────────────────────
  WORKSPACE_NAV: '[data-testid="api-mock-workspace-nav"]',
  VIEW_STUDIO: '[data-testid="api-mock-view-studio"]',
  VIEW_RUNTIME: '[data-testid="api-mock-view-runtime"]',
  VIEW_CONFLICTS: '[data-testid="api-mock-view-conflicts"]',
  IMPORT_MENU: '[data-testid="api-mock-import-menu"]',
  EXPORT: '[data-testid="api-mock-export"]',
  EXPORT_MENU: '[data-testid="api-mock-export-menu-panel"]',
  EXPORT_WORKSPACE: '[data-testid="api-mock-export-workspace"]',
  EXPORT_WORKSPACE_YAML: '[data-testid="api-mock-export-workspace-yaml"]',
  EXPORT_SERVERS: '[data-testid="api-mock-export-servers"]',
  EXPORT_ROUTES: '[data-testid="api-mock-export-routes"]',
  EXPORT_WIREMOCK: '[data-testid="api-mock-export-wiremock"]',
  EXPORT_HAR: '[data-testid="api-mock-export-har"]',

  // ── Server tabs / bar ───────────────────────────────────────────────────
  SERVER_TABS: '[data-testid="api-mock-server-tabs"]',
  TAB_ADD: '[data-testid="api-mock-tab-add"]',
  SERVER_BAR: '[data-testid="api-mock-server-bar"]',
  ADDRESS: '[data-testid="api-mock-address"]',
  COPY_ADDRESS: '[data-testid="api-mock-copy-address"]',
  HTTP2_BADGE: '[data-testid="api-mock-http2-badge"]',
  DIRTY_BADGE: '[data-testid="api-mock-dirty-badge"]',
  START: '[data-testid="api-mock-start"]',
  STOP: '[data-testid="api-mock-stop"]',
  APPLY: '[data-testid="api-mock-apply"]',
  RESTART: '[data-testid="api-mock-restart"]',
  SETTINGS: '[data-testid="api-mock-settings"]',
  OPEN_ROUTES: '[data-testid="api-mock-open-routes"]',
  SERVER_ERROR: '[data-testid="api-mock-server-error"]',
  NATIVE_WARNINGS: '[data-testid="api-mock-native-warnings"]',
  tab: (id: string) => `[data-testid="api-mock-tab-${id}"]`,
  tabClose: (id: string) => `[data-testid="api-mock-tab-close-${id}"]`,

  // ── Route explorer ───────────────────────────────────────────────────────
  ROUTE_EXPLORER: '[data-testid="api-mock-route-explorer"]',
  ADD_ROUTE: '[data-testid="api-mock-add-route"]',
  ADD_FOLDER: '[data-testid="api-mock-add-folder"]',
  ROUTE_SEARCH: '[data-testid="api-mock-route-search"]',
  ROUTE_FILTER: '[data-testid="api-mock-route-filter"]',
  ROUTE_FILTER_PANEL: '[data-testid="api-mock-route-filter-panel"]',
  FILTER_SHOW_DISABLED: '[data-testid="api-mock-filter-show-disabled"]',
  FILTER_CONFLICTS_ONLY: '[data-testid="api-mock-filter-conflicts-only"]',
  FILTER_METHOD: '[data-testid="api-mock-filter-method"]',
  CLOSE_ROUTES: '[data-testid="api-mock-close-routes"]',
  ROUTES_EMPTY: '[data-testid="api-mock-routes-empty"]',
  ROUTES_NO_MATCH: '[data-testid="api-mock-routes-no-match"]',
  ANALYZE: '[data-testid="api-mock-analyze"]',
  route: (id: string) => `[data-testid="api-mock-route-${id}"]`,

  // ── Route editor ─────────────────────────────────────────────────────────
  NO_ROUTE: '[data-testid="api-mock-no-route"]',
  NO_ROUTE_CREATE: '[data-testid="api-mock-no-route-create"]',
  ROUTE_EDITOR: '[data-testid="api-mock-route-editor"]',
  ROUTE_TITLE: '[data-testid="api-mock-route-title"]',
  ROUTE_NAME: '[data-testid="api-mock-route-name"]',
  ROUTE_ENABLED: '[data-testid="api-mock-route-enabled"]',
  METHOD_SELECT: '[data-testid="api-mock-method-select"]',
  PATH_INPUT: '[data-testid="api-mock-path-input"]',
  PATH_KIND: '[data-testid="api-mock-path-kind"]',
  PATH_TOOLBOX: '[data-testid="api-mock-path-toolbox"]',
  PRIORITY_INPUT: '[data-testid="api-mock-priority-input"]',
  SIMULATE: '[data-testid="api-mock-simulate"]',
  REVIEW_CONFLICTS: '[data-testid="api-mock-review-conflicts"]',
  CONFLICT_NOTICE: '[data-testid="api-mock-conflict-notice"]',
  RESPONSE_EDITOR: '[data-testid="api-mock-response-editor"]',
  VARIANT_BODY: '[data-testid="api-mock-variant-body"]',
  VARIANT_STATUS: '[data-testid="api-mock-variant-status"]',
  ADD_VARIANT: '[data-testid="api-mock-add-variant"]',
  FAULTS_PANEL: '[data-testid="api-mock-faults-panel"]',
  FAULT_SELECT: '[data-testid="api-mock-fault-select"]',
  VARIANT_OUTBOUND: '[data-testid="api-mock-variant-outbound"]',
  EXAMPLES_GRID: '[data-testid="api-mock-examples-grid"]',
  EXAMPLES_EMPTY: '[data-testid="api-mock-examples-empty"]',

  // ── Live strip ───────────────────────────────────────────────────────────
  LIVE_STRIP: '[data-testid="api-mock-live-strip"]',
  LIVE_TRANSACTIONS: '[data-testid="api-mock-live-transactions"]',
  LIVE_CONFLICTS: '[data-testid="api-mock-live-conflicts"]',
  LIVE_VARIABLES: '[data-testid="api-mock-live-variables"]',
  LIVE_SETTINGS: '[data-testid="api-mock-live-settings"]',
  LIVE_CONSOLE: '[data-testid="api-mock-live-console"]',
  OPEN_RUNTIME: '[data-testid="api-mock-open-runtime"]',

  // ── Runtime page / dock ──────────────────────────────────────────────────
  RUNTIME_PAGE: '[data-testid="api-mock-runtime-page"]',
  DOCK: '[data-testid="api-mock-dock"]',
  dockTab: (id: string) => `[data-testid="api-mock-dock-tab-${id}"]`,
  DOCK_TAB_TRANSACTIONS: '[data-testid="api-mock-dock-tab-transactions"]',
  DOCK_TAB_STATE: '[data-testid="api-mock-dock-tab-state"]',
  DOCK_TAB_VARIABLES: '[data-testid="api-mock-dock-tab-variables"]',
  DOCK_TAB_SETTINGS: '[data-testid="api-mock-dock-tab-settings"]',
  DOCK_TAB_DIAGNOSTICS: '[data-testid="api-mock-dock-tab-diagnostics"]',
  DOCK_TAB_CONSOLE: '[data-testid="api-mock-dock-tab-console"]',
  JOURNAL_TOOLBAR: '[data-testid="api-mock-journal-toolbar"]',
  JOURNAL_FILTER: '[data-testid="api-mock-journal-filter"]',
  JOURNAL_EXPORT: '[data-testid="api-mock-journal-export"]',
  JOURNAL_CLEAR: '[data-testid="api-mock-journal-clear"]',
  RUNTIME_GUIDE: '[data-testid="api-mock-runtime-guide"]',
  RUNTIME_SAMPLE_CURL: '[data-testid="api-mock-runtime-sample-curl"]',
  RUNTIME_COPY_CURL: '[data-testid="api-mock-runtime-copy-curl"]',
  RUNTIME_SETTINGS_PANEL: '[data-testid="api-mock-runtime-settings-panel"]',
  RUNTIME_SETTINGS_SAVE: '[data-testid="api-mock-runtime-settings-save"]',
  RUNTIME_SETTINGS_CORS: '[data-testid="api-mock-runtime-settings-cors"]',
  RUNTIME_SETTINGS_JOURNAL: '[data-testid="api-mock-runtime-settings-journal"]',
  RUNTIME_SETTINGS_FALLBACK: '[data-testid="api-mock-runtime-settings-fallback"]',
  DIAGNOSTICS: '[data-testid="api-mock-diagnostics"]',
  tx: (id: string) => `[data-testid="api-mock-tx-${id}"]`,

  // ── Conflicts ────────────────────────────────────────────────────────────
  CONFLICTS_PAGE: '[data-testid="api-mock-conflicts-page"]',
  CONFLICTS_ANALYZE: '[data-testid="api-mock-conflicts-analyze"]',
  CONFLICT_INSPECTOR: '[data-testid="api-mock-conflict-inspector"]',
  CONFLICT_GUIDE: '[data-testid="api-mock-conflict-guide"]',
  CONFLICT_GUIDE_ANALYZE: '[data-testid="api-mock-conflict-guide-analyze"]',
  CONFLICT_SUMMARY: '[data-testid="api-mock-conflict-summary"]',
  CONFLICT_LIST: '[data-testid="api-mock-conflict-list"]',
  CONFLICT_DETAIL: '[data-testid="api-mock-conflict-detail"]',
  CONFLICT_SIMULATE: '[data-testid="api-mock-conflict-simulate"]',
  CONFLICT_ACKNOWLEDGE: '[data-testid="api-mock-conflict-acknowledge"]',
  CONFLICT_ADJUST_PRIORITY: '[data-testid="api-mock-conflict-adjust-priority"]',
  CONFLICT_APPLY: '[data-testid="api-mock-conflict-apply"]',
  conflictFilter: (kind: string) => `[data-testid="api-mock-conflict-filter-${kind}"]`,

  // ── Pattern Toolbox ──────────────────────────────────────────────────────
  PATTERN_TOOLBOX: '[data-testid="api-mock-pattern-toolbox"]',
  TOOLBOX_APPLY: '[data-testid="api-mock-toolbox-apply"]',
  TOOLBOX_CANCEL: '[data-testid="api-mock-toolbox-cancel"]',
  TOOLBOX_JSON_SAMPLE: '[data-testid="api-mock-toolbox-json-sample"]',
  TOOLBOX_JSONPATH: '[data-testid="api-mock-toolbox-jsonpath"]',
  TOOLBOX_JSON_RESOLVED: '[data-testid="api-mock-toolbox-json-resolved"]',
  TOOLBOX_REGEX: '[data-testid="api-mock-toolbox-regex"]',
  TOOLBOX_SAMPLE: '[data-testid="api-mock-toolbox-sample"]',
  TOOLBOX_XPATH: '[data-testid="api-mock-toolbox-xpath"]',
  TOOLBOX_SCHEMA: '[data-testid="api-mock-toolbox-schema"]',

  // ── Import review ────────────────────────────────────────────────────────
  IMPORT_REVIEW: '[data-testid="api-mock-import-review"]',
  IMPORT_CLOSE: '[data-testid="api-mock-import-close"]',
  IMPORT_CONFIRM: '[data-testid="api-mock-import-confirm"]',
  IMPORT_CANCEL: '[data-testid="api-mock-import-cancel"]',
  CURL_INPUT: '[data-testid="api-mock-curl-input"]',
  CURL_PARSE: '[data-testid="api-mock-curl-parse"]',
  IMPORT_PASTE: '[data-testid="api-mock-import-paste"]',
  IMPORT_PARSE: '[data-testid="api-mock-import-parse"]',
  importSource: (id: string) => `[data-testid="api-mock-import-source-${id}"]`,

  // ── Simulate ─────────────────────────────────────────────────────────────
  SIMULATE_WORKSPACE: '[data-testid="api-mock-simulate-workspace"]',
  SIMULATE_RUN: '[data-testid="api-mock-simulate-run"]',
  SIMULATE_CLOSE: '[data-testid="api-mock-simulate-close"]',
  SIMULATE_PATH: '[data-testid="api-mock-simulate-path"]',
  SIMULATE_METHOD: '[data-testid="api-mock-simulate-method"]',
  SIMULATE_RESULT: '[data-testid="api-mock-simulate-result"]',

  // ── Server settings (TLS / Proxy) ─────────────────────────────────────────
  SETTINGS_MODAL: '[data-testid="api-mock-settings-modal"]',
  SETTINGS_SAVE: '[data-testid="api-mock-settings-save"]',
  SETTINGS_CANCEL: '[data-testid="api-mock-settings-cancel"]',
  settingsTab: (id: string) => `[data-testid="api-mock-settings-tab-${id}"]`,
  SETTINGS_TLS_ENABLED: '[data-testid="api-mock-settings-tls-enabled"]',
  SETTINGS_TLS_GENERATE: '[data-testid="api-mock-settings-tls-generate"]',
  SETTINGS_PROXY_ENABLED: '[data-testid="api-mock-settings-proxy-enabled"]',
  SETTINGS_PROXY_ALLOWLIST: '[data-testid="api-mock-settings-proxy-allowlist"]',
  SETTINGS_PROXY_RECORD: '[data-testid="api-mock-settings-proxy-record"]',
  SETTINGS_MTLS_ENABLED: '[data-testid="api-mock-settings-mtls-enabled"]',
  SETTINGS_MTLS_GENERATE: '[data-testid="api-mock-settings-mtls-generate"]',

  // ── Undo toast ───────────────────────────────────────────────────────────
  UNDO_TOAST: '[data-testid="api-mock-undo-toast"]',
  UNDO_RESTORE: '[data-testid="api-mock-undo-restore"]',
  UNDO_DISMISS: '[data-testid="api-mock-undo-dismiss"]',

  // ── App navigation helpers ───────────────────────────────────────────────
  APP_SUBNAV: '[data-testid="nav-tab-api-mock-studio"]',
} as const;

/** @deprecated Prefer `API_MOCK` — kept as a short alias for lesson narration. */
export const AMS = API_MOCK;
