/** Runtime, Simulate, Pattern Toolbox, and workflow-node selectors. */
export const API_MOCK_RUNTIME = {
  // ── Runtime page / dock ──────────────────────────────────────────────────
  RUNTIME_PAGE: '[data-testid="api-mock-runtime-page"]',
  DOCK: '[data-testid="api-mock-dock"]',
  dockTab: (id: string) => `[data-testid="api-mock-dock-tab-${id}"]`,
  DOCK_TAB_TRANSACTIONS: '[data-testid="api-mock-dock-tab-transactions"]',
  DOCK_TAB_STATE: '[data-testid="api-mock-dock-tab-state"]',
  DOCK_STATE: '[data-testid="api-mock-dock-state"]',
  DOCK_STATE_LIVE: '[data-testid="api-mock-dock-state-live"]',
  DOCK_SEQ_ROW: '[data-testid="api-mock-dock-seq-row"]',
  DOCK_TAB_VARIABLES: '[data-testid="api-mock-dock-tab-variables"]',
  DOCK_VARIABLES: '[data-testid="api-mock-dock-variables"]',
  VAR_ADD: '[data-testid="api-mock-var-add"]',
  VAR_ROW: '[data-testid="api-mock-dock-variables"] tbody tr[data-testid^="api-mock-var-row-"]',
  VAR_KEY_LAST: '[data-testid="api-mock-dock-variables"] tbody tr:last-child input[data-testid^="api-mock-var-key-"]',
  VAR_VALUE_LAST: '[data-testid="api-mock-dock-variables"] tbody tr:last-child input[data-testid^="api-mock-var-value-"]',
  VAR_SENSITIVE_LAST: '[data-testid="api-mock-dock-variables"] tbody tr:last-child [data-testid^="api-mock-var-sensitive-"]',
  STATE_RESET: '[data-testid="api-mock-state-reset"]',
  DOCK_TAB_SETTINGS: '[data-testid="api-mock-dock-tab-settings"]',
  DOCK_TAB_DIAGNOSTICS: '[data-testid="api-mock-dock-tab-diagnostics"]',
  DOCK_TAB_CONSOLE: '[data-testid="api-mock-dock-tab-console"]',
  CONSOLE: '[data-testid="api-mock-dock-console"]',
  CONSOLE_EMPTY: '[data-testid="api-mock-dock-console-empty"]',
  CONSOLE_LINE: '[data-testid="api-mock-dock-console"] .am-console-line',
  CONSOLE_SEARCH: '[data-testid="api-mock-console-search"]',
  CONSOLE_MATCH_COUNT: '[data-testid="api-mock-console-match-count"]',
  CONSOLE_FILTER_EMPTY: '[data-testid="api-mock-console-filter-empty"]',
  CONSOLE_CLEAR: '[data-testid="api-mock-console-clear"]',
  consoleFilter: (id: 'all' | 'started' | 'stopped' | 'applied' | 'errors') => `[data-testid="api-mock-console-filter-${id}"]`,
  JOURNAL_TOOLBAR: '[data-testid="api-mock-journal-toolbar"]',
  JOURNAL_FILTER: '[data-testid="api-mock-journal-filter"]',
  JOURNAL_EXPORT: '[data-testid="api-mock-journal-export"]',
  JOURNAL_CLEAR: '[data-testid="api-mock-journal-clear"]',
  /** First journal transaction row (table body only — never detail/action chrome). */
  JOURNAL_FIRST_ROW: '[data-testid="api-mock-dock"] table tbody tr[data-testid^="api-mock-tx-"]',
  TX_DETAIL: '[data-testid="api-mock-tx-detail"]',
  TX_OUTCOME: '[data-testid="api-mock-tx-outcome"]',
  TX_DETAIL_DURATION: '[data-testid="api-mock-tx-detail-duration"]',
  TX_DURATION: '[data-testid="api-mock-tx-duration"]',
  TX_IO: '[data-testid="api-mock-tx-io"]',
  TX_REQUEST: '[data-testid="api-mock-tx-request"]',
  TX_RESPONSE: '[data-testid="api-mock-tx-response"]',
  TX_RESPONSE_STATUS: '[data-testid="api-mock-tx-response-status"]',
  TX_SPLITTER: '[data-testid="api-mock-tx-splitter"]',
  TX_NOTICE: '[data-testid="api-mock-tx-notice"]',
  TX_CANDIDATES: '[data-testid="api-mock-tx-candidates"]',
  TX_NEAR_MISSES: '[data-testid="api-mock-tx-near-misses"]',
  TX_ACTIONS: '[data-testid="api-mock-tx-actions"]',
  TX_CREATE_ROUTE: '[data-testid="api-mock-tx-create-route"]',
  TX_SAVE_EXAMPLE: '[data-testid="api-mock-tx-save-example"]',
  TX_OPEN_REQUESTS: '[data-testid="api-mock-tx-open-requests"]',
  TX_COPY: '[data-testid="api-mock-tx-copy"]',
  TX_OPEN_CREATED: '[data-testid="api-mock-tx-open-created"]',
  TX_VIEW_EXAMPLE: '[data-testid="api-mock-tx-view-example"]',
  RUNTIME_GUIDE: '[data-testid="api-mock-runtime-guide"]',
  RUNTIME_SAMPLE_CURL: '[data-testid="api-mock-runtime-sample-curl"]',
  RUNTIME_COPY_CURL: '[data-testid="api-mock-runtime-copy-curl"]',
  RUNTIME_SETTINGS_PANEL: '[data-testid="api-mock-runtime-settings-panel"]',
  RUNTIME_SETTINGS_SAVE: '[data-testid="api-mock-runtime-settings-save"]',
  RUNTIME_SETTINGS_DIRTY: '[data-testid="api-mock-runtime-settings-dirty"]',
  RUNTIME_SETTINGS_CORS: '[data-testid="api-mock-runtime-settings-cors"]',
  RUNTIME_SETTINGS_CORS_ORIGINS: '[data-testid="api-mock-runtime-settings-cors-origins"]',
  RUNTIME_SETTINGS_INBOUND: '[data-testid="api-mock-runtime-settings-inbound"]',
  RUNTIME_SETTINGS_CONN: '[data-testid="api-mock-runtime-settings-conn"]',
  RUNTIME_SETTINGS_DRAIN: '[data-testid="api-mock-runtime-settings-drain"]',
  RUNTIME_SETTINGS_JOURNAL: '[data-testid="api-mock-runtime-settings-journal"]',
  RUNTIME_SETTINGS_JOURNAL_MAX: '[data-testid="api-mock-runtime-settings-journal-max"]',
  RUNTIME_SETTINGS_PERSIST: '[data-testid="api-mock-runtime-settings-persist"]',
  RUNTIME_SETTINGS_FALLBACK: '[data-testid="api-mock-runtime-settings-fallback"]',
  RUNTIME_SETTINGS_REDACT_HEADERS: '[data-testid="api-mock-runtime-settings-redact-headers"]',
  RUNTIME_SETTINGS_REDACT_PATHS: '[data-testid="api-mock-runtime-settings-redact-paths"]',
  JOURNAL_FILTER_EMPTY: '[data-testid="api-mock-journal-filter-empty"]',
  /** Empty journal after Clear — Runtime page uses the guide instead. */
  JOURNAL_EMPTY: '[data-testid="api-mock-dock-transactions-empty"]',
  DIAGNOSTICS: '[data-testid="api-mock-diagnostics"]',
  DIAG_MATCH_P95: '[data-testid="api-mock-diag-match-p95"]',
  DIAG_OUTCOMES: '[data-testid="api-mock-diag-outcomes"]',
  DIAG_GENERATION: '[data-testid="api-mock-diag-generation"]',
  DIAG_MATCH_LAST: '[data-testid="api-mock-diag-match-last"]',
  DIAG_JOURNAL_SIZE: '[data-testid="api-mock-diag-journal-size"]',
  tx: (id: string) => `[data-testid="api-mock-tx-${id}"]`,

  // ── Conflicts ────────────────────────────────────────────────────────────
  CONFLICTS_PAGE: '[data-testid="api-mock-conflicts-page"]',
  CONFLICTS_ANALYZE: '[data-testid="api-mock-conflicts-analyze"]',
  CONFLICT_INSPECTOR: '[data-testid="api-mock-conflict-inspector"]',
  CONFLICT_GUIDE: '[data-testid="api-mock-conflict-guide"]',
  CONFLICT_GUIDE_ANALYZE: '[data-testid="api-mock-conflict-guide-analyze"]',
  CONFLICT_SUMMARY: '[data-testid="api-mock-conflict-summary"]',
  CONFLICT_LIST: '[data-testid="api-mock-conflict-list"]',
  /** First conflict finding row in the list. */
  FIRST_FINDING: '[data-testid="api-mock-conflict-list"] button[data-testid^="api-mock-finding-"]',
  CONFLICT_DETAIL: '[data-testid="api-mock-conflict-detail"]',
  CONFLICT_WITNESS: '[data-testid="api-mock-conflict-witness"]',
  CONFLICT_POLICY_MULTIPLE: '[data-testid="api-mock-conflict-policy-multiple"]',
  CONFLICT_POLICY_EQUAL: '[data-testid="api-mock-conflict-policy-equal"]',
  CONFLICT_SIMULATE: '[data-testid="api-mock-conflict-simulate"]',
  CONFLICT_ACKNOWLEDGE: '[data-testid="api-mock-conflict-acknowledge"]',
  CONFLICT_ACK: '[data-testid="api-mock-conflict-ack"]',
  CONFLICT_ADJUST_PRIORITY: '[data-testid="api-mock-conflict-adjust-priority"]',
  CONFLICT_PRIO_MENU: '[data-testid="api-mock-conflict-prio-menu"]',
  CONFLICT_PRIO_LEFT: '[data-testid="api-mock-conflict-prio-left"]',
  CONFLICT_PRIO_RIGHT: '[data-testid="api-mock-conflict-prio-right"]',
  CONFLICT_APPLY: '[data-testid="api-mock-conflict-apply"]',
  CONFLICT_GOTO_LEFT: '[data-testid="api-mock-conflict-goto-left"]',
  CONFLICT_GOTO_RIGHT: '[data-testid="api-mock-conflict-goto-right"]',
  CONFLICT_FINGERPRINTS: '[data-testid="api-mock-conflict-fingerprints"]',
  CONFLICT_FINGERPRINTS_SUMMARY: '[data-testid="api-mock-conflict-fingerprints-summary"]',
  CONFLICT_FINGERPRINTS_OPEN: '[data-testid="api-mock-conflict-fingerprints"][open]',
  CONFLICT_FINGERPRINT_HASHES: '[data-testid="api-mock-conflict-fingerprint-hashes"]',
  CONFLICT_FINGERPRINT_LEFT: '[data-testid="api-mock-conflict-fingerprint-left"]',
  CONFLICT_FINGERPRINT_RIGHT: '[data-testid="api-mock-conflict-fingerprint-right"]',
  CONFLICT_FINGERPRINT_RELATION: '[data-testid="api-mock-conflict-fingerprint-relation"]',
  CONFLICT_FINGERPRINT_WHY: '[data-testid="api-mock-conflict-fingerprint-why"]',
  CONFLICT_STALE: '[data-testid="api-mock-conflict-stale"]',
  CONFLICT_COMPARE: '[data-testid="api-mock-conflict-compare"]',
  CONFLICT_DIMENSIONS: '[data-testid="api-mock-conflict-dimensions"]',
  CONFLICT_DIM_ROW: '[data-testid="api-mock-conflict-dim-row"]',
  CONFLICT_DIM_UNKNOWN: '[data-testid="api-mock-conflict-dim-row"][data-result="unknown"]',
  CONFLICT_FILTER_EMPTY: '[data-testid="api-mock-conflict-filter-empty"]',
  CONFLICT_FILTERS: '[data-testid="api-mock-conflict-filters"]',
  conflictFilter: (kind: string) => `[data-testid="api-mock-conflict-filter-${kind}"]`,
  finding: (id: string) => `[data-testid="api-mock-finding-${id}"]`,
  findingByKind: (kind: string) => `[data-testid="api-mock-conflict-list"] button[data-kind="${kind}"]`,

  // ── Pattern Toolbox ──────────────────────────────────────────────────────
  PATTERN_TOOLBOX: '[data-testid="api-mock-pattern-toolbox"]',
  TOOLBOX_APPLY: '[data-testid="api-mock-toolbox-apply"]',
  TOOLBOX_CANCEL: '[data-testid="api-mock-toolbox-cancel"]',
  TOOLBOX_TAB_JSONPATH: '[data-testid="api-mock-toolbox-tab-jsonpath"]',
  TOOLBOX_TAB_CONSTRAINTS: '[data-testid="api-mock-toolbox-tab-constraints"]',
  TOOLBOX_TAB_REGEX: '[data-testid="api-mock-toolbox-tab-regex"]',
  TOOLBOX_TAB_PATH: '[data-testid="api-mock-toolbox-tab-path"]',
  TOOLBOX_TAB_XPATH: '[data-testid="api-mock-toolbox-tab-xpath"]',
  TOOLBOX_TAB_SCHEMA: '[data-testid="api-mock-toolbox-tab-schema"]',
  TOOLBOX_JSON_SAMPLE: '[data-testid="api-mock-toolbox-json-sample"]',
  /** Valid / Invalid JSON badge above the sample body editor. */
  TOOLBOX_JSON_VALID: '[data-testid="api-mock-toolbox-json-valid"]',
  TOOLBOX_JSONPATH: '[data-testid="api-mock-toolbox-jsonpath"]',
  TOOLBOX_JSON_RESOLVED: '[data-testid="api-mock-toolbox-json-resolved"]',
  TOOLBOX_JSON_EXPECTED: '[data-testid="api-mock-toolbox-json-expected"]',
  TOOLBOX_JSON_RESULT: '[data-testid="api-mock-toolbox-json-result"]',
  TOOLBOX_REGEX: '[data-testid="api-mock-toolbox-regex"]',
  TOOLBOX_APPLIED_SOURCE: '[data-testid="api-mock-toolbox-applied-source"]',
  TOOLBOX_APPLIED_SELECTOR: '[data-testid="api-mock-toolbox-applied-selector"]',
  TOOLBOX_APPLIED_OPERATOR: '[data-testid="api-mock-toolbox-applied-operator"]',
  TOOLBOX_APPLIED_EXPECTED: '[data-testid="api-mock-toolbox-applied-expected"]',
  TOOLBOX_SAMPLE: '[data-testid="api-mock-toolbox-sample"]',
  /** XPath tab panel root. */
  TOOLBOX_XPATH: '[data-testid="api-mock-toolbox-xpath"]',
  /** XPath tab — sample XML the expression is tested against. */
  TOOLBOX_XPATH_SAMPLE: '[data-testid="api-mock-toolbox-xpath-sample"]',
  /** XPath tab — expand Sample XML into the full-text popup. */
  TOOLBOX_XPATH_SAMPLE_EXPAND: '[data-testid="api-mock-toolbox-xpath-sample-expand"]',
  /** XPath tab — well-formed / not-XML badge on the sample pane. */
  TOOLBOX_XPATH_VALID: '[data-testid="api-mock-toolbox-xpath-valid"]',
  /** XPath tab — the expression being composed. */
  TOOLBOX_XPATH_EXPR: '[data-testid="api-mock-toolbox-xpath-expr"]',
  /** XPath tab — what the expression selects from the sample (read-only). */
  TOOLBOX_XPATH_RESOLVED: '[data-testid="api-mock-toolbox-xpath-resolved"]',
  /** XPath tab — optional equals value; empty applies `xpath_exists`. */
  TOOLBOX_XPATH_VALUE: '[data-testid="api-mock-toolbox-xpath-value"]',
  /** XPath tab — live ✓ / × verdict for the expression against the sample. */
  TOOLBOX_XPATH_RESULT: '[data-testid="api-mock-toolbox-xpath-result"]',
  /** XPath tab presets — `Root element`, `Local name`, `Text value`. */
  toolboxXPathPreset: (name: string) => `[data-testid="api-mock-toolbox-xpath-preset-${name}"]`,
  /** Schema tab panel root. */
  TOOLBOX_SCHEMA: '[data-testid="api-mock-toolbox-schema"]',
  /** Schema tab — the schema being composed (JSON Schema, or XML element names). */
  TOOLBOX_SCHEMA_EDITOR: '[data-testid="api-mock-toolbox-schema-editor"]',
  TOOLBOX_SCHEMA_KIND_JSON: '[data-testid="api-mock-toolbox-schema-kind-json"]',
  TOOLBOX_SCHEMA_KIND_XML: '[data-testid="api-mock-toolbox-schema-kind-xml"]',
  /** Schema tab — Valid / Invalid badge for the draft in the editor. */
  TOOLBOX_SCHEMA_STATUS: '[data-testid="api-mock-toolbox-schema-status"]',
  /** Schema tab — why Apply is blocked when the draft is invalid. */
  TOOLBOX_SCHEMA_ERROR: '[data-testid="api-mock-toolbox-schema-error"]',
  /** Schema tab presets — `JSON object`, `Required id`, `XML names`. */
  toolboxSchemaPreset: (name: string) => `[data-testid="api-mock-toolbox-schema-preset-${name}"]`,
  toolboxTab: (id: string) => `[data-testid="api-mock-toolbox-tab-${id}"]`,
  /** Path tab — explicit kind select (Exact / Parameterized / Glob / Regex). */
  TOOLBOX_KIND: '[data-testid="api-mock-toolbox-kind"]',
  /** Path tab — the pattern being composed (not yet applied to the rule). */
  TOOLBOX_PATTERN: '[data-testid="api-mock-toolbox-pattern"]',
  /** Path tab — case-insensitive matching toggle. */
  TOOLBOX_CI: '[data-testid="api-mock-toolbox-ci"]',
  /** Path tab — live match verdict for the Test path, incl. captured params. */
  TOOLBOX_RESULT: '[data-testid="api-mock-toolbox-result"]',
  /** Path tab — Generalize block: one button per path segment. */
  TOOLBOX_SEGMENTS: '[data-testid="api-mock-toolbox-segments"]',
  toolboxSegment: (index: number) => `[data-testid="api-mock-toolbox-segment-${index}"]`,
  /** Path tab — the template the product suggests for the imported path. */
  TOOLBOX_SUGGESTED: '[data-testid="api-mock-toolbox-suggested"]',
  /** Path tab — captured path parameters for the current Test path. */
  TOOLBOX_EXTRACTION: '[data-testid="api-mock-toolbox-extraction"]',
  toolboxPreset: (label: string) => `[data-testid="api-mock-toolbox-preset-${label}"]`,
  /** Regex tab — pattern library search box. */
  TOOLBOX_LIBRARY_SEARCH: '[data-testid="api-mock-toolbox-library-search"]',
  toolboxLib: (name: string) => `[data-testid="api-mock-toolbox-lib-${name}"]`,
  /** Regex tab — Valid / Invalid badge for the composed expression. */
  TOOLBOX_SAFETY: '[data-testid="api-mock-toolbox-safety"]',
  /** Regex tab — Ignore case / Case sensitive flag chips. */
  TOOLBOX_FLAG_CI: '[data-testid="api-mock-toolbox-flag-ci"]',
  TOOLBOX_FLAG_CS: '[data-testid="api-mock-toolbox-flag-cs"]',
  /** Regex tab — live sample rows (ids `p0`/`f0`… after a library pick). */
  TOOLBOX_SAMPLE_ROWS: '[data-testid="api-mock-pattern-toolbox"] .am-sample-list .am-sample-row',
  toolboxSampleRow: (id: string) => `[data-testid="api-mock-toolbox-sample-row-${id}"]`,
  toolboxSampleValue: (id: string) => `[data-testid="api-mock-toolbox-sample-value-${id}"]`,
  toolboxSampleExpect: (id: string) => `[data-testid="api-mock-toolbox-sample-expect-${id}"]`,
  toolboxSampleActual: (id: string) => `[data-testid="api-mock-toolbox-sample-actual-${id}"]`,
  toolboxSampleCheck: (id: string) => `[data-testid="api-mock-toolbox-sample-check-${id}"]`,
  /** Query & headers tab — composes match conditions instead of a path pattern. */
  TOOLBOX_ADD_CONSTRAINT: '[data-testid="api-mock-toolbox-add-constraint"]',
  /** Pending constraint rows — the tab opens with one blank row (`c1`). */
  TOOLBOX_CONSTRAINT_ROWS: '[data-testid="api-mock-pattern-toolbox"] .am-constraint-row',
  toolboxConstraint: (id: string) => `[data-testid="api-mock-toolbox-constraint-${id}"]`,
  toolboxConstraintSource: (id: string) => `[data-testid="api-mock-toolbox-constraint-source-${id}"]`,
  toolboxConstraintName: (id: string) => `[data-testid="api-mock-toolbox-constraint-name-${id}"]`,
  toolboxConstraintOperator: (id: string) => `[data-testid="api-mock-toolbox-constraint-operator-${id}"]`,
  toolboxConstraintValue: (id: string) => `[data-testid="api-mock-toolbox-constraint-value-${id}"]`,

  // ── Import review ────────────────────────────────────────────────────────
  IMPORT_REVIEW: '[data-testid="api-mock-import-review"]',
  IMPORT_CLOSE: '[data-testid="api-mock-import-close"]',
  IMPORT_CONFIRM: '[data-testid="api-mock-import-confirm"]',
  IMPORT_CANCEL: '[data-testid="api-mock-import-cancel"]',
  IMPORT_MODE_MERGE: '[data-testid="api-mock-import-mode-merge"]',
  IMPORT_MODE_REPLACE: '[data-testid="api-mock-import-mode-replace"]',
  IMPORT_MODE_COPY: '[data-testid="api-mock-import-mode-copy"]',
  IMPORT_PREVIEW: '[data-testid="api-mock-import-preview-block"]',
  IMPORT_ROUTE_LIST: '[data-testid="api-mock-import-route-list"]',
  CURL_INPUT: '[data-testid="api-mock-curl-input"]',
  CURL_PARSE: '[data-testid="api-mock-curl-parse"]',
  IMPORT_PASTE: '[data-testid="api-mock-import-paste"]',
  IMPORT_PRETTY: '[data-testid="api-mock-import-pretty"]',
  IMPORT_PARSE: '[data-testid="api-mock-import-parse"]',
  IMPORT_SOURCES: '[data-testid="api-mock-import-sources"]',
  IMPORT_FOLDER: '[data-testid="api-mock-import-folder"]',
  IMPORT_FOLDER_MENU: '[data-testid="api-mock-import-folder-menu"]',
  IMPORT_FOLDER_NEW: '[data-testid="api-mock-import-folder-new"]',
  IMPORT_NEW_FOLDER_NAME: '[data-testid="api-mock-import-new-folder-name"]',
  IMPORT_PRIORITY: '[data-testid="api-mock-import-priority"]',
  IMPORT_GENERALIZE: '[data-testid="api-mock-import-generalize"]',
  IMPORT_LOSS: '[data-testid="api-mock-import-loss"]',
  IMPORT_REPLACE_WARNING: '[data-testid="api-mock-import-replace-warning"]',
  IMPORT_PREVIEW_PATH: '[data-testid="api-mock-import-preview-path"]',
  IMPORT_CATALOG_LIST: '[data-testid="api-mock-import-catalog-list"]',
  IMPORT_CATALOG_FILTER: '[data-testid="api-mock-import-catalog-filter"]',
  IMPORT_CATALOG_SELECT_ALL: '[data-testid="api-mock-import-catalog-select-all"]',
  IMPORT_REQUESTS_LIST: '[data-testid="api-mock-import-requests-list"]',
  IMPORT_REQUESTS_FILTER: '[data-testid="api-mock-import-requests-filter"]',
  IMPORT_REQUESTS_SELECT_ALL: '[data-testid="api-mock-import-requests-select-all"]',
  importSource: (id: string) => `[data-testid="api-mock-import-source-${id}"]`,
  /** Disabled / draft explorer rows (imports land enabled:false). */
  DRAFT_ROUTE: '[data-testid="api-mock-route-explorer"] button.am-route-item.disabled[role="treeitem"]',
  /** First draft row — same as DRAFT_ROUTE (querySelector returns first). */
  FIRST_DRAFT_ROUTE: '[data-testid="api-mock-route-explorer"] button.am-route-item.disabled[role="treeitem"]',
  /** Explorer footer draft tally text. */
  ROUTES_FOOTER: '[data-testid="api-mock-routes-footer"]',
  ROUTES_ENABLED: '[data-testid="api-mock-routes-enabled"]',
  ROUTES_DRAFT: '[data-testid="api-mock-routes-draft"]',

  // ── Simulate ─────────────────────────────────────────────────────────────
  SIMULATE_WORKSPACE: '[data-testid="api-mock-simulate-workspace"]',
  SIMULATE_RUN: '[data-testid="api-mock-simulate-run"]',
  SIMULATE_RUN_ALL: '[data-testid="api-mock-simulate-run-all"]',
  SIMULATE_EXPORT: '[data-testid="api-mock-simulate-export"]',
  SIMULATE_SEED: '[data-testid="api-mock-simulate-seed"]',
  SIMULATE_CLOSE: '[data-testid="api-mock-simulate-close"]',
  SIMULATE_PATH: '[data-testid="api-mock-simulate-path"]',
  SIMULATE_METHOD: '[data-testid="api-mock-simulate-method"]',
  SIMULATE_HEADERS: '[data-testid="api-mock-simulate-headers"]',
  SIMULATE_BODY: '[data-testid="api-mock-simulate-body"]',
  SIMULATE_CERT_SUBJECT: '[data-testid="api-mock-simulate-cert-subject"]',
  SIMULATE_BODY_EXPAND: '[data-testid="api-mock-simulate-body-expand"]',
  SIMULATE_HEADERS_EXPAND: '[data-testid="api-mock-simulate-headers-expand"]',
  HEADERS_EXPAND_MODAL: '[data-testid="api-mock-headers-expand-modal"]',
  HEADERS_EXPAND_EDITOR: '[data-testid="api-mock-headers-expand-editor"]',
  HEADERS_EXPAND_TABLE: '[data-testid="api-mock-headers-expand-table"]',
  HEADERS_EXPAND_VIEW_RAW: '[data-testid="api-mock-headers-expand-view-raw"]',
  HEADERS_EXPAND_VIEW_TABLE: '[data-testid="api-mock-headers-expand-view-table"]',
  HEADERS_EXPAND_SEARCH: '[data-testid="api-mock-headers-expand-search"]',
  HEADERS_EXPAND_COUNT: '[data-testid="api-mock-headers-expand-count"]',
  HEADERS_EXPAND_PREV: '[data-testid="api-mock-headers-expand-prev"]',
  HEADERS_EXPAND_NEXT: '[data-testid="api-mock-headers-expand-next"]',
  HEADERS_EXPAND_ADD: '[data-testid="api-mock-headers-expand-add"]',
  HEADERS_EXPAND_UNDO: '[data-testid="api-mock-headers-expand-undo"]',
  HEADERS_EXPAND_REDO: '[data-testid="api-mock-headers-expand-redo"]',
  HEADERS_EXPAND_APPLY: '[data-testid="api-mock-headers-expand-apply"]',
  HEADERS_EXPAND_CLOSE: '[data-testid="api-mock-headers-expand-close"]',
  headersExpandName: (rowId: string) => `[data-testid="api-mock-headers-expand-name-${rowId}"]`,
  headersExpandValue: (rowId: string) => `[data-testid="api-mock-headers-expand-value-${rowId}"]`,
  headersExpandRemove: (rowId: string) => `[data-testid="api-mock-headers-expand-remove-${rowId}"]`,
  SIMULATE_RESULT: '[data-testid="api-mock-simulate-result"]',
  SIMULATE_SAMPLES: '[data-testid="api-mock-sim-samples"]',
  SIMULATE_SAMPLE_STATE: '[data-testid="api-mock-sim-sample-state"]',
  SIMULATE_SAMPLE_HEALTH: '[data-testid="api-mock-sim-sample-sample-health"]',
  SIMULATE_SUMMARY: '[data-testid="api-mock-simulate-summary"]',
  SIMULATE_TAB_TRACE: '[data-testid="api-mock-sim-tab-trace"]',
  SIMULATE_TAB_REQUEST: '[data-testid="api-mock-sim-tab-request"]',
  SIMULATE_TAB_RENDERED: '[data-testid="api-mock-sim-tab-rendered"]',
  SIMULATE_TAB_ASSERTIONS: '[data-testid="api-mock-sim-tab-assertions"]',
  SIMULATE_TIMELINE_FIRST: '[data-testid="api-mock-sim-timeline-1"]',
  SIMULATE_TIMELINE_DELAY: '[data-testid="api-mock-sim-timeline-5"]',
  SIMULATE_TIMELINE_FAULT: '[data-testid="api-mock-sim-timeline-6"]',
  SIMULATE_VIRTUAL_DELAY: '[data-testid="api-mock-sim-virtual-delay"]',
  SIMULATE_FAULT_BADGE: '[data-testid="api-mock-sim-fault-badge"]',
  SIMULATE_FAULT_TIMELINE: '[data-testid="api-mock-sim-fault-timeline"]',
  SIMULATE_NORMALIZED: '[data-testid="api-mock-sim-normalized"]',
  SIMULATE_RENDERED: '[data-testid="api-mock-sim-rendered"]',
  SIMULATE_RENDERED_BODY: '[data-testid="api-mock-sim-rendered-body"]',
  SIMULATE_RENDERED_FORMAT: '[data-testid="api-mock-sim-rendered-format"]',
  SIMULATE_RENDERED_STATUS: '[data-testid="api-mock-sim-rendered-status"]',
  SIMULATE_ASSERTIONS: '[data-testid="api-mock-sim-assertions"]',
  SIMULATE_SAVE_SAMPLE: '[data-testid="api-mock-simulate-save-sample"]',
  SIMULATE_SAMPLE_NAME: '[data-testid="api-mock-simulate-sample-name"]',
  SIMULATE_SAMPLE_ADHOC: '[data-testid="api-mock-sim-sample-adhoc"]',
  SIMULATE_SAMPLE_ADHOC_BTN: '[data-testid="api-mock-sim-sample-adhoc"] .am-sim-sample-btn',
  SIMULATE_MAIN: '[data-testid="api-mock-sim-main"]',
  SIMULATE_SECTION_SAVED: '[data-testid="api-mock-sim-section-saved"]',
  SIMULATE_SECTION_SCRATCH: '[data-testid="api-mock-sim-section-scratch"]',
  SIMULATE_SECTION_FROM_RULES: '[data-testid="api-mock-sim-section-from-rules"]',
  simSample: (id: string) => `[data-testid="api-mock-sim-sample-${id}"]`,
  simSampleBtn: (id: string) => `[data-testid="api-mock-sim-sample-${id}"] .am-sim-sample-btn`,
  /** First FAIL badge on a saved sample after an expectation mismatch. */
  SIMULATE_FAIL_BADGE: '[data-testid="api-mock-sim-sample-fail"]',
  SIMULATE_ASSERT_ROW_OUTCOME: '[data-testid="api-mock-sim-assert-row-outcome"]',
  SIMULATE_ASSERT_ROW_STATUS: '[data-testid="api-mock-sim-assert-row-status"]',
  SIMULATE_ASSERT_ROW_BODY: '[data-testid="api-mock-sim-assert-row-body"]',
  SIMULATE_ASSERT_STATUS: '[data-testid="api-mock-sim-assert-status"]',
  SIMULATE_ASSERT_BODY: '[data-testid="api-mock-sim-assert-body"]',
  SIMULATE_ASSERT_FAIL: '[data-testid="api-mock-sim-assert-fail"]',
  SIMULATE_EXPORT_CONFIRM: '[data-testid="api-mock-sim-export-confirm"]',
  SIMULATE_EXPORT_PREVIEW: '[data-testid="api-mock-sim-export-preview"]',
  SIMULATE_EXPORT_FILENAME: '[data-testid="api-mock-sim-export-filename"]',
  SIMULATE_VIEW_REQUEST: '[data-testid="api-mock-sim-view-request"]',
  SIMULATE_VIEW_RESULTS: '[data-testid="api-mock-sim-view-results"]',
  simTab: (id: 'trace' | 'request' | 'rendered' | 'assertions') => `[data-testid="api-mock-sim-tab-${id}"]`,
  /** Decision-trace outcome badge — MATCHED / UNMATCHED / AMBIGUOUS / FAULT. */
  SIMULATE_OUTCOME: '[data-testid="api-mock-sim-outcome"]',
  /** Winner badge on the selected candidate. */
  SIMULATE_WINNER: '[data-testid="api-mock-sim-winner"]',
  /** Specificity score list — only when two or more rules tied at the highest priority. */
  SIMULATE_SPECIFICITY: '[data-testid="api-mock-sim-specificity"]',
  simSpecificityRow: (routeId: string) => `[data-testid="api-mock-sim-specificity-${routeId}"]`,
  /** Timeline step 3 — Apply selection policy. */
  SIMULATE_TIMELINE_POLICY: '[data-testid="api-mock-sim-timeline-3"]',
  /** Every evaluated candidate row in the decision trace. */
  SIMULATE_CANDIDATES: '[data-testid="api-mock-simulate-result"] .am-candidate',
  simCandidate: (routeId: string) => `[data-testid="api-mock-sim-candidate-${routeId}"]`,
  /** Per-predicate tick rows inside the trace — method, path, then one per condition. */
  SIMULATE_PREDICATE_ROWS: '[data-testid="api-mock-simulate-result"] .am-candidate .am-predicate',
  /** Red Decision-trace rows — the matcher that rejected the candidate. */
  SIMULATE_PREDICATE_FAIL: '[data-testid="api-mock-simulate-result"] .am-candidate .am-predicate--fail',
  simPredicateRows: (routeId: string) => `[data-testid="api-mock-sim-candidate-${routeId}"] .am-predicate`,

  // ── Server settings (TLS / Proxy) ─────────────────────────────────────────
  SETTINGS_MODAL: '[data-testid="api-mock-settings-modal"]',
  SETTINGS_NAME: '[data-testid="api-mock-settings-name"]',
  SETTINGS_PORT: '[data-testid="api-mock-settings-port"]',
  /** Inline error when the typed port is already claimed by another saved mock. */
  SETTINGS_PORT_TAKEN: '[data-testid="api-mock-settings-port-taken"]',
  SETTINGS_SAVE: '[data-testid="api-mock-settings-save"]',
  SETTINGS_CANCEL: '[data-testid="api-mock-settings-cancel"]',
  settingsTab: (id: string) => `[data-testid="api-mock-settings-tab-${id}"]`,
  SETTINGS_TAB_GENERAL: '[data-testid="api-mock-settings-tab-general"]',
  SETTINGS_PANEL_GENERAL: '[data-testid="api-mock-settings-panel-general"]',
  SETTINGS_TAB_SELECTION: '[data-testid="api-mock-settings-tab-selection"]',
  SETTINGS_PANEL_SELECTION: '[data-testid="api-mock-settings-panel-selection"]',
  SETTINGS_MULTIPLE_MATCH: '[data-testid="api-mock-settings-multiple-match"]',
  SETTINGS_EQUAL_POLICY: '[data-testid="api-mock-settings-equal-priority"]',
  SETTINGS_AMBIGUITY_STATUS: '[data-testid="api-mock-settings-ambiguity-status"]',
  SETTINGS_AMBIGUITY_BODY: '[data-testid="api-mock-settings-ambiguity-body"]',
  /** Host select (CustomSelect — 127.0.0.1 / localhost / 0.0.0.0). */
  SETTINGS_HOST: '[data-testid="api-mock-settings-host"]',
  /** LAN-exposure warning, shown only while host is `0.0.0.0`. */
  SETTINGS_HOST_WARNING: '[data-testid="api-mock-settings-host-warning"]',
  SETTINGS_BASE_PATH: '[data-testid="api-mock-settings-basepath"]',
  /** Live listen-URL preview at the top of the modal — updates as fields change. */
  SETTINGS_LISTEN_URL: '[data-testid="api-mock-settings-listen-url"]',
  SETTINGS_PANEL_TLS: '[data-testid="api-mock-settings-panel-tls"]',
  SETTINGS_TAB_TLS: '[data-testid="api-mock-settings-tab-tls"]',
  SETTINGS_TLS_ENABLED: '[data-testid="api-mock-settings-tls-enabled"]',
  SETTINGS_TLS_GENERATE: '[data-testid="api-mock-settings-tls-generate"]',
  SETTINGS_TLS_CERT: '[data-testid="api-mock-settings-tls-cert"]',
  SETTINGS_TLS_KEY: '[data-testid="api-mock-settings-tls-key"]',
  SETTINGS_TAB_PROXY: '[data-testid="api-mock-settings-tab-proxy"]',
  SETTINGS_PANEL_PROXY: '[data-testid="api-mock-settings-panel-proxy"]',
  SETTINGS_PROXY_ENABLED: '[data-testid="api-mock-settings-proxy-enabled"]',
  SETTINGS_PROXY_DENY: '[data-testid="api-mock-settings-proxy-deny"]',
  SETTINGS_PROXY_ALLOWLIST: '[data-testid="api-mock-settings-proxy-allowlist"]',
  SETTINGS_PROXY_PRIVATE: '[data-testid="api-mock-settings-proxy-private"]',
  SETTINGS_PROXY_FORWARD_AUTH: '[data-testid="api-mock-settings-proxy-forward-auth"]',
  SETTINGS_PROXY_RECORD: '[data-testid="api-mock-settings-proxy-record"]',
  SETTINGS_PROXY_LOOP: '[data-testid="api-mock-settings-proxy-loop"]',
  SETTINGS_CALLBACKS: '[data-testid="api-mock-settings-callbacks"]',
  SETTINGS_CALLBACK_ALLOWLIST: '[data-testid="api-mock-settings-callback-allowlist"]',
  SETTINGS_FALLBACK_MODE: '[data-testid="api-mock-settings-fallback-mode"]',
  SETTINGS_MTLS_ENABLED: '[data-testid="api-mock-settings-mtls-enabled"]',
  SETTINGS_MTLS_CN: '[data-testid="api-mock-settings-mtls-cn"]',
  SETTINGS_MTLS_GENERATE: '[data-testid="api-mock-settings-mtls-generate"]',
  SETTINGS_MTLS_ISSUED: '[data-testid="api-mock-settings-mtls-issued"]',
  SETTINGS_MTLS_DOWNLOAD_CERT: '[data-testid="api-mock-settings-mtls-download-cert"]',
  SETTINGS_MTLS_DOWNLOAD_KEY: '[data-testid="api-mock-settings-mtls-download-key"]',
  SETTINGS_MTLS_DOWNLOAD_CA: '[data-testid="api-mock-settings-mtls-download-ca"]',

  // ── Workflow Designer API Mock nodes ─────────────────────────────────────
  WF_START_CONFIG: '[data-testid="api-mock-start-config"]',
  WF_APPLY_CONFIG: '[data-testid="api-mock-apply-config"]',
  WF_RESET_CONFIG: '[data-testid="api-mock-reset-config"]',
  WF_ASSERT_CONFIG: '[data-testid="api-mock-assert-config"]',
  WF_STOP_CONFIG: '[data-testid="api-mock-stop-config"]',
  WF_SERVER: '[data-testid="api-mock-wf-server"]',
  /** Host around the picker — `data-count` is the live Studio library size. */
  WF_SERVER_HOST: '[data-testid="api-mock-wf-server-host"]',
  WF_PORT_OVERRIDE: '[data-testid="api-mock-wf-port-override"]',
  WF_ISOLATE: '[data-testid="api-mock-wf-isolate"]',
  WF_PORT_VARS: '[data-testid="api-mock-wf-port-vars"]',
  WF_SAVE_PORT: '[data-testid="api-mock-wf-save-port"]',
  WF_SAVE_BASE_URL: '[data-testid="api-mock-wf-save-base-url"]',
  WF_APPLY_ISOLATE_HINT: '[data-testid="api-mock-wf-apply-isolate-hint"]',
  WF_RESET_OPTION: '[data-testid="api-mock-wf-reset-option"]',
  WF_ASSERT_MIN: '[data-testid="api-mock-wf-assert-min"]',
  WF_ASSERT_STATUS: '[data-testid="api-mock-wf-assert-status"]',
  WF_ASSERT_BODY: '[data-testid="api-mock-wf-assert-body"]',
  WF_ASSERT_BODY_MATCH: '[data-testid="api-mock-wf-assert-body-match"]',
  WF_ASSERT_HEADER: '[data-testid="api-mock-wf-assert-header"]',
  WF_ASSERT_HEADER_VALUE: '[data-testid="api-mock-wf-assert-header-value"]',
  WF_ASSERT_HEADERS: '[data-testid="api-mock-wf-assert-headers"]',
  WF_ASSERT_HEADER_ADD: '[data-testid="api-mock-wf-assert-header-add"]',
  WF_ASSERT_RECENCY: '[data-testid="api-mock-wf-assert-recency"]',
  CANVAS_START: '[data-testid="api-mock-canvas-apiMockStart"]',
  CANVAS_APPLY: '[data-testid="api-mock-canvas-apiMockApply"]',
  CANVAS_RESET: '[data-testid="api-mock-canvas-apiMockResetState"]',
  CANVAS_ASSERT: '[data-testid="api-mock-canvas-apiMockAssertCalls"]',
  CANVAS_STOP: '[data-testid="api-mock-canvas-apiMockStop"]',

  // ── Undo toast ───────────────────────────────────────────────────────────
  UNDO_TOAST: '[data-testid="api-mock-undo-toast"]',
  UNDO_RESTORE: '[data-testid="api-mock-undo-restore"]',
  UNDO_DISMISS: '[data-testid="api-mock-undo-dismiss"]',

  // ── App navigation helpers ───────────────────────────────────────────────
  APP_SUBNAV: '[data-testid="nav-tab-api-mock-studio"]',
} as const;
