// ─── Demo Hub ───────────────────────────────────────────────────
export const DEMO = {
  HUB_BTN:           'button[title="Demo Hub"]',
  DOMAIN_CARD:       '.demo-domain-card:not(.coming-soon)',
  LESSON_ITEM:       '.demo-lesson-item',
  START_BTN:         '.demo-start-btn',
  STEP_COUNTER:      '.demo-live-step-counter',
  STEP_TITLE:        '.demo-live-step-title',
  SPOTLIGHT_RING:    '.demo-spotlight-ring',
  MODE_BADGE:        '.demo-live-mode-badge',
  PHASE_BADGE:       '.demo-live-phase-badge',
  PHASE_SKIPPABLE:   '.demo-live-phase-badge.skippable',
  PLAY_BTN:          '.demo-live-play-btn',
  CATEGORY_TAB:      '.demo-category-tab',
  LESSON_NOTE_BTN:   '[data-testid="demo-lesson-note-btn"]',
  LESSON_NOTES_PANEL:'[data-testid="demo-lesson-notes-panel"]',
  NOTES_SAVE_BTN:    '[data-testid="demo-lesson-notes-save-btn"]',
  NOTES_CLOSE_BTN:   '[data-testid="demo-lesson-notes-close-btn"]',
  LIVE_NOTES_BTN:    '[data-testid="demo-live-notes-btn"]',
  SIDEBAR_NOTES:     '[data-testid="demo-lesson-sidebar-notes"]',
} as const;
