/** gRPC Studio — shared data-testid selectors (Phase 1D+). */
export const GRPC = {
  STUDIO_PAGE: '[data-testid="grpc-studio-page"]',
  TAB_BAR: '[data-testid="grpc-tab-bar"]',
  TAB: (tabId: string) => `[data-testid="${tabId}"]`,
  TAB_CLOSE: (tabId: string) => `[data-testid="grpc-tab-close-${tabId}"]`,
  TAB_DUPLICATE: (tabId: string) => `[data-testid="grpc-tab-duplicate-${tabId}"]`,
  ADD_TAB: '[data-testid="grpc-add-tab"]',
  TAB_PANE: (tabId: string) => `[data-testid="grpc-tab-pane-${tabId}"]`,
  TARGET_INPUT: '[data-testid="grpc-target-input"]',
  TARGET_VALIDATION: '[data-testid="grpc-target-validation"]',
  TARGET_STATUS_OK: '[data-testid="grpc-target-status-ok"]',
  TARGET_STATUS_ERROR: '[data-testid="grpc-target-status-error"]',
  TARGET_VALIDATION_STRIP: '[data-testid="grpc-target-validation-strip"]',
  TARGET_PANEL_STACK: '[data-testid="grpc-target-panel-stack"]',
  INTERPOLATION_ERROR_BANNER: '[data-testid="grpc-interpolation-error-banner"]',
  INTERPOLATION_ERROR_MESSAGE: '[data-testid="grpc-interpolation-error-message"]',
  INTERPOLATION_ERROR_TOKEN_PATH: '[data-testid="grpc-interpolation-error-token-path"]',
  INTERPOLATION_PREVIEW_STRIP: '[data-testid="grpc-interpolation-preview-strip"]',
  INTERPOLATION_PREVIEW_TEMPLATE: '[data-testid="grpc-interpolation-preview-template"]',
  INTERPOLATION_PREVIEW_RESOLVED: '[data-testid="grpc-interpolation-preview-resolved"]',
  INTERPOLATION_PREVIEW_VALUE: '[data-testid="grpc-interpolation-preview-value"]',
  ENDPOINT_PREVIEW: '[data-testid="grpc-endpoint-preview"]',
  CONNECTION_BAR: '[data-testid="grpc-connection-bar"]',
  CONNECTION_STATUS_DOT: '[data-testid="grpc-connection-status-dot"]',
  CONNECTION_TOGGLE_BTN: '[data-testid="grpc-connection-toggle-btn"]',
  CONNECTION_CHROME: '[data-testid="grpc-connection-chrome"]',
  TLS_BADGE: '[data-testid="grpc-tls-badge"]',
  AUTH_BADGE: '[data-testid="grpc-auth-badge"]',
  DEADLINE_BADGE: '[data-testid="grpc-deadline-badge"]',
  CONNECTION_SETTINGS_BTN: '[data-testid="grpc-connection-settings-btn"]',
  SETTINGS_DRAWER: '[data-testid="grpc-connection-settings-drawer"]',
  SETTINGS_NAV: '[data-testid="grpc-settings-nav"]',
  SETTINGS_NAV_ITEM: (nav: string) => `[data-testid="grpc-settings-nav-${nav}"]`,
  SETTINGS_PANEL: (nav: string) => `[data-testid="grpc-settings-panel-${nav}"]`,
  SETTINGS_CLOSE: '[data-testid="grpc-settings-close"]',
  COMPRESSION_PANEL: '[data-testid="grpc-compression-panel"]',
  COMPRESSION_ENABLED: '[data-testid="grpc-compression-enabled"]',
  COMPRESSION_ALGORITHM: '[data-testid="grpc-compression-algorithm"]',
  COMPRESSION_PREVIEW: '[data-testid="grpc-compression-preview"]',
  HEALTH_PANEL: '[data-testid="grpc-health-panel"]',
  HEALTH_SERVICE_NAME: '[data-testid="grpc-health-service-name"]',
  HEALTH_CHECK_BTN: '[data-testid="grpc-health-check-btn"]',
  HEALTH_WATCH_BTN: '[data-testid="grpc-health-watch-btn"]',
  HEALTH_RESULT: '[data-testid="grpc-health-result"]',
  HEALTH_UNAVAILABLE: '[data-testid="grpc-health-unavailable"]',
  HEALTH_PROBE_BLOCKED: '[data-testid="grpc-health-probe-blocked"]',
  K8S_PANEL: '[data-testid="grpc-k8s-panel"]',
  K8S_START_BTN: '[data-testid="grpc-k8s-start-btn"]',
  K8S_DEFERRED: '[data-testid="grpc-k8s-deferred"]',
  TRANSPORT_PANEL: '[data-testid="grpc-transport-panel"]',
  TRANSPORT_MODE: (mode: string) => `[data-testid="grpc-transport-mode-${mode}"]`,
  CALL_SETTINGS_PANEL: '[data-testid="grpc-call-settings-panel"]',
  CALL_SETTINGS_TIMEOUT: '[data-testid="grpc-call-settings-timeout"]',
  CALL_SETTINGS_PREVIEW: '[data-testid="grpc-call-settings-preview"]',
  CONNECTION_ENV_BADGE: '[data-testid="grpc-connection-env-badge"]',
  PROTO_ONEOF: (oneofName: string) => `[data-testid="grpc-proto-oneof-${oneofName}"]`,
  PROTO_ONEOF_RADIO: (oneofName: string, member: string) =>
    `[data-testid="grpc-proto-oneof-radio-${oneofName}-${member}"]`,
  PROTO_ANY_HINT: '[data-testid="grpc-proto-any-hint"]',
  TLS_PANEL: '[data-testid="grpc-tls-panel"]',
  TLS_MODAL_BODY: '[data-testid="grpc-tls-body"]',
  TLS_MODAL_SAVE: '[data-testid="grpc-tls-save"]',
  TLS_MODAL_CANCEL: '[data-testid="grpc-tls-cancel"]',
  TLS_MODAL_CLOSE: '[data-testid="grpc-tls-close"]',
  TLS_MODAL_TEST: '[data-testid="grpc-tls-test"]',
  TLS_MODAL_RESET: '[data-testid="grpc-tls-reset"]',
  TLS_MODE: (mode: string) => `[data-testid="grpc-tls-mode-${mode}"]`,
  TLS_ISSUES: '[data-testid="grpc-tls-issues"]',
  SPRING_HINT: (hintId: string) => `[data-testid="grpc-spring-hint-${hintId}"]`,
  SPRING_HINT_DISMISS: (hintId: string) => `[data-testid="grpc-spring-hint-dismiss-${hintId}"]`,
  SECRET_FIELD_STORED_HINT: (testId: string) => `[data-testid="${testId}-stored-hint"]`,
  SECRET_FIELD_CLEAR: (testId: string) => `[data-testid="${testId}-clear"]`,
  RESPONSE_TLS_HINT: '[data-testid="grpc-response-tls-hint"]',
  STREAM_RESPONSE_HINTS: '[data-testid="grpc-stream-response-hints"]',
  AUTH_PANEL: '[data-testid="grpc-auth-panel"]',
  AUTH_TYPE: '[data-testid="grpc-auth-type"]',
  AUTH_TYPE_PILLS: '[data-testid="grpc-auth-type-pills"]',
  AUTH_TYPE_PILL: (type: string) => `[data-testid="grpc-auth-type-pill-${type}"]`,
  AUTH_CONFLICTS: '[data-testid="grpc-auth-conflicts"]',
  AUTH_PREVIEW: '[data-testid="grpc-auth-preview"]',
  AUTH_ISSUES: '[data-testid="grpc-auth-issues"]',
  TAB_STATE_TARGET: '[data-testid="grpc-tab-state-target"]',
  TAB_STATE_SERVICE: '[data-testid="grpc-tab-state-service"]',
  TAB_STATE_METHOD: '[data-testid="grpc-tab-state-method"]',
  TAB_STATE_BODY: '[data-testid="grpc-tab-state-body"]',
  TAB_STATE_LIFECYCLE: '[data-testid="grpc-tab-state-lifecycle"]',
  SERVICE_EXPLORER: '[data-testid="grpc-service-explorer"]',
  REFLECT_BTN: '[data-testid="grpc-reflect-btn"]',
  EXPLORER_SEARCH: '[data-testid="grpc-explorer-search"]',
  EXPLORER_TREE: '[data-testid="grpc-explorer-tree"]',
  EXPLORER_FOOTER: '[data-testid="grpc-explorer-footer"]',
  EXPLORER_SOURCE: '[data-testid="grpc-explorer-source"]',
  EXPLORER_SERVICE_TOTAL: '[data-testid="grpc-explorer-service-total"]',
  EXPLORER_METHOD_TOTAL: '[data-testid="grpc-explorer-method-total"]',
  MANAGE_SCHEMAS_BTN: '[data-testid="grpc-manage-schemas-btn"]',
  PROTO_MANAGE_MODAL: '[data-testid="grpc-proto-manage-modal"]',
  PROTO_UPLOAD_ZONE: '[data-testid="grpc-proto-upload-zone"]',
  PROTO_FILE_LIST: '[data-testid="grpc-proto-file-list"]',
  PROTO_IMPORT_PATH_INPUT: '[data-testid="grpc-proto-import-path-input"]',
  PROTO_IMPORT_PATH_ADD: '[data-testid="grpc-proto-import-path-add"]',
  PROTO_LOAD_BTN: '[data-testid="grpc-proto-load-btn"]',
  PROTO_LOAD_ERROR: '[data-testid="grpc-proto-load-error"]',
  PROTO_CANCEL_BTN: '[data-testid="grpc-proto-cancel-btn"]',
  PROTO_TAB_PROTO_FILES: '[data-testid="grpc-proto-tab-proto-files"]',
  PROTO_TAB_PROTOSET: '[data-testid="grpc-proto-tab-protoset"]',
  PROTO_TAB_URL: '[data-testid="grpc-proto-tab-url"]',
  PROTO_TAB_BSR: '[data-testid="grpc-proto-tab-bsr"]',
  PROTO_TAB_SCHEMA_BROWSER: '[data-testid="grpc-proto-tab-schema-browser"]',
  SCHEMA_BROWSER: '[data-testid="grpc-schema-browser"]',
  SCHEMA_BROWSER_SEARCH: '[data-testid="grpc-schema-browser-search"]',
  SCHEMA_BROWSER_TREE: '[data-testid="grpc-schema-browser-tree"]',
  SCHEMA_BROWSER_DETAIL: '[data-testid="grpc-schema-browser-detail"]',
  SCHEMA_COPY_GRPCURL_BTN: '[data-testid="grpc-schema-copy-grpcurl-btn"]',
  SCHEMA_OPEN_TAB_BTN: '[data-testid="grpc-schema-open-tab-btn"]',
  SCHEMA_METHOD_SIGNATURE: '[data-testid="grpc-schema-method-signature"]',
  SCHEMA_DRIFT_BANNER: '[data-testid="grpc-schema-drift-banner"]',
  SCHEMA_DRIFT_MESSAGE: '[data-testid="grpc-schema-drift-message"]',
  SCHEMA_DRIFT_ISSUES: '[data-testid="grpc-schema-drift-issues"]',
  SCHEMA_DRIFT_REBINDS: '[data-testid="grpc-schema-drift-rebinds"]',
  SCHEMA_DRIFT_REBIND: (service: string, method: string) =>
    `[data-testid="grpc-schema-drift-rebind-${service.replaceAll('.', '-')}-${method}"]`,
  SCHEMA_DRIFT_PRUNE_BTN: '[data-testid="grpc-schema-drift-prune-btn"]',
  SCHEMA_DRIFT_DISMISS_BTN: '[data-testid="grpc-schema-drift-dismiss-btn"]',
  PROTO_URL_INPUT: '[data-testid="grpc-proto-url-input"]',
  PROTO_BSR_MODULE_INPUT: '[data-testid="grpc-proto-bsr-module-input"]',
  PROTO_BSR_VERSION_INPUT: '[data-testid="grpc-proto-bsr-version-input"]',
  PROTO_BSR_TOKEN_INPUT: '[data-testid="grpc-proto-bsr-token-input"]',
  PROTO_PROTOSET_ZONE: '[data-testid="grpc-proto-protoset-zone"]',
  CALL_PANEL: '[data-testid="grpc-call-panel"]',
  CALL_SEND_BAR: '[data-testid="grpc-call-send-bar"]',
  SEND_BTN: '[data-testid="grpc-send-btn"]',
  SEND_BLOCK_HINT: '[data-testid="grpc-call-send-block-hint"]',
  CANCEL_BTN: '[data-testid="grpc-cancel-btn"]',
  CALL_TIMEOUT_INPUT: '[data-testid="grpc-call-timeout-input"]',
  REQUEST_TAB_FORM: '[data-testid="grpc-request-tab-form"]',
  REQUEST_TAB_JSON: '[data-testid="grpc-request-tab-json"]',
  REQUEST_TAB_METADATA: '[data-testid="grpc-request-tab-metadata"]',
  REQUEST_TAB_AUTH: '[data-testid="grpc-request-tab-auth"]',
  REQUEST_JSON: '[data-testid="grpc-request-json"]',
  REQUEST_JSON_TOOLBAR: '[data-testid="grpc-request-json-toolbar"]',
  REQUEST_JSON_PRETTY_BTN: '[data-testid="grpc-request-json-pretty-btn"]',
  REQUEST_JSON_COPY_BTN: '[data-testid="grpc-request-json-copy-btn"]',
  REQUEST_JSON_ERROR: '[data-testid="grpc-request-json-error"]',
  PROTO_FORM: '[data-testid="grpc-proto-form"]',
  /** Echo lesson / unary demos — scalar `message` field on EchoRequest. */
  PROTO_FIELD_INPUT_MESSAGE: '[data-testid="grpc-proto-field-input-message"]',
  PROTO_FIELD_INPUT: (fieldName: string) => `[data-testid="grpc-proto-field-input-${fieldName}"]`,
  METADATA_EDITOR: '[data-testid="grpc-metadata-editor"]',
  METADATA_VALIDATION_ERROR: '[data-testid="grpc-metadata-validation-error"]',
  RESPONSE_PANEL_PLACEHOLDER: '[data-testid="grpc-response-panel-placeholder"]',
  RESPONSE_PANEL: '[data-testid="grpc-response-panel"]',
  RESPONSE_HEADER: '[data-testid="grpc-response-header"]',
  RESPONSE_STATUS: '[data-testid="grpc-response-status"]',
  RESPONSE_DURATION: '[data-testid="grpc-response-duration"]',
  RESPONSE_TARGET: '[data-testid="grpc-response-target"]',
  RESPONSE_COPY: '[data-testid="grpc-response-copy"]',
  RESPONSE_IDLE: '[data-testid="grpc-response-idle"]',
  RESPONSE_IN_FLIGHT: '[data-testid="grpc-response-in-flight"]',
  RESPONSE_CANCELLED: '[data-testid="grpc-response-cancelled"]',
  RESPONSE_ERROR_SUMMARY: '[data-testid="grpc-response-error-summary"]',
  RESPONSE_ERROR_PANEL: '[data-testid="grpc-response-error-panel"]',
  RESPONSE_TAB_BODY: '[data-testid="grpc-response-tab-body"]',
  RESPONSE_TAB_HEADERS: '[data-testid="grpc-response-tab-headers"]',
  RESPONSE_TAB_TRAILERS: '[data-testid="grpc-response-tab-trailers"]',
  RESPONSE_TAB_TIMING: '[data-testid="grpc-response-tab-timing"]',
  RESPONSE_BODY: '[data-testid="grpc-response-body"]',
  RESPONSE_JSON_TOOLBAR: '[data-testid="grpc-response-json-toolbar"]',
  RESPONSE_JSON_PRETTY_BTN: '[data-testid="grpc-response-json-pretty-btn"]',
  RESPONSE_JSON_COPY_BTN: '[data-testid="grpc-response-json-copy-btn"]',
  RESPONSE_HEADERS: '[data-testid="grpc-response-headers"]',
  RESPONSE_TRAILERS: '[data-testid="grpc-response-trailers"]',
  RESPONSE_TIMING: '[data-testid="grpc-response-timing"]',
  RESPONSE_TIMING_ROW: (key: string) => `[data-testid="grpc-response-timing-row-${key}"]`,
  /** Phase 2F — streaming UI */
  STREAM_PANEL: '[data-testid="grpc-stream-panel"]',
  STREAM_ERROR: '[data-testid="grpc-stream-error"]',
  STREAM_MESSAGE_LOG: '[data-testid="grpc-stream-message-log"]',
  STREAM_LOG_LIST: '[data-testid="grpc-stream-log-list"]',
  STREAM_LOG_COUNT: '[data-testid="grpc-stream-log-count"]',
  STREAM_LOG_EMPTY: '[data-testid="grpc-stream-log-empty"]',
  STREAM_STATUS_BAR: '[data-testid="grpc-stream-status-bar"]',
  STREAM_STATUS_BADGE: '[data-testid="grpc-stream-status-badge"]',
  STREAM_INBOUND_COUNT: '[data-testid="grpc-stream-inbound-count"]',
  STREAM_OUTBOUND_COUNT: '[data-testid="grpc-stream-outbound-count"]',
  STREAM_ELAPSED: '[data-testid="grpc-stream-elapsed"]',
  STREAM_CLEAR_LOG: '[data-testid="grpc-stream-clear-log"]',
  STREAM_EXPORT_LOG_BTN: '[data-testid="grpc-stream-export-log-btn"]',
  STREAM_PENDING_PANEL: '[data-testid="grpc-stream-pending-panel"]',
  STREAM_PENDING_LIST: '[data-testid="grpc-stream-pending-list"]',
  STREAM_PENDING_EMPTY: '[data-testid="grpc-stream-pending-empty"]',
  STREAM_PENDING_CHIP: '[data-testid="grpc-stream-pending-chip"]',
  STREAM_PENDING_ITEM: (index: number) => `[data-testid="grpc-stream-pending-item-${index}"]`,
  STREAM_PENDING_REMOVE: (index: number) => `[data-testid="grpc-stream-pending-remove-${index}"]`,
  STREAM_SEND_ALL_BTN: '[data-testid="grpc-stream-send-all-btn"]',
  STREAM_PENDING_END_BTN: '[data-testid="grpc-stream-pending-end-btn"]',
  STREAM_ADD_QUEUE_BTN: '[data-testid="grpc-stream-add-queue-btn"]',
  STREAM_SEND_NOW_BTN: '[data-testid="grpc-stream-send-now-btn"]',
  CALL_TYPE_SELECTOR: '[data-testid="grpc-call-type-selector"]',
  CALL_TYPE_TAB: (callType: string) => `[data-testid="grpc-call-type-tab-${callType}"]`,
  STREAM_LAYOUT_PREVIEW_HINT: '[data-testid="grpc-stream-layout-preview-hint"]',
  STREAM_PENDING_COUNT: '[data-testid="grpc-stream-pending-count"]',
  STREAM_SEND_MESSAGE_BTN: '[data-testid="grpc-stream-send-message-btn"]',
  STREAM_END_BTN: '[data-testid="grpc-stream-end-btn"]',
  STREAM_START_BTN: '[data-testid="grpc-stream-start-btn"]',
  STREAM_CANCEL_BTN: '[data-testid="grpc-stream-cancel-btn"]',
  STREAM_DIRECTION_LEGEND: '[data-testid="grpc-stream-direction-legend"]',
  TAB_CALL_TYPE_PILL: (tabId: string) => `[data-testid="grpc-tab-call-type-pill-${tabId}"]`,
  CALL_PANEL_EMPTY: '[data-testid="grpc-call-panel-empty"]',
  CALL_PANEL_PLACEHOLDER: '[data-testid="grpc-call-panel-placeholder"]',
  EXPLORER_IDLE: '[data-testid="grpc-explorer-idle"]',
  EXPLORER_LOADING: '[data-testid="grpc-explorer-loading"]',
  EXPLORER_ERROR: '[data-testid="grpc-explorer-error"]',
  METHOD_DETAIL: '[data-testid="grpc-method-detail"]',
  METHOD_DETAIL_EMPTY: '[data-testid="grpc-method-detail-empty"]',
  METHOD_DETAIL_STALE: '[data-testid="grpc-method-detail-stale"]',
  METHOD_DETAIL_SERVICE: '[data-testid="grpc-method-detail-service"]',
  METHOD_DETAIL_REQUEST_TYPE: '[data-testid="grpc-method-detail-request-type"]',
  METHOD_DETAIL_RESPONSE_TYPE: '[data-testid="grpc-method-detail-response-type"]',
  METHOD_CALL_TYPE: '[data-testid="grpc-method-call-type"]',
  METHOD_UNARY_READY: '[data-testid="grpc-method-unary-ready"]',
  SERVICE: (serviceFullName: string) => `[data-testid="grpc-service-${serviceFullName.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').toLowerCase()}"]`,
  METHOD: (serviceFullName: string, methodName: string) => `[data-testid="grpc-method-${`${serviceFullName}-${methodName}`.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').toLowerCase()}"]`,
  /** Phase 5H — collections / history */
  STUDIO_SUB_NAV: '[data-testid="grpc-studio-sub-nav"]',
  SUB_NAV_STUDIO: '[data-testid="grpc-sub-nav-studio"]',
  SUB_NAV_COLLECTIONS: '[data-testid="grpc-sub-nav-collections"]',
  SUB_NAV_HISTORY: '[data-testid="grpc-sub-nav-history"]',
  SUB_NAV_HISTORY_BADGE: '[data-testid="grpc-sub-nav-history-badge"]',
  SAVE_REQUEST_BTN: '[data-testid="grpc-save-request-btn"]',
  IMPORT_GRPCURL_BTN: '[data-testid="grpc-import-grpcurl-btn"]',
  COLLECTIONS_PANEL: '[data-testid="grpc-collections-panel"]',
  COLLECTIONS_SEARCH: '[data-testid="grpc-collections-search"]',
  COLLECTIONS_NEW_BTN: '[data-testid="grpc-collections-new-btn"]',
  COLLECTIONS_TREE: '[data-testid="grpc-collections-tree"]',
  COLLECTION_GROUP: (collectionId: string) => `[data-testid="grpc-collection-group-${collectionId}"]`,
  COLLECTION_SAVED_REQUEST: (savedId: string) => `[data-testid="grpc-collection-saved-${savedId}"]`,
  SAVED_REQUEST_DETAIL: '[data-testid="grpc-saved-request-detail"]',
  SAVED_REQUEST_OPEN_STUDIO: '[data-testid="grpc-saved-request-open-studio"]',
  SAVED_REQUEST_COPY_GRPCURL: '[data-testid="grpc-saved-request-copy-grpcurl"]',
  SAVED_REQUEST_DELETE: '[data-testid="grpc-saved-request-delete"]',
  SAVED_REQUEST_DUPLICATE: '[data-testid="grpc-saved-request-duplicate"]',
  HISTORY_PANEL: '[data-testid="grpc-history-panel"]',
  HISTORY_SEARCH: '[data-testid="grpc-history-search"]',
  HISTORY_FILTER_SERVICE: '[data-testid="grpc-history-filter-service"]',
  HISTORY_FILTER_STATUS: '[data-testid="grpc-history-filter-status"]',
  HISTORY_CLEAR_FILTERED: '[data-testid="grpc-history-clear-filtered"]',
  HISTORY_CLEAR_ALL: '[data-testid="grpc-history-clear-all"]',
  HISTORY_LIST: '[data-testid="grpc-history-list"]',
  HISTORY_ENTRY: (entryId: string) => `[data-testid="grpc-history-entry-${entryId}"]`,
  HISTORY_DETAIL: '[data-testid="grpc-history-detail"]',
  HISTORY_REPLAY_BTN: '[data-testid="grpc-history-replay-btn"]',
  HISTORY_COPY_GRPCURL: '[data-testid="grpc-history-copy-grpcurl"]',
  SAVE_REQUEST_MODAL: '[data-testid="grpc-save-request-modal"]',
  SAVE_REQUEST_NAME: '[data-testid="grpc-save-request-name"]',
  SAVE_REQUEST_COLLECTION: '[data-testid="grpc-save-request-collection"]',
  SAVE_REQUEST_NEW_COLLECTION: '[data-testid="grpc-save-request-new-collection"]',
  SAVE_REQUEST_SUBMIT: '[data-testid="grpc-save-request-submit"]',
  SAVE_REQUEST_CANCEL: '[data-testid="grpc-save-request-cancel"]',
  IMPORT_GRPCURL_MODAL: '[data-testid="grpc-import-grpcurl-modal"]',
  IMPORT_GRPCURL_TEXTAREA: '[data-testid="grpc-import-grpcurl-textarea"]',
  IMPORT_GRPCURL_PREVIEW: '[data-testid="grpc-import-grpcurl-preview"]',
  IMPORT_GRPCURL_WARNINGS: '[data-testid="grpc-import-grpcurl-warnings"]',
  IMPORT_GRPCURL_SUBMIT: '[data-testid="grpc-import-grpcurl-submit"]',
  IMPORT_GRPCURL_CANCEL: '[data-testid="grpc-import-grpcurl-cancel"]',
  /** Phase 5I — response snapshot baseline */
  RESPONSE_SNAPSHOT_PANEL: '[data-testid="grpc-response-snapshot-panel"]',
  SNAPSHOT_BADGE_MATCH: '[data-testid="grpc-snapshot-badge-match"]',
  SNAPSHOT_BADGE_DIFF: '[data-testid="grpc-snapshot-badge-diff"]',
  SNAPSHOT_BADGE_NONE: '[data-testid="grpc-snapshot-badge-none"]',
  SNAPSHOT_UPDATE_BASELINE: '[data-testid="grpc-snapshot-update-baseline"]',
  SNAPSHOT_VIEW_DIFF: '[data-testid="grpc-snapshot-view-diff"]',
  SNAPSHOT_CLEAR_BASELINE: '[data-testid="grpc-snapshot-clear-baseline"]',
  SNAPSHOT_DIFF_MODAL: '[data-testid="grpc-snapshot-diff-modal"]',
  SNAPSHOT_DIFF_CLOSE: '[data-testid="grpc-snapshot-diff-close"]',
  SUB_NAV_ADVANCED: '[data-testid="grpc-sub-nav-advanced"]',
  ADVANCED_SHELL: '[data-testid="grpc-advanced-shell"]',
  ADVANCED_NAV: '[data-testid="grpc-advanced-nav"]',
  ADVANCED_TAB: (tab: string) => `[data-testid="grpc-advanced-tab-${tab}"]`,
  LOAD_TEST_PANEL: '[data-testid="grpc-load-test-panel"]',
  LOAD_TEST_START: '[data-testid="grpc-load-test-start-btn"]',
  LOAD_TEST_STOP: '[data-testid="grpc-load-test-stop-btn"]',
  LOAD_TEST_STATUS: '[data-testid="grpc-load-test-status"]',
  LOAD_TEST_RESULTS: '[data-testid="grpc-load-test-results"]',
  LOAD_TEST_SUMMARY_METRICS: '[data-testid="grpc-load-test-summary-metrics"]',
  MOCK_SERVER_PANEL: '[data-testid="grpc-mock-server-panel"]',
  MOCK_START: '[data-testid="grpc-mock-start-btn"]',
  MOCK_STOP: '[data-testid="grpc-mock-stop-btn"]',
  MOCK_STATUS: '[data-testid="grpc-mock-status"]',
  MOCK_RULES_JSON: '[data-testid="grpc-mock-rules-json"]',
  SCHEMA_DIFF_PANEL: '[data-testid="grpc-schema-diff-panel"]',
  SCHEMA_DIFF_CAPTURE_BASELINE: '[data-testid="grpc-schema-diff-capture-baseline"]',
  SCHEMA_DIFF_COMPARE: '[data-testid="grpc-schema-diff-compare-btn"]',
  SCHEMA_DIFF_STATUS: '[data-testid="grpc-schema-diff-status"]',
  SCHEMA_DIFF_RESULTS: '[data-testid="grpc-schema-diff-results"]',
  SCHEMA_DIFF_CHANGE_LIST: '[data-testid="grpc-schema-diff-change-list"]',
} as const;
