/** gRPC Studio — shared data-testid selectors (Phase 1D+). */
export const GRPC = {
  STUDIO_PAGE: '[data-testid="grpc-studio-page"]',
  TAB_BAR: '[data-testid="grpc-tab-bar"]',
  TAB: (tabId: string) => `[data-testid="${tabId}"]`,
  TAB_CLOSE: (tabId: string) => `[data-testid="grpc-tab-close-${tabId}"]`,
  TAB_DUPLICATE: (tabId: string) => `[data-testid="grpc-tab-duplicate-${tabId}"]`,
  ADD_TAB: '[data-testid="grpc-add-tab"]',
  TAB_PANE: (tabId: string) => `[data-testid="grpc-tab-pane-${tabId}"]`,
  TARGET_INPUT: '[data-testid="grpc-target-input"]',
  TARGET_VALIDATION: '[data-testid="grpc-target-validation"]',
  TARGET_STATUS_OK: '[data-testid="grpc-target-status-ok"]',
  TARGET_STATUS_ERROR: '[data-testid="grpc-target-status-error"]',
  TARGET_VALIDATION_STRIP: '[data-testid="grpc-target-validation-strip"]',
  TARGET_PANEL_STACK: '[data-testid="grpc-target-panel-stack"]',
  INTERPOLATION_ERROR_BANNER: '[data-testid="grpc-interpolation-error-banner"]',
  INTERPOLATION_ERROR_MESSAGE: '[data-testid="grpc-interpolation-error-message"]',
  INTERPOLATION_ERROR_TOKEN_PATH: '[data-testid="grpc-interpolation-error-token-path"]',
  INTERPOLATION_PREVIEW_STRIP: '[data-testid="grpc-interpolation-preview-strip"]',
  INTERPOLATION_PREVIEW_TEMPLATE: '[data-testid="grpc-interpolation-preview-template"]',
  INTERPOLATION_PREVIEW_RESOLVED: '[data-testid="grpc-interpolation-preview-resolved"]',
  INTERPOLATION_PREVIEW_VALUE: '[data-testid="grpc-interpolation-preview-value"]',
  ENDPOINT_PREVIEW: '[data-testid="grpc-endpoint-preview"]',
  CONNECTION_BAR: '[data-testid="grpc-connection-bar"]',
  CONNECTION_STATUS_DOT: '[data-testid="grpc-connection-status-dot"]',
  CONNECTION_TOGGLE_BTN: '[data-testid="grpc-connection-toggle-btn"]',
  CONNECTION_CHROME: '[data-testid="grpc-connection-chrome"]',
  TRANSPORT_BADGE: '[data-testid="grpc-transport-badge"]',
  TLS_BADGE: '[data-testid="grpc-tls-badge"]',
  AUTH_BADGE: '[data-testid="grpc-auth-badge"]',
  DEADLINE_BADGE: '[data-testid="grpc-deadline-badge"]',
  CONNECTION_SETTINGS_BTN: '[data-testid="grpc-connection-settings-btn"]',
  SETTINGS_DRAWER: '[data-testid="grpc-connection-settings-drawer"]',
  SETTINGS_NAV: '[data-testid="grpc-settings-nav"]',
  SETTINGS_NAV_ITEM: (nav: string) => `[data-testid="grpc-settings-nav-${nav}"]`,
  SETTINGS_PANEL: (nav: string) => `[data-testid="grpc-settings-panel-${nav}"]`,
  SETTINGS_CLOSE: '[data-testid="grpc-settings-close"]',
  COMPRESSION_PANEL: '[data-testid="grpc-compression-panel"]',
  COMPRESSION_ENABLED: '[data-testid="grpc-compression-enabled"]',
  COMPRESSION_ALGORITHM: '[data-testid="grpc-compression-algorithm"]',
  COMPRESSION_PREVIEW: '[data-testid="grpc-compression-preview"]',
  HEALTH_PANEL: '[data-testid="grpc-health-panel"]',
  HEALTH_SERVICE_NAME: '[data-testid="grpc-health-service-name"]',
  HEALTH_CHECK_BTN: '[data-testid="grpc-health-check-btn"]',
  HEALTH_WATCH_BTN: '[data-testid="grpc-health-watch-btn"]',
  HEALTH_RESULT: '[data-testid="grpc-health-result"]',
  HEALTH_UNAVAILABLE: '[data-testid="grpc-health-unavailable"]',
  HEALTH_PROBE_BLOCKED: '[data-testid="grpc-health-probe-blocked"]',
  K8S_PANEL: '[data-testid="grpc-k8s-panel"]',
  K8S_START_BTN: '[data-testid="grpc-k8s-start-btn"]',
  K8S_STOP_BTN: '[data-testid="grpc-k8s-stop-btn"]',
  K8S_STATUS: '[data-testid="grpc-k8s-status"]',
  K8S_COMMAND: '[data-testid="grpc-k8s-command"]',
  K8S_LOCAL_PORT: '[data-testid="grpc-k8s-local-port"]',
  K8S_LOG_VIEW: '[data-testid="grpc-k8s-log-view"]',
  K8S_LOG_LINES: '[data-testid="grpc-k8s-log-lines"]',
  K8S_LOG_EMPTY: '[data-testid="grpc-k8s-log-empty"]',
  K8S_LOG_CLEAR_BTN: '[data-testid="grpc-k8s-log-clear-btn"]',
  K8S_LOG_AUTOSCROLL_BTN: '[data-testid="grpc-k8s-log-autoscroll-btn"]',
  TRANSPORT_PANEL: '[data-testid="grpc-transport-panel"]',
  TRANSPORT_MODE: (mode: string) => `[data-testid="grpc-transport-mode-${mode}"]`,
  TRANSPORT_MODE_REASON: (mode: string) => `[data-testid="grpc-transport-mode-reason-${mode}"]`,
  TRANSPORT_LOCKED_HINT: '[data-testid="grpc-transport-locked-hint"]',
  CALL_SETTINGS_PANEL: '[data-testid="grpc-call-settings-panel"]',
  CALL_SETTINGS_TIMEOUT: '[data-testid="grpc-call-settings-timeout"]',
  CALL_SETTINGS_PREVIEW: '[data-testid="grpc-call-settings-preview"]',
  PROTO_ONEOF: (oneofName: string) => `[data-testid="grpc-proto-oneof-${oneofName}"]`,
  PROTO_ONEOF_RADIO: (oneofName: string, member: string) =>
    `[data-testid="grpc-proto-oneof-radio-${oneofName}-${member}"]`,
  PROTO_ONEOF_RADIO_PAYMENT_METHOD_CARD:
    '[data-testid="grpc-proto-oneof-radio-payment_method-card"]',
  PROTO_ONEOF_RADIO_PAYMENT_METHOD_INVOICE:
    '[data-testid="grpc-proto-oneof-radio-payment_method-invoice"]',
  PROTO_ANY_HINT: '[data-testid="grpc-proto-any-hint"]',
  TLS_PANEL: '[data-testid="grpc-tls-panel"]',
  TLS_MODAL_BODY: '[data-testid="grpc-tls-body"]',
  TLS_MODAL_SAVE: '[data-testid="grpc-tls-save"]',
  TLS_MODAL_CANCEL: '[data-testid="grpc-tls-cancel"]',
  TLS_MODAL_CLOSE: '[data-testid="grpc-tls-close"]',
  TLS_MODAL_TEST: '[data-testid="grpc-tls-test"]',
  TLS_MODAL_RESET: '[data-testid="grpc-tls-reset"]',
  TLS_MODE: (mode: string) => `[data-testid="grpc-tls-mode-${mode}"]`,
  TLS_ISSUES: '[data-testid="grpc-tls-issues"]',
  TLS_TEST_RESULT: '[data-testid="grpc-tls-test-result"]',
  TLS_SERVER_NAME: '[data-testid="grpc-tls-server-name"]',
  TLS_SERVER_CA: '[data-testid="grpc-tls-server-ca"]',
  TLS_CLIENT_CERT: '[data-testid="grpc-tls-client-cert"]',
  TLS_CLIENT_KEY: '[data-testid="grpc-tls-client-key"]',
  /** Vault "Set" badge on a PEM field header (scoped under TLS_MODAL_BODY). */
  TLS_FIELD_SET_BADGE: '.ws-tls-field-set-badge',
  TLS_FIELD: '.ws-tls-field',
  TLS_FIELD_HEADER: '.ws-tls-field-header',
  SPRING_HINT: (hintId: string) => `[data-testid="grpc-spring-hint-${hintId}"]`,
  SPRING_HINT_DISMISS: (hintId: string) => `[data-testid="grpc-spring-hint-dismiss-${hintId}"]`,
  SECRET_FIELD_STORED_HINT: (testId: string) => `[data-testid="${testId}-stored-hint"]`,
  SECRET_FIELD_CLEAR: (testId: string) => `[data-testid="${testId}-clear"]`,
  RESPONSE_TLS_HINT: '[data-testid="grpc-response-tls-hint"]',
  STREAM_RESPONSE_HINTS: '[data-testid="grpc-stream-response-hints"]',
  AUTH_PANEL: '[data-testid="grpc-auth-panel"]',
  AUTH_TYPE: '[data-testid="grpc-auth-type-select"]',
  AUTH_TYPE_SELECT: '[data-testid="grpc-auth-type-select"]',
  AUTH_BEARER_TOKEN: '[data-testid="grpc-auth-bearer-token"]',
  AUTH_NO_AUTH_HINT: '[data-testid="grpc-auth-no-auth-hint"]',
  AUTH_PAGE_SCOPE_BANNER: '[data-testid="grpc-auth-page-scope-banner"]',
  AUTH_CONFLICTS: '[data-testid="grpc-auth-conflicts"]',
  AUTH_PREVIEW: '[data-testid="grpc-auth-preview"]',
  AUTH_ISSUES: '[data-testid="grpc-auth-issues"]',
  TAB_STATE_TARGET: '[data-testid="grpc-tab-state-target"]',
  TAB_STATE_SERVICE: '[data-testid="grpc-tab-state-service"]',
  TAB_STATE_METHOD: '[data-testid="grpc-tab-state-method"]',
  TAB_STATE_BODY: '[data-testid="grpc-tab-state-body"]',
  TAB_STATE_LIFECYCLE: '[data-testid="grpc-tab-state-lifecycle"]',
  SERVICE_EXPLORER: '[data-testid="grpc-service-explorer"]',
  REFLECT_BTN: '[data-testid="grpc-reflect-btn"]',
  EXPLORER_SEARCH: '[data-testid="grpc-explorer-search"]',
  EXPLORER_COLLAPSE_BTN: '[data-testid="grpc-explorer-collapse-btn"]',
  EXPLORER_RAIL: '[data-testid="grpc-explorer-rail"]',
  EXPLORER_TREE: '[data-testid="grpc-explorer-tree"]',
  EXPLORER_FOOTER: '[data-testid="grpc-explorer-footer"]',
  EXPLORER_SOURCE: '[data-testid="grpc-explorer-source"]',
  EXPLORER_SERVICE_TOTAL: '[data-testid="grpc-explorer-service-total"]',
  EXPLORER_METHOD_TOTAL: '[data-testid="grpc-explorer-method-total"]',
  MANAGE_SCHEMAS_BTN: '[data-testid="grpc-manage-schemas-btn"]',
  PROTO_MANAGE_MODAL: '[data-testid="grpc-proto-manage-modal"]',
  PROTO_UPLOAD_ZONE: '[data-testid="grpc-proto-upload-zone"]',
  PROTO_FILE_LIST: '[data-testid="grpc-proto-file-list"]',
  PROTO_FILE_CLEAR_ALL: '[data-testid="grpc-proto-file-clear-all"]',
  PROTO_FILE_REMOVE_AT: (index: number) => `[data-testid="grpc-proto-file-remove-${index}"]`,
  PROTO_LOAD_BTN: '[data-testid="grpc-proto-load-btn"]',
  PROTO_LOAD_ERROR: '[data-testid="grpc-proto-load-error"]',
  PROTO_CANCEL_BTN: '[data-testid="grpc-proto-cancel-btn"]',
  PROTO_TAB_PROTO_FILES: '[data-testid="grpc-proto-tab-proto-files"]',
  PROTO_TAB_PROTOSET: '[data-testid="grpc-proto-tab-protoset"]',
  PROTO_TAB_URL: '[data-testid="grpc-proto-tab-url"]',
  PROTO_TAB_BSR: '[data-testid="grpc-proto-tab-bsr"]',
  PROTO_TAB_SCHEMA_BROWSER: '[data-testid="grpc-proto-tab-schema-browser"]',
  PROTO_ROOT_MANAGER: '[data-testid="grpc-proto-root-manager"]',
  PROTO_ROOT_ADD_INPUT: '[data-testid="grpc-proto-root-add-input"]',
  PROTO_ROOT_ADD_BTN: '[data-testid="grpc-proto-root-add-btn"]',
  PROTO_ROOT_LIST: '[data-testid="grpc-proto-root-list"]',
  PROTO_SELECTED_ROOT: '[data-testid="grpc-proto-selected-root"]',
  PROTO_CANONICAL_PREVIEW: '[data-testid="grpc-proto-canonical-preview"]',
  PROTO_COLLISION_WARNINGS: '[data-testid="grpc-proto-collision-warnings"]',
  PROTO_CANONICAL_LIST: '[data-testid="grpc-proto-canonical-list"]',
  SCHEMA_BROWSER: '[data-testid="grpc-schema-browser"]',
  SCHEMA_BROWSER_SEARCH: '[data-testid="grpc-schema-browser-search"]',
  SCHEMA_BROWSER_TREE: '[data-testid="grpc-schema-browser-tree"]',
  SCHEMA_BROWSER_DETAIL: '[data-testid="grpc-schema-browser-detail"]',
  SCHEMA_TREE_NODE: (...parts: string[]) =>
    `[data-testid="grpc-schema-tree-node-${parts
      .map((part) =>
        part
          .replace(/[^a-zA-Z0-9]+/g, '-')
          .replace(/^-+|-+$/g, '')
          .toLowerCase())
      .join('--')}"]`,
  SCHEMA_COPY_GRPCURL_BTN: '[data-testid="grpc-schema-copy-grpcurl-btn"]',
  SCHEMA_OPEN_TAB_BTN: '[data-testid="grpc-schema-open-tab-btn"]',
  SCHEMA_METHOD_SIGNATURE: '[data-testid="grpc-schema-method-signature"]',
  SCHEMA_DRIFT_BANNER: '[data-testid="grpc-schema-drift-banner"]',
  SCHEMA_DRIFT_MESSAGE: '[data-testid="grpc-schema-drift-message"]',
  SCHEMA_DRIFT_ISSUES: '[data-testid="grpc-schema-drift-issues"]',
  SCHEMA_DRIFT_REBINDS: '[data-testid="grpc-schema-drift-rebinds"]',
  SCHEMA_DRIFT_REBIND: (service: string, method: string) =>
    `[data-testid="grpc-schema-drift-rebind-${service.replaceAll('.', '-')}-${method}"]`,
  SCHEMA_DRIFT_PRUNE_BTN: '[data-testid="grpc-schema-drift-prune-btn"]',
  SCHEMA_DRIFT_DISMISS_BTN: '[data-testid="grpc-schema-drift-dismiss-btn"]',
  PROTO_URL_INPUT: '[data-testid="grpc-proto-url-input"]',
  PROTO_BSR_MODULE_INPUT: '[data-testid="grpc-proto-bsr-module-input"]',
  PROTO_BSR_VERSION_INPUT: '[data-testid="grpc-proto-bsr-version-input"]',
  PROTO_BSR_TOKEN_INPUT: '[data-testid="grpc-proto-bsr-token-input"]',
  PROTO_PROTOSET_ZONE: '[data-testid="grpc-proto-protoset-zone"]',
  CALL_PANEL: '[data-testid="grpc-call-panel"]',
  REQUEST_PANE: '[data-testid="grpc-request-pane"]',
  CALL_METHOD_NAME: '[data-testid="grpc-call-method-name"]',
  CALL_SEND_BAR: '[data-testid="grpc-call-send-bar"]',
  SEND_BTN: '[data-testid="grpc-send-btn"]',
  SEND_BTN_ANY: '[data-testid="grpc-send-btn"], [data-testid="grpc-mobile-primary-action"]',
  SEND_BLOCK_HINT: '[data-testid="grpc-call-send-block-hint"]',
  CANCEL_BTN: '[data-testid="grpc-cancel-btn"]',
  CALL_TIMEOUT_INPUT: '[data-testid="grpc-call-timeout-input"]',
  REQUEST_TAB_FORM: '[data-testid="grpc-request-tab-form"]',
  REQUEST_FORM_SCROLL: '[data-testid="grpc-request-form-scroll"]',
  /** Hybrid unary composer — JSON on the Form Input tab. */
  REQUEST_JSON_COMPACT: '[data-testid="grpc-request-json-compact"]',
  /** Hybrid — Open Full Form Editor button (send bar). */
  OPEN_FULL_FORM_EDITOR_BTN: '[data-testid="grpc-open-full-form-editor-btn"]',
  /** Hybrid — Open Full Form Editor button (Form Input strip, inline). */
  OPEN_FULL_FORM_EDITOR_BTN_INLINE: '[data-testid="grpc-open-full-form-editor-btn-inline"]',
  /** Full Form Editor modal root (dialog className). */
  HYBRID_MODAL: '.grpc-hybrid-modal',
  /** Full Form Editor modal — Form View tab button. */
  HYBRID_TAB_FORM_VIEW: '[data-testid="grpc-hybrid-tab-option-a"]',
  /** Full Form Editor modal — Focus View tab button. */
  HYBRID_TAB_FOCUS_VIEW: '[data-testid="grpc-hybrid-tab-option-b"]',
  /** Full Form Editor modal — JSON View tab button. */
  HYBRID_TAB_JSON_VIEW: '[data-testid="grpc-hybrid-tab-option-c"]',
  /** Full Form Editor modal — Apply to Request button. */
  HYBRID_APPLY_BTN: '[data-testid="grpc-hybrid-apply-btn"]',
  /** Full Form Editor modal — Discard button. */
  HYBRID_DISCARD_BTN: '[data-testid="grpc-hybrid-discard-btn"]',
  /** Full Form Editor modal — close-confirm overlay. */
  HYBRID_CLOSE_CONFIRM: '[data-testid="grpc-hybrid-close-confirm"]',
  /** Full Form Editor modal — navigator panel (Focus View). */
  HYBRID_NAVIGATOR: '[data-testid="grpc-hybrid-navigator"]',
  HYBRID_NAVIGATOR_LIST: '[data-testid="grpc-hybrid-navigator-list"]',
  HYBRID_NAVIGATOR_SEARCH: '[data-testid="grpc-hybrid-navigator-search"]',
  HYBRID_NAV_ITEM_FIELD: (fieldName: string) => `[data-testid="grpc-hybrid-nav-item-field-${fieldName}"]`,
  HYBRID_NAV_ITEM_FIELD_DEADLINE: '[data-testid="grpc-hybrid-nav-item-field-deadline"]',
  HYBRID_NAV_ITEM_ONEOF: (oneofName: string) => `[data-testid="grpc-hybrid-nav-item-oneof-${oneofName}"]`,
  /** Full Form Editor modal — focus detail editor panel (Focus View). */
  HYBRID_FOCUS_EDITOR: '[data-testid="grpc-hybrid-focus-editor"]',
  /** Full Form Editor modal — Form View panel (Option A). */
  HYBRID_FORM_VIEW: '[data-testid="grpc-hybrid-form-view"]',
  /** Full Form Editor modal — Focus View panel (Option B). */
  HYBRID_FOCUS_VIEW: '[data-testid="grpc-hybrid-option-b-view"]',
  /** Full Form Editor modal — JSON View panel (Option C). */
  HYBRID_JSON_VIEW: '[data-testid="grpc-hybrid-json-view"]',
  /** Full Form Editor modal — JSON editor textarea (JSON View). */
  HYBRID_JSON_EDITOR: '[data-testid="grpc-hybrid-json-editor"]',
  /** Full Form Editor modal — complexity insight chips (Form View). */
  HYBRID_INSIGHT_CHIPS: '[data-testid="grpc-hybrid-option-a-insights"]',
  REQUEST_TAB_METADATA: '[data-testid="grpc-request-tab-metadata"]',
  REQUEST_TAB_AUTH: '[data-testid="grpc-request-tab-auth"]',
  REQUEST_TAB_FILES: '[data-testid="grpc-request-tab-files"]',
  REQUEST_FILES_PANEL: '[data-testid="grpc-request-files-panel"]',
  REQUEST_FILES_INPUT: '[data-testid="grpc-request-files-input"]',
  REQUEST_FILES_LIST: '[data-testid="grpc-request-files-list"]',
  REQUEST_FILES_EMPTY: '[data-testid="grpc-request-files-empty"]',
  REQUEST_FILES_COUNT: '[data-testid="grpc-request-files-count"]',
  REQUEST_FILES_CLEAR: '[data-testid="grpc-request-files-clear"]',
  REQUEST_FILES_REMOVE_AT: (index: number) => `[data-testid="grpc-request-files-remove-${index}"]`,
  REQUEST_JSON: '[data-testid="grpc-request-json"]',
  /** Demo-only: the "message" line inside the request JSON editor, tagged by lessons for precise spotlighting. */
  REQUEST_JSON_MESSAGE_LINE: '[data-testid="grpc-request-json-message-line"]',
  REQUEST_JSON_TOOLBAR: '[data-testid="grpc-request-json-toolbar"]',
  REQUEST_JSON_PRETTY_BTN: '[data-testid="grpc-request-json-pretty-btn"]',
  REQUEST_JSON_COPY_BTN: '[data-testid="grpc-request-json-copy-btn"]',
  REQUEST_JSON_ERROR: '[data-testid="grpc-request-json-error"]',
  PROTO_FORM: '[data-testid="grpc-proto-form"]',
  PROTO_GUIDED_CARD_CORE: '[data-testid="grpc-proto-guided-card-core"]',
  PROTO_GUIDED_CARD_MAPS: '[data-testid="grpc-proto-guided-card-maps"]',
  PROTO_GUIDED_CARD_REPEATED: '[data-testid="grpc-proto-guided-card-repeated"]',
  PROTO_GUIDED_CARD_ONEOF: (oneofName: string) => `[data-testid="grpc-proto-guided-card-oneof-${oneofName}"]`,
  /** Echo lesson / unary demos — scalar `message` field on EchoRequest. */
  PROTO_FIELD_INPUT_MESSAGE: '[data-testid="grpc-proto-field-input-message"]',
  PROTO_FIELD_INPUT: (fieldName: string) => `[data-testid="grpc-proto-field-input-${fieldName}"]`,
  PROTO_FIELD: (fieldName: string) => `[data-testid="grpc-proto-field-${fieldName}"]`,
  PROTO_FIELD_REPEATED_ADD: (fieldName: string) => `[data-testid="grpc-proto-repeated-add-${fieldName}"]`,
  /** Draft input for repeated string fields — type here, then click + Add item or press Enter. */
  PROTO_FIELD_REPEATED_TOKEN_INPUT: (fieldName: string) =>
    `[data-testid="grpc-proto-repeated-token-input-${fieldName}"]`,
  PROTO_FIELD_MAP_ADD: (fieldName: string) => `[data-testid="grpc-proto-map-add-${fieldName}"]`,
  PROTO_FIELD_INPUT_INDEXED: (fieldName: string, index: number) =>
    `[data-testid="grpc-proto-field-input-${fieldName}-${index}"]`,
  PROTO_FIELD_MAP_KEY: (fieldName: string, index: number) =>
    `[data-testid="grpc-proto-field-input-${fieldName}-key-${index}"]`,
  PROTO_FIELD_MAP_VALUE: (fieldName: string, index: number) =>
    `[data-testid="grpc-proto-field-input-${fieldName}-value-${index}"]`,
  METADATA_EDITOR: '[data-testid="grpc-metadata-editor"]',
  METADATA_ADD_BTN: '[data-testid="grpc-metadata-add-btn"]',
  METADATA_VALIDATION_ERROR: '[data-testid="grpc-metadata-validation-error"]',
  RESPONSE_PANEL_PLACEHOLDER: '[data-testid="grpc-response-panel-placeholder"]',
  RESPONSE_PANEL: '[data-testid="grpc-response-panel"]',
  RESPONSE_HEADER: '[data-testid="grpc-response-header"]',
  RESPONSE_STATUS: '[data-testid="grpc-response-status"]',
  RESPONSE_DURATION: '[data-testid="grpc-response-duration"]',
  RESPONSE_SIZE: '[data-testid="grpc-response-size"]',
  RESPONSE_TRACING_CHIP: '[data-testid="grpc-response-tracing-chip"]',
  RESPONSE_TARGET: '[data-testid="grpc-response-target"]',
  RESPONSE_RAW_TOGGLE: '[data-testid="grpc-response-raw-toggle"]',
  RESPONSE_COPY: '[data-testid="grpc-response-copy"]',
  RESPONSE_IDLE: '[data-testid="grpc-response-idle"]',
  RESPONSE_IN_FLIGHT: '[data-testid="grpc-response-in-flight"]',
  RESPONSE_CANCELLED: '[data-testid="grpc-response-cancelled"]',
  RESPONSE_ERROR_SUMMARY: '[data-testid="grpc-response-error-summary"]',
  RESPONSE_ERROR_PANEL: '[data-testid="grpc-response-error-panel"]',
  RESPONSE_ERROR_MESSAGE: '[data-testid="grpc-response-error-message"]',
  RESPONSE_BROWSER_TRANSPORT_HINT: '[data-testid="grpc-response-browser-transport-hint"]',
  RETRY_EXPRESS_BTN: '[data-testid="grpc-retry-express-btn"]',
  STREAM_RETRY_EXPRESS_BTN: '[data-testid="grpc-stream-retry-express-btn"]',
  RESPONSE_TAB_BODY: '[data-testid="grpc-response-tab-body"]',
  RESPONSE_TAB_HEADERS: '[data-testid="grpc-response-tab-headers"]',
  RESPONSE_TAB_TRAILERS: '[data-testid="grpc-response-tab-trailers"]',
  RESPONSE_TAB_METADATA: '[data-testid="grpc-response-tab-metadata"]',
  RESPONSE_TAB_TRACING: '[data-testid="grpc-response-tab-tracing"]',
  RESPONSE_TAB_TIMING: '[data-testid="grpc-response-tab-timing"]',
  RESPONSE_TOP_TAB_RESPONSE: '[data-testid="grpc-response-top-tab-response"]',
  RESPONSE_TOP_TAB_PROTO: '[data-testid="grpc-response-top-tab-proto"]',
  RESPONSE_PROTO_PANEL: '[data-testid="grpc-response-proto-panel"]',
  RESPONSE_PROTO_CODE: '[data-testid="grpc-response-proto-code"]',
  RESPONSE_PROTO_EXPORT: '[data-testid="grpc-response-proto-export"]',
  RESPONSE_BODY: '[data-testid="grpc-response-body"]',
  RESPONSE_JSON_TOOLBAR: '[data-testid="grpc-response-json-toolbar"]',
  RESPONSE_JSON_PRETTY_BTN: '[data-testid="grpc-response-json-pretty-btn"]',
  RESPONSE_JSON_COPY_BTN: '[data-testid="grpc-response-json-copy-btn"]',
  RESPONSE_HEADERS: '[data-testid="grpc-response-headers"]',
  RESPONSE_TRAILERS: '[data-testid="grpc-response-trailers"]',
  RESPONSE_METADATA: '[data-testid="grpc-response-metadata"]',
  RESPONSE_TRACING: '[data-testid="grpc-response-tracing"]',
  RESPONSE_TIMING: '[data-testid="grpc-response-timing"]',
  RESPONSE_LATENCY_FOOTER: '[data-testid="grpc-response-latency-footer"]',
  RESPONSE_LATENCY_MIN: '[data-testid="grpc-response-latency-min"]',
  RESPONSE_LATENCY_AVG: '[data-testid="grpc-response-latency-avg"]',
  RESPONSE_LATENCY_P95: '[data-testid="grpc-response-latency-p95"]',
  RESPONSE_LATENCY_MAX: '[data-testid="grpc-response-latency-max"]',
  RESPONSE_LATENCY_HISTORY: '[data-testid="grpc-response-latency-history"]',
  RESPONSE_TIMING_ROW: (key: string) => `[data-testid="grpc-response-timing-row-${key}"]`,
  /** Phase 2F — streaming UI */
  STREAM_PANEL: '[data-testid="grpc-stream-panel"]',
  STREAM_ERROR: '[data-testid="grpc-stream-error"]',
  STREAM_MESSAGE_LOG: '[data-testid="grpc-stream-message-log"]',
  STREAM_LOG_LIST: '[data-testid="grpc-stream-log-list"]',
  STREAM_LOG_COUNT: '[data-testid="grpc-stream-log-count"]',
  STREAM_LOG_EMPTY: '[data-testid="grpc-stream-log-empty"]',
  STREAM_STATUS_BAR: '[data-testid="grpc-stream-status-bar"]',
  STREAM_STATUS_BADGE: '[data-testid="grpc-stream-status-badge"]',
  STREAM_INBOUND_COUNT: '[data-testid="grpc-stream-inbound-count"]',
  STREAM_OUTBOUND_COUNT: '[data-testid="grpc-stream-outbound-count"]',
  STREAM_ELAPSED: '[data-testid="grpc-stream-elapsed"]',
  STREAM_CLEAR_LOG: '[data-testid="grpc-stream-clear-log"]',
  STREAM_EXPORT_LOG_BTN: '[data-testid="grpc-stream-export-log-btn"]',
  STREAM_PENDING_PANEL: '[data-testid="grpc-stream-pending-panel"]',
  STREAM_PENDING_LIST: '[data-testid="grpc-stream-pending-list"]',
  STREAM_PENDING_EMPTY: '[data-testid="grpc-stream-pending-empty"]',
  STREAM_PENDING_CHIP: '[data-testid="grpc-stream-pending-chip"]',
  STREAM_PENDING_ITEM: (index: number) => `[data-testid="grpc-stream-pending-item-${index}"]`,
  STREAM_PENDING_REMOVE: (index: number) => `[data-testid="grpc-stream-pending-remove-${index}"]`,
  STREAM_SEND_ALL_BTN: '[data-testid="grpc-stream-send-all-btn"]',
  STREAM_PENDING_END_BTN: '[data-testid="grpc-stream-pending-end-btn"]',
  STREAM_ADD_QUEUE_BTN: '[data-testid="grpc-stream-add-queue-btn"]',
  STREAM_SEND_NOW_BTN: '[data-testid="grpc-stream-send-now-btn"]',
  CALL_TYPE_SELECTOR: '[data-testid="grpc-call-type-selector"]',
  CALL_TYPE_TAB: (callType: string) => `[data-testid="grpc-call-type-tab-${callType}"]`,
  STREAM_LAYOUT_PREVIEW_HINT: '[data-testid="grpc-stream-layout-preview-hint"]',
  STREAM_PENDING_COUNT: '[data-testid="grpc-stream-pending-chip"]',
  STREAM_SEND_MESSAGE_BTN: '[data-testid="grpc-stream-send-message-btn"]',
  STREAM_END_BTN: '[data-testid="grpc-stream-end-btn"]',
  STREAM_START_BTN: '[data-testid="grpc-stream-start-btn"]',
  STREAM_CANCEL_BTN: '[data-testid="grpc-stream-cancel-btn"]',
  STREAM_DIRECTION_LEGEND: '[data-testid="grpc-stream-direction-legend"]',
  TAB_CALL_TYPE_PILL: (tabId: string) => `[data-testid="grpc-tab-call-type-pill-${tabId}"]`,
  TAB_CALL_COUNT_BADGE: (tabId: string) => `[data-testid="grpc-tab-call-count-${tabId}"]`,
  CALL_PANEL_EMPTY: '[data-testid="grpc-call-panel-empty"]',
  CALL_PANEL_PLACEHOLDER: '[data-testid="grpc-call-panel-placeholder"]',
  EXPLORER_IDLE: '[data-testid="grpc-explorer-idle"]',
  EXPLORER_LOADING: '[data-testid="grpc-explorer-loading"]',
  EXPLORER_ERROR: '[data-testid="grpc-explorer-error"]',
  METHOD_DETAIL: '[data-testid="grpc-method-detail"]',
  METHOD_DETAIL_EMPTY: '[data-testid="grpc-method-detail-empty"]',
  METHOD_DETAIL_STALE: '[data-testid="grpc-method-detail-stale"]',
  METHOD_DETAIL_SERVICE: '[data-testid="grpc-method-detail-service"]',
  METHOD_DETAIL_REQUEST_TYPE: '[data-testid="grpc-method-detail-request-type"]',
  METHOD_DETAIL_RESPONSE_TYPE: '[data-testid="grpc-method-detail-response-type"]',
  METHOD_CALL_TYPE: '[data-testid="grpc-method-call-type"]',
  METHOD_UNARY_READY: '[data-testid="grpc-method-unary-ready"]',
  SERVICE: (serviceFullName: string) => `[data-testid="grpc-service-${serviceFullName.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').toLowerCase()}"]`,
  METHOD: (serviceFullName: string, methodName: string) => `[data-testid="grpc-method-${`${serviceFullName}-${methodName}`.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').toLowerCase()}"]`,
  /** Phase 5H — collections / history */
  STUDIO_SUB_NAV: '[data-testid="grpc-studio-sub-nav"]',
  SUB_NAV_STUDIO: '[data-testid="grpc-sub-nav-studio"]',
  SUB_NAV_COLLECTIONS: '[data-testid="grpc-sub-nav-collections"]',
  SUB_NAV_HISTORY: '[data-testid="grpc-sub-nav-history"]',
  SUB_NAV_HISTORY_BADGE: '[data-testid="grpc-sub-nav-history-badge"]',
  CONSOLE_LAUNCHER: '[data-testid="grpc-console-launcher"]',
  CONSOLE_LAUNCHER_COUNT: '[data-testid="grpc-console-launcher-count"]',
  CONSOLE_MODAL: '[data-testid="grpc-console-modal"]',
  CONSOLE_MODAL_CLOSE: '[data-testid="grpc-console-modal-close"]',
  CONSOLE_MODAL_CLEAR: '[data-testid="grpc-console-modal-clear"]',
  SAVE_REQUEST_BTN: '[data-testid="grpc-save-request-btn"]',
  IMPORT_GRPCURL_BTN: '[data-testid="grpc-import-grpcurl-btn"]',
  COLLECTIONS_PANEL: '[data-testid="grpc-collections-panel"]',
  COLLECTIONS_SEARCH: '[data-testid="grpc-collections-search"]',
  COLLECTIONS_NEW_BTN: '[data-testid="grpc-collections-new-btn"]',
  COLLECTIONS_EXPORT_BTN: '[data-testid="grpc-collections-export-btn"]',
  COLLECTIONS_IMPORT_BTN: '[data-testid="grpc-collections-import-btn"]',
  COLLECTIONS_IMPORT_INPUT: '[data-testid="grpc-collections-import-input"]',
  COLLECTIONS_TREE: '[data-testid="grpc-collections-tree"]',
  COLLECTION_GROUP: (collectionId: string) => `[data-testid="grpc-collection-group-${collectionId}"]`,
  COLLECTION_GROUP_RENAME: (collectionId: string) => `[data-testid="grpc-collection-group-rename-${collectionId}"]`,
  COLLECTION_RENAME_MODAL: '[data-testid="grpc-collection-rename-modal"]',
  COLLECTION_RENAME_INPUT: '[data-testid="grpc-collection-rename-input"]',
  COLLECTION_RENAME_CANCEL: '[data-testid="grpc-collection-rename-cancel"]',
  COLLECTION_RENAME_SAVE: '[data-testid="grpc-collection-rename-save"]',
  COLLECTION_SAVED_REQUEST: (savedId: string) => `[data-testid="grpc-collection-saved-${savedId}"]`,
  SAVED_REQUEST_DETAIL: '[data-testid="grpc-saved-request-detail"]',
  SAVED_REQUEST_OPEN_STUDIO: '[data-testid="grpc-saved-request-open-studio"]',
  SAVED_REQUEST_COPY_GRPCURL: '[data-testid="grpc-saved-request-copy-grpcurl"]',
  SAVED_REQUEST_DELETE: '[data-testid="grpc-saved-request-delete"]',
  SAVED_REQUEST_DUPLICATE: '[data-testid="grpc-saved-request-duplicate"]',
  SAVED_REQUEST_RENAME: '[data-testid="grpc-saved-request-rename"]',
  SAVED_REQUEST_RENAME_MODAL: '[data-testid="grpc-saved-request-rename-modal"]',
  SAVED_REQUEST_RENAME_INPUT: '[data-testid="grpc-saved-request-rename-input"]',
  SAVED_REQUEST_RENAME_SAVE: '[data-testid="grpc-saved-request-rename-save"]',
  SAVED_REQUEST_RENAME_CANCEL: '[data-testid="grpc-saved-request-rename-cancel"]',
  HISTORY_PANEL: '[data-testid="grpc-history-panel"]',
  HISTORY_SEARCH: '[data-testid="grpc-history-search"]',
  HISTORY_FILTER_SERVICE: '[data-testid="grpc-history-filter-service"]',
  HISTORY_FILTER_STATUS: '[data-testid="grpc-history-filter-status"]',
  HISTORY_CLEAR_FILTERED: '[data-testid="grpc-history-clear-filtered"]',
  HISTORY_CLEAR_ALL: '[data-testid="grpc-history-clear-all"]',
  HISTORY_LIST: '[data-testid="grpc-history-list"]',
  /** First (or any) persisted call row — entry id is dynamic. */
  HISTORY_ENTRY_ROW: '[data-testid^="grpc-history-entry-"]',
  HISTORY_ENTRY: (entryId: string) => `[data-testid="grpc-history-entry-${entryId}"]`,
  HISTORY_DETAIL: '[data-testid="grpc-history-detail"]',
  HISTORY_REPLAY_BTN: '[data-testid="grpc-history-replay-btn"]',
  HISTORY_COPY_GRPCURL: '[data-testid="grpc-history-copy-grpcurl"]',
  CONSOLE_PANEL: '[data-testid="grpc-console-panel"]',
  CONSOLE_SEARCH: '[data-testid="grpc-console-search"]',
  CONSOLE_FILTER_STATUS: '[data-testid="grpc-console-filter-status"]',
  CONSOLE_LIST: '[data-testid="grpc-console-list"]',
  CONSOLE_ENTRY_ROW: '[data-testid^="grpc-console-entry-"]',
  CONSOLE_DETAIL: '[data-testid="grpc-console-detail"]',
  CONSOLE_REPLAY_BTN: '[data-testid="grpc-console-replay-btn"]',
  CONSOLE_COPY_GRPCURL: '[data-testid="grpc-console-copy-grpcurl"]',
  SAVE_REQUEST_MODAL: '[data-testid="grpc-save-request-modal"]',
  SAVE_REQUEST_NAME: '[data-testid="grpc-save-request-name"]',
  SAVE_REQUEST_COLLECTION: '[data-testid="grpc-save-request-collection"]',
  SAVE_REQUEST_NEW_COLLECTION: '[data-testid="grpc-save-request-new-collection"]',
  SAVE_REQUEST_SUBMIT: '[data-testid="grpc-save-request-submit"]',
  SAVE_REQUEST_CANCEL: '[data-testid="grpc-save-request-cancel"]',
  IMPORT_GRPCURL_MODAL: '[data-testid="grpc-import-grpcurl-modal"]',
  IMPORT_GRPCURL_TEXTAREA: '[data-testid="grpc-import-grpcurl-textarea"]',
  IMPORT_GRPCURL_PREVIEW: '[data-testid="grpc-import-grpcurl-preview"]',
  IMPORT_GRPCURL_WARNINGS: '[data-testid="grpc-import-grpcurl-warnings"]',
  IMPORT_GRPCURL_SUBMIT: '[data-testid="grpc-import-grpcurl-submit"]',
  IMPORT_GRPCURL_CANCEL: '[data-testid="grpc-import-grpcurl-cancel"]',
  /** Phase 5I — response snapshot baseline */
  RESPONSE_SNAPSHOT_PANEL: '[data-testid="grpc-response-snapshot-panel"]',
  SNAPSHOT_BADGE_MATCH: '[data-testid="grpc-snapshot-badge-match"]',
  SNAPSHOT_BADGE_DIFF: '[data-testid="grpc-snapshot-badge-diff"]',
  SNAPSHOT_BADGE_NONE: '[data-testid="grpc-snapshot-badge-none"]',
  SNAPSHOT_UPDATE_BASELINE: '[data-testid="grpc-snapshot-update-baseline"]',
  SNAPSHOT_VIEW_DIFF: '[data-testid="grpc-snapshot-view-diff"]',
  SNAPSHOT_CLEAR_BASELINE: '[data-testid="grpc-snapshot-clear-baseline"]',
  SNAPSHOT_DIFF_MODAL: '[data-testid="grpc-snapshot-diff-modal"]',
  SNAPSHOT_DIFF_CLOSE: '[data-testid="grpc-snapshot-diff-close"]',
  SUB_NAV_ADVANCED: '[data-testid="grpc-sub-nav-advanced"]',
  ADVANCED_SHELL: '[data-testid="grpc-advanced-shell"]',
  ADVANCED_NAV: '[data-testid="grpc-advanced-nav"]',
  ADVANCED_TAB: (tab: string) => `[data-testid="grpc-advanced-tab-${tab}"]`,
  LOAD_TEST_PANEL: '[data-testid="grpc-load-test-panel"]',
  LOAD_TEST_METHOD_SELECT: '[data-testid="grpc-load-test-method-select"]',
  LOAD_TEST_CONCURRENCY: '[data-testid="grpc-load-test-concurrency"]',
  LOAD_TEST_START: '[data-testid="grpc-load-test-start-btn"]',
  LOAD_TEST_STOP: '[data-testid="grpc-load-test-stop-btn"]',
  LOAD_TEST_STATUS: '[data-testid="grpc-load-test-status"]',
  LOAD_TEST_RESULTS: '[data-testid="grpc-load-test-results"]',
  LOAD_TEST_SUMMARY_METRICS: '[data-testid="grpc-load-test-summary-metrics"]',
  LOAD_TEST_PROFILE_SELECT: '[data-testid="grpc-load-test-profile-select"]',
  LOAD_TEST_PROFILE_NAME: '[data-testid="grpc-load-test-profile-name"]',
  LOAD_TEST_PROFILE_SAVE: '[data-testid="grpc-load-test-profile-save"]',
  LOAD_TEST_PROFILE_LOAD: '[data-testid="grpc-load-test-profile-load"]',
  LOAD_TEST_PROFILE_RENAME: '[data-testid="grpc-load-test-profile-rename"]',
  LOAD_TEST_PROFILE_DELETE: '[data-testid="grpc-load-test-profile-delete"]',
  LOAD_TEST_CALL_TYPE_BADGE: '[data-testid="grpc-load-test-call-type-badge"]',
  LOAD_TEST_MAX_MESSAGES_PER_STREAM: '[data-testid="grpc-load-test-max-messages-per-stream"]',
  LOAD_TEST_EXPORT_JSON: '[data-testid="grpc-load-test-export-json"]',
  LOAD_TEST_DOWNLOAD_JSON: '[data-testid="grpc-load-test-download-json"]',
  LOAD_TEST_EXPORT_CSV: '[data-testid="grpc-load-test-export-csv"]',
  LOAD_TEST_DOWNLOAD_CSV: '[data-testid="grpc-load-test-download-csv"]',
  LOAD_TEST_EXPORT_ERROR: '[data-testid="grpc-load-test-export-error"]',
  LOAD_TEST_LIVE_COMPLETED: '[data-testid="grpc-load-test-live-completed"]',
  LOAD_TEST_LIVE_THROUGHPUT: '[data-testid="grpc-load-test-live-throughput"]',
  LOAD_TEST_LIVE_SUCCESS_RATE: '[data-testid="grpc-load-test-live-success-rate"]',
  LOAD_TEST_LIVE_P50: '[data-testid="grpc-load-test-live-p50"]',
  LOAD_TEST_LIVE_ERROR_RATE: '[data-testid="grpc-load-test-live-error-rate"]',
  LOAD_TEST_REQUEST_RATE: '[data-testid="grpc-load-test-request-rate"]',
  LOAD_TEST_REQUEST_TEMPLATE: '[data-testid="grpc-load-test-request-template"]',
  LOAD_TEST_RUN_HISTORY_SELECT: '[data-testid="grpc-load-test-run-history-select"]',
  LOAD_TEST_RUN_STRIP: '[data-testid="grpc-load-test-run-strip"]',
  LOAD_TEST_PERCENTILE_LEGEND: '[data-testid="grpc-load-test-percentile-legend"]',
  LOAD_TEST_RUN_COMPARE: '[data-testid="grpc-load-test-run-compare"]',
  LOAD_TEST_RUN_COMPARE_SELECT: '[data-testid="grpc-load-test-run-compare-select"]',
  LOAD_TEST_RUN_COMPARE_DETAILS: '[data-testid="grpc-load-test-run-compare-details"]',
  LOAD_TEST_RUN_COMPARE_STATUS: '[data-testid="grpc-load-test-run-compare-status-composition"]',
  LOAD_TEST_COMPARE_GRID: '.grpc-load-test-compare-grid',
  LOAD_TEST_STATUS_BREAKDOWN: '[data-testid="grpc-load-test-status-breakdown"]',
  LOAD_TEST_LATENCY_HISTOGRAM: '[data-testid="grpc-load-test-latency-histogram"]',
  LOAD_TEST_THROUGHPUT_TIMELINE: '[data-testid="grpc-load-test-throughput-timeline"]',
  MOCK_SERVER_PANEL: '[data-testid="grpc-mock-server-panel"]',
  MOCK_TAB_BUILDER: '[data-testid="grpc-mock-tab-builder"]',
  MOCK_TAB_JSON: '[data-testid="grpc-mock-tab-json"]',
  MOCK_TAB_RUNTIME: '[data-testid="grpc-mock-tab-runtime"]',
  MOCK_BUILDER_PANEL: '[data-testid="grpc-mock-builder-panel"]',
  MOCK_BUILDER_ADD_RULE: '[data-testid="grpc-mock-builder-add-rule"]',
  MOCK_BUILDER_RULE: '[data-testid^="grpc-mock-builder-rule-"]',
  MOCK_BUILDER_SEARCH: '[data-testid="grpc-mock-builder-search"]',
  MOCK_BUILDER_COLLAPSE_ALL: '[data-testid="grpc-mock-builder-collapse-all"]',
  MOCK_BUILDER_EXPAND_ALL: '[data-testid="grpc-mock-builder-expand-all"]',
  MOCK_BUILDER_GENERATE_STUBS: '[data-testid="grpc-mock-builder-generate-stubs"]',
  MOCK_BUILDER_EMPTY: '[data-testid="grpc-mock-builder-empty"]',
  MOCK_BUILDER_CONFLICTS: '[data-testid="grpc-mock-builder-conflicts"]',
  MOCK_JSON_EDITOR: '[data-testid="grpc-mock-json-editor"]',
  MOCK_EXPORT_JSON: '[data-testid="grpc-mock-export-json"]',
  MOCK_START: '[data-testid="grpc-mock-start-btn"]',
  MOCK_STOP: '[data-testid="grpc-mock-stop-btn"]',
  MOCK_EXPOSE_NETWORK: '[data-testid="grpc-mock-expose-network"]',
  MOCK_LISTEN_TARGET: '[data-testid="grpc-mock-listen-target"]',
  MOCK_COPY_LISTEN_TARGET: '[data-testid="grpc-mock-copy-listen-target"]',
  MOCK_LISTENER_GENERATION: '[data-testid="grpc-mock-listener-generation"]',
  MOCK_LISTENER_LOG: '[data-testid="grpc-mock-listener-log"]',
  MOCK_STATUS: '[data-testid="grpc-mock-status"]',
  MOCK_RULES_JSON: '[data-testid="grpc-mock-rules-json"]',
  SCHEMA_DIFF_PANEL: '[data-testid="grpc-schema-diff-panel"]',
  SCHEMA_DIFF_CAPTURE_BASELINE: '[data-testid="grpc-schema-diff-capture-baseline"]',
  SCHEMA_DIFF_COMPARE: '[data-testid="grpc-schema-diff-compare-btn"]',
  SCHEMA_DIFF_STATUS: '[data-testid="grpc-schema-diff-status"]',
  SCHEMA_DIFF_RESULTS: '[data-testid="grpc-schema-diff-results"]',
  SCHEMA_DIFF_CHANGE_LIST: '[data-testid="grpc-schema-diff-change-list"]',
  SCHEMA_DIFF_HIDE_ACKNOWLEDGED: '[data-testid="grpc-schema-diff-hide-acknowledged"]',
  SCHEMA_DIFF_ACK_BTN: '[data-testid="grpc-schema-diff-ack-btn"]',
  SCHEMA_DIFF_EXPORT_JSON: '[data-testid="grpc-schema-diff-export-json"]',
  SCHEMA_DIFF_EXPORT_MARKDOWN: '[data-testid="grpc-schema-diff-export-markdown"]',
  SCHEMA_DIFF_SEVERITY_FILTER: '[data-testid="grpc-schema-diff-severity-filter"]',
  SCHEMA_DIFF_BASELINE_KEY: '[data-testid="grpc-schema-diff-baseline-key"]',
  SCHEMA_DIFF_SUMMARY: '[data-testid="grpc-schema-diff-summary"]',
  SCHEMA_DIFF_CHANGE_ROW: '[data-testid="grpc-schema-diff-change-row"]',
  SCHEMA_DIFF_CLEAR_BASELINE: '[data-testid="grpc-schema-diff-clear-baseline"]',
  SCHEMA_DIFF_PROTO_BTN: '[data-testid="grpc-sdiff-group-proto-btn"]',
  SCHEMA_DIFF_PROTO_BADGE: '[data-testid="grpc-sdiff-group-proto-badge"]',
  SCHEMA_DIFF_PROTO_MODAL: '[data-testid="grpc-sdiff-proto-modal"]',
  SCHEMA_DIFF_PROTO_IMPACT_SUMMARY: '[data-testid="grpc-sdiff-proto-impact-summary"]',
  SCHEMA_DIFF_PROTO_BEFORE: '[data-testid="grpc-sdiff-proto-before"]',
  SCHEMA_DIFF_PROTO_AFTER: '[data-testid="grpc-sdiff-proto-after"]',
  SCHEMA_DIFF_PROTO_MODAL_CLOSE: '[data-testid="grpc-sdiff-proto-modal-close"]',
  SAVED_REQUEST_RUN_LOAD_TEST: '[data-testid="grpc-saved-request-run-load-test"]',
  RPC_STATS_PANEL: '[data-testid="grpc-rpc-stats-panel"]',
  RPC_STATS_SUMMARY: '[data-testid="grpc-rpc-stats-summary"]',
  RPC_STATS_TABLE: '[data-testid="grpc-rpc-stats-table"]',
  RPC_STATS_RESET: '[data-testid="grpc-rpc-stats-reset-btn"]',
  RPC_STATS_EMPTY: '[data-testid="grpc-rpc-stats-empty"]',
    RPC_STATS_EXPORT_JSON_BTN: '[data-testid="grpc-rpc-stats-export-json-btn"]',
    RPC_STATS_EXPORT_CSV_BTN: '[data-testid="grpc-rpc-stats-export-csv-btn"]',
  RPC_STATS_TOTAL_CALLS: '[data-testid="grpc-rpc-stats-total-calls"]',
  RPC_STATS_ROW: '[data-testid="grpc-rpc-stats-row"]',
  // Native Diagnostics panel (Tauri desktop only)
  NATIVE_DIAGNOSTICS_PANEL: '[data-testid="grpc-native-diagnostics-panel"]',
  NATIVE_DIAGNOSTICS_REFRESH: '[data-testid="grpc-native-diagnostics-refresh"]',
  NATIVE_DIAGNOSTICS_COPY: '[data-testid="grpc-native-diagnostics-copy"]',
  NATIVE_DIAGNOSTICS_JSON: '[data-testid="grpc-native-diagnostics-json"]',
  NATIVE_DIAGNOSTICS_UNAVAILABLE: '[data-testid="grpc-native-diagnostics-unavailable"]',
  NATIVE_DIAGNOSTICS_EMPTY: '[data-testid="grpc-native-diagnostics-empty"]',
  NATIVE_DIAGNOSTICS_ERROR: '[data-testid="grpc-native-diagnostics-error"]',
  // Workflow Designer gRPC node config panels
  WF_UNARY_CONFIG: '[data-testid="grpc-unary-config"]',
  WF_UNARY_CFG_TARGET: '[data-testid="grpc-unary-config-target"]',
  WF_UNARY_CFG_REFLECT_STATUS: '[data-testid="grpc-unary-config-reflect-status"]',
  WF_UNARY_CFG_REFLECT_READY: '[data-testid="grpc-unary-config-reflect-status"][data-status="ready"]',
  WF_UNARY_CFG_SERVICE: '[data-testid="grpc-unary-config-service"]',
  WF_UNARY_CFG_METHOD: '[data-testid="grpc-unary-config-method"]',
  WF_UNARY_CFG_BODY: '[data-testid="grpc-unary-config-body"]',
  WF_UNARY_CFG_METADATA: '[data-testid="grpc-unary-config-metadata"]',
  WF_UNARY_CFG_SAVE_AS: '[data-testid="grpc-unary-config-save-as"]',
  WF_UNARY_CFG_TLS_MODE: '[data-testid="grpc-unary-config-tls-mode"]',
  WF_UNARY_CFG_TLS_CONFIGURE: '[data-testid="grpc-unary-config-tls-configure"]',
  WF_UNARY_CFG_AUTH_SECTION: '[data-testid="grpc-unary-config-auth-section"]',
  WF_ASSERT_CONFIG: '[data-testid="grpc-assert-config"]',
  WF_ASSERT_CFG_SOURCE: '[data-testid="grpc-assert-config-source"]',
  WF_ASSERT_CFG_ASSERTIONS: '[data-testid="grpc-assert-config-assertions"]',
  // Workflow Designer canvas nodes (gRPC unary / assert)
  CANVAS_UNARY_NODE: '[data-testid="grpc-canvas-unary-node"]',
  CANVAS_ASSERT_NODE: '[data-testid="grpc-canvas-assert-node"]',
  // GRPC-24 Workflow Runner lesson — cross-feature selectors (Workflow Runner / Results)
  LESSON24_WF_VARIABLES_BTN: '[data-testid="wf-toolbar-variables-btn"]',
  LESSON24_QUICK_TEST_VERIFY: '[data-testid="exec-summary"]',
  LESSON24_RUNNER_RUN_BTN: '[data-testid="workflow-runner-run-btn"]',
  LESSON24_RESULTS_METRICS: '[data-testid="results-metrics-cards"]',
  LESSON24_REQUEST_DETAILS_TAB: '[data-testid="results-tab-requests"]',
  LESSON24_RESULTS_EXPLORER_DIAGRAM: '[data-testid="results-explorer-diagram"]',
  LESSON24_EXPORT_JSON_BTN: '[data-testid="results-export-json-btn"]',
  WF_VIEW_RESULTS_BTN: '.completion-section .btn-primary, .wfp-view-results-btn, [data-testid="view-results-btn"]',
} as const;
