// ─── Workflow Designer ──────────────────────────────────────────
export const WF = {
  DESIGNER:            '.wf-designer',
  TOOLBAR:             '.wf-toolbar',
  TOOLBAR_SELECT:      '[data-testid="wf-toolbar-select"]',
  QUICK_TEST_BTN:      '.wf-quick-test-btn',
  PALETTE:             '.wf-palette',
  CANVAS:              '.wf-canvas-area',
  CONTROLS:            '[data-testid="controls"]',
  NODE_CONFIG:         '.wf-config-modal',
  CFG_CLOSE:           '.wf-config-modal-footer-actions .btn-ghost',
  CONSOLE:             '.wf-console-panel',
  EXEC_SUMMARY:        '[data-testid="exec-summary"]',
  TPL_BROWSE:          '[data-testid="tpl-browse"]',
  WS_CONNECT_CFG:      '[data-testid="ws-connect-config"]',
  WS_SEND_CFG:         '[data-testid="ws-send-config"]',
  WS_RECEIVE_CFG:      '[data-testid="ws-receive-config"]',
  SERVICES_BTN:        '[data-testid="wf-toolbar-services-btn"]',
  VARIABLES_BTN:       '[data-testid="wf-toolbar-variables-btn"]',
  // Sidebar
  SIDEBAR:             '.wf-sidebar',
  SIDEBAR_NEW_BTN:     'button[title="New workflow"]',
  NEW_BLANK_ITEM:      '.wf-new-dropdown-item:first-child',
  CREATE_INPUT:        '.req-confirm-input',
  CREATE_OK:           '.req-confirm-ok',
  // Palette items
  PAL_WS_CONNECT:      '.wf-palette-block-wsConnect',
  PAL_WS_SEND:         '.wf-palette-block-wsSend',
  PAL_WS_RECEIVE:      '.wf-palette-block-wsReceive',
  // Node config fields
  CFG_WS_URL:          '[data-testid="ws-connect-config"] .expr-input-wrapper input',
  CFG_WS_MSG:          '[data-testid="ws-send-config"] textarea.wf-config-textarea',
  CFG_SAVE:            '.wf-config-modal-footer-actions .btn-primary',
  CFG_CANCEL:          '.wf-config-modal-footer-actions .btn-ghost',
  // Canvas nodes
  NODE_WS_CONNECT:     '.react-flow__node-wsConnect',
  NODE_WS_SEND:        '.react-flow__node-wsSend',
  NODE_WS_RECEIVE:     '.react-flow__node-wsReceive',
  // GraphQL workflow palette blocks (Phase 4)
  PAL_GQL_QUERY:       '.wf-palette-block-graphqlQuery',
  PAL_GQL_MUTATION:    '.wf-palette-block-graphqlMutation',
  PAL_GQL_SUBSCRIPTION:'.wf-palette-block-graphqlSubscription',
  PAL_GQL_ASSERT:      '.wf-palette-block-graphqlAssert',
  NODE_GQL_QUERY:      '.react-flow__node-graphqlQuery',
  NODE_GQL_MUTATION:   '.react-flow__node-graphqlMutation',
  NODE_GQL_SUBSCRIPTION:'.react-flow__node-graphqlSubscription',
  NODE_GQL_ASSERT:     '.react-flow__node-graphqlAssert',
  WF_GQL_MUTATION_ENDPOINT:'[data-testid="gql-wf-mutation-panel"] .wf-config-field--row .expr-input-wrapper input',
  WF_GQL_SUBSCRIPTION_ENDPOINT:'[data-testid="gql-wf-subscription-panel"] .wf-config-field--row .expr-input-wrapper input',
  NODE_START:          '.react-flow__node-start',
  NODE_END:            '.react-flow__node-end',
  WF_GQL_ENDPOINT:     '[data-testid="gql-wf-query-panel"] .wf-config-field--row .expr-input-wrapper input',
  WF_GQL_ASSERT_SOURCE:'[data-testid="gql-wf-assert-source-var"]',
  WORKFLOW_SELECT:     '[data-testid="workflow-select"]',
  // Console badge and Debug button (Demo Player lessons)
  CONSOLE_BADGE:       '.wf-console-badge',
  DEBUG_BTN:           'button[title="Run workflow step-by-step"]',
  // Defaults (Variables) modal
  DEFAULTS_MODAL:      '.wf-defaults-modal',
  DEFAULTS_NEW_KEY:    '.wf-defaults-modal .wf-var-key-input[placeholder="name"]',
  DEFAULTS_NEW_VAL:    '.wf-defaults-modal .wf-var-new-row-value .wf-var-value-input',
  DEFAULTS_ADD_BTN:    '.wf-defaults-modal .wf-config-vars > div:last-child > button[type="button"]:last-of-type',
  DEFAULTS_SAVE_BTN:   '.wf-defaults-modal .btn-primary',
} as const;
