// ─── Workflow Designer ──────────────────────────────────────────
export const WF = {
  DESIGNER:            '.wf-designer',
  TOOLBAR:             '.wf-toolbar',
  TOOLBAR_SELECT:      '[data-testid="wf-toolbar-select"]',
  QUICK_TEST_BTN:      '.wf-quick-test-btn',
  PALETTE:             '.wf-palette',
  CANVAS:              '.wf-canvas-area',
  CONTROLS:            '[data-testid="controls"]',
  NODE_CONFIG:         '.wf-config-modal',
  CFG_CLOSE:           '.wf-config-modal-footer-actions .btn-ghost',
  CONSOLE:             '.wf-console-panel',
  EXEC_SUMMARY:        '[data-testid="exec-summary"]',
  TPL_BROWSE:          '[data-testid="tpl-browse"]',
  WS_CONNECT_CFG:      '[data-testid="ws-connect-config"]',
  WS_SEND_CFG:         '[data-testid="ws-send-config"]',
  WS_RECEIVE_CFG:      '[data-testid="ws-receive-config"]',
  SERVICES_BTN:        '[data-testid="wf-toolbar-services-btn"]',
  VARIABLES_BTN:       '[data-testid="wf-toolbar-variables-btn"]',
  // Sidebar
  SIDEBAR:             '.wf-sidebar',
  SIDEBAR_NEW_BTN:     'button[title="New workflow"]',
  FIT_VIEW_BTN:        '.wf-designer button[title="Fit view"]',
  NEW_BLANK_ITEM:      '.wf-new-dropdown-item:first-child',
  CREATE_INPUT:        '.req-confirm-input',
  CREATE_OK:           '.req-confirm-ok',
  // Palette tabs
  PAL_TAB_BLOCKS:      '[data-testid="wf-palette-tab-blocks"]',
  PAL_TAB_REQUESTS:    '[data-testid="wf-palette-tab-requests"]',
  PAL_TAB_CATALOG:     '[data-testid="wf-palette-tab-catalog"]',
  // Palette search
  PAL_SEARCH:          '.wf-palette-search',
  // Palette items
  PAL_WS_CONNECT:      '.wf-palette-block-wsConnect',
  PAL_WS_SEND:         '.wf-palette-block-wsSend',
  PAL_WS_RECEIVE:      '.wf-palette-block-wsReceive',
  PAL_HTTP:            '.wf-palette-block-http',
  // Kafka palette blocks
  PAL_KAFKA_PRODUCE:   '.wf-palette-block-kafkaProduce',
  PAL_KAFKA_CONSUME:   '.wf-palette-block-kafkaConsume',
  PAL_KAFKA_TRIGGER:   '.wf-palette-block-kafkaTrigger',
  PAL_KAFKA_WAIT:      '.wf-palette-block-kafkaWait',
  // WS trigger (supplement existing WS palette selectors)
  PAL_WS_TRIGGER:      '.wf-palette-block-wsTrigger',
  // GraphQL introspect (supplement existing GQL palette selectors)
  PAL_GQL_INTROSPECT:  '.wf-palette-block-graphqlIntrospect',
  PAL_CONDITION:       '.wf-palette-block-condition',
  PAL_SWITCH:          '.wf-palette-block-switch',
  PAL_LOG_DEBUG:       '.wf-palette-block-logDebug',
  // Node config fields
  CFG_WS_URL:          '[data-testid="ws-connect-config"] .expr-input-wrapper input',
  CFG_WS_MSG:          '[data-testid="ws-send-config"] textarea.wf-config-textarea',
  // Log/Debug config fields
  CFG_LOG_LEVEL:       '[data-testid="logdebug-config"] .cs-wrapper',
  CFG_LOG_MESSAGE:     '[data-testid="logdebug-config"] textarea.wf-config-textarea',
  CFG_SAVE:            '.wf-config-modal-footer-actions .btn-primary',
  CFG_CANCEL:          '.wf-config-modal-footer-actions .btn-ghost',
  // Canvas nodes
  NODE_WS_CONNECT:     '.react-flow__node-wsConnect',
  NODE_WS_SEND:        '.react-flow__node-wsSend',
  NODE_WS_RECEIVE:     '.react-flow__node-wsReceive',
  NODE_HTTP:           '.react-flow__node-http',
  NODE_CONDITION:      '.react-flow__node-condition',
  NODE_LOG_DEBUG:      '.react-flow__node-logDebug',
  NODE_SWITCH:         '.react-flow__node-switch',
  // HTTP config fields
  CFG_HTTP_URL:        '.wf-config-url-input',
  CFG_HTTP_URL_PREVIEW:'.wf-config-last-req-url',
  CFG_HTTP_METHOD:     '.wf-config-method-select',
  // HTTP extraction fields (Extract sub-tab)
  CFG_EXT_ADD:         '.extraction-editor .ext-add-btn',
  CFG_EXT_VAR:         '.extraction-editor .ext-row:last-child .ext-cell-var .ext-input',
  CFG_EXT_EXPR:        '.extraction-editor .ext-row:last-child .ext-cell-expr .ext-input',
  CFG_EXT_ROW:         '.extraction-editor .ext-row',
  // gRPC workflow palette blocks
  PAL_GRPC_UNARY:      '.wf-palette-block-grpcUnary',
  PAL_GRPC_ASSERT:     '.wf-palette-block-grpcAssert',
  PAL_GRPC_SERVER_STREAM: '.wf-palette-block-grpcServerStream',
  // gRPC workflow canvas nodes (testid on node body — reliable for demo verify/spotlight)
  NODE_GRPC_UNARY:     '[data-testid="grpc-canvas-unary-node"]',
  NODE_GRPC_ASSERT:    '[data-testid="grpc-canvas-assert-node"]',
  // gRPC workflow config modal fields
  GRPC_UNARY_CONFIG:       '[data-testid="grpc-unary-config"]',
  GRPC_UNARY_CFG_TARGET:   '[data-testid="grpc-unary-config-target"]',
  GRPC_UNARY_CFG_SERVICE:  '[data-testid="grpc-unary-config-service"]',
  GRPC_UNARY_CFG_METHOD:   '[data-testid="grpc-unary-config-method"]',
  GRPC_UNARY_CFG_BODY:     '[data-testid="grpc-unary-config-body"]',
  GRPC_UNARY_CFG_SAVE_AS:  '[data-testid="grpc-unary-config-save-as"]',
  GRPC_ASSERT_CONFIG:      '[data-testid="grpc-assert-config"]',
  GRPC_ASSERT_CFG_SOURCE:  '[data-testid="grpc-assert-config-source"]',
  GRPC_ASSERT_CFG_ASSERTIONS: '[data-testid="grpc-assert-config-assertions"]',
  // GraphQL workflow palette blocks (Phase 4)
  PAL_GQL_QUERY:       '.wf-palette-block-graphqlQuery',
  PAL_GQL_MUTATION:    '.wf-palette-block-graphqlMutation',
  PAL_GQL_SUBSCRIPTION:'.wf-palette-block-graphqlSubscription',
  PAL_GQL_ASSERT:      '.wf-palette-block-graphqlAssert',
  NODE_GQL_QUERY:      '.react-flow__node-graphqlQuery',
  NODE_GQL_MUTATION:   '.react-flow__node-graphqlMutation',
  NODE_GQL_SUBSCRIPTION:'.react-flow__node-graphqlSubscription',
  NODE_GQL_ASSERT:     '.react-flow__node-graphqlAssert',
  NODE_GQL_INTROSPECT: '.react-flow__node-graphqlIntrospect',
  // Kafka canvas nodes
  NODE_KAFKA_PRODUCE:  '.react-flow__node-kafkaProduce',
  NODE_KAFKA_CONSUME:  '.react-flow__node-kafkaConsume',
  // WS canvas nodes (supplement existing WS selectors)
  NODE_WS_TRIGGER:     '.react-flow__node-wsTrigger',
  WF_GQL_MUTATION_ENDPOINT:'[data-testid="gql-wf-endpoint-input"]',
  WF_GQL_SUBSCRIPTION_ENDPOINT:'[data-testid="gql-wf-endpoint-input"]',
  NODE_START:          '.react-flow__node-start',
  NODE_END:            '.react-flow__node-end',
  NODE_LOOP:           '.react-flow__node-loop',
  NODE_FORK:           '.react-flow__node-fork',
  NODE_JOIN:           '.react-flow__node-join',
  PAL_LOOP:            '.wf-palette-block-loop',
  PAL_FORK:            '.wf-palette-block-fork',
  PAL_JOIN:            '.wf-palette-block-join',
  PAL_ERROR_HANDLER:   '.wf-palette-block-errorHandler',
  // Error Handler canvas node
  NODE_ERROR_HANDLER:  '.react-flow__node-errorHandler',
  WF_GQL_ENDPOINT:     '[data-testid="gql-wf-endpoint-input"]',
  WF_GQL_ASSERT_SOURCE:'[data-testid="gql-wf-assert-source-var"]',
  WORKFLOW_SELECT:     '[data-testid="workflow-select"]',
  // Console badge and Debug button (Demo Player lessons)
  CONSOLE_BADGE:       '.wf-console-badge',
  RESET_RUN_BTN:       '.wf-toolbar-reset-btn',
  CONSOLE_CLEAR_BTN:   '.wf-console-action-btn[title="Clear console"]',
  CONSOLE_SEARCH_BTN:  '.wf-console-panel .wf-console-action-btn[title="Search console (Cmd+F)"]',
  CONSOLE_SEARCH_INPUT:'.wf-console-search-input',
  CONSOLE_MATCH:       '.wf-console-panel .wf-console-match',
  CONSOLE_LINE_MATCH:  '.wf-console-panel .wf-cl-line-current-match, .wf-console-panel .wf-cl-line-match',
  // The ACTIVE match line + the highlighted term inside it (updates as you press
  // Next/Prev). Use these — not CONSOLE_MATCH — to spotlight the *current* match.
  CONSOLE_CURRENT_LINE:  '.wf-console-panel .wf-cl-line-current-match',
  CONSOLE_CURRENT_MATCH: '.wf-console-panel .wf-cl-line-current-match .wf-console-match',
  CONSOLE_NEXT_MATCH_BTN:'.wf-console-panel button[title="Next match (Enter)"]',
  DEBUG_BTN:           'button[title="Run workflow step-by-step"]',
  DEBUG_STEP_BTN:      '.wf-debug-step-btn',
  DEBUG_BAR:           '.wf-debug-bar',
  DEBUG_RESUME_BTN:    '.wf-debug-bar button[title="Run remaining nodes without pausing"]',
  DEBUG_STEP_ALL_BTN:  '.wf-debug-bar button[title="Step all paused nodes simultaneously"]',
  DEBUG_STOP_BTN:      '.wf-debug-bar button[title="Stop debug session"]',
  // Variable context badge + modal
  VAR_CONTEXT_BADGE:   '.wf-var-badge',
  VAR_CONTEXT_MODAL:   '.wf-vars-modal',
  // Run History
  RUN_HISTORY_TRIGGER: '.wf-run-history-trigger',
  RUN_HISTORY_DROPDOWN:'.wf-run-history-dropdown',
  // Exec summary pass state
  EXEC_SUMMARY_PASS:   '.wf-exec-strip-pass',
  RUN_IN_HARNESS_BTN:  '.wf-toolbar-harness-btn',
  // Version history
  VERSIONS_BTN:        '.wf-toolbar-versions-btn',
  VERSION_PANEL:       '.wfv-panel',
  VERSION_ITEM:        '.wfv-item',
  VERSION_CHECKBOX:    '.wfv-checkbox',
  VERSION_COMPARE_BTN: '.wfv-compare-btn',
  VERSION_RESTORE_BTN: '.wfv-action-restore',
  VERSION_DIFF_MODAL:  '.wf-version-diff-modal',
  VERSION_DIFF_TAB:    '.wf-version-diff-tab',
  VERSION_CLOSE_BTN:   '.wfv-footer-close',
  // Orphan badge
  ORPHAN_BADGE:        '[data-testid="wf-orphan-badge"]',
  // Services panel
  SVC_PANEL:           '.wf-services-panel',
  SVC_MATRIX:          '.wf-svc-endpoint-matrix',
  // Defaults (Variables) modal
  DEFAULTS_MODAL:      '.wf-defaults-modal',
  DEFAULTS_NEW_KEY:    '.wf-defaults-modal .wf-var-key-input[placeholder="name"]',
  DEFAULTS_NEW_VAL:    '.wf-defaults-modal .wf-var-new-row-value .wf-var-value-input',
  /** Value input on an existing variable row (not the blank add row). */
  DEFAULTS_EXISTING_VALUE: '.wf-defaults-modal .wf-config-kv-row-vars:not(:last-child) .wf-var-value-input',
  DEFAULTS_ADD_BTN:    '.wf-defaults-modal .wf-config-vars > div:last-child > button[type="button"]:last-of-type',
  DEFAULTS_SAVE_BTN:   '.wf-defaults-modal .btn-primary',
} as const;
