import type { GraphqlSchemaDiffResult } from '@shared/types/graphql';

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Generate a self-contained HTML diff report (3D-9) */
export function generateHtmlReport(
  result: GraphqlSchemaDiffResult,
  oldLabel: string,
  newLabel: string,
): string {
  const rows = result.changes.map((c) => {
    const color = c.criticality === 'BREAKING'   ? '#f87171'
                : c.criticality === 'DANGEROUS'  ? '#fb923c'
                : c.criticality === 'DEPRECATED' ? '#facc15'
                : '#4ade80';
    const ackNote = c.acknowledged
      ? `<br><small style="color:#94a3b8">✓ Acknowledged${c.acknowledgeNote ? ': ' + escapeHtml(c.acknowledgeNote) : ''}</small>`
      : '';
    return `
      <tr>
        <td><span style="background:${color};color:#0f172a;padding:2px 6px;border-radius:3px;font-size:11px;font-weight:700">${c.criticality}</span></td>
        <td style="font-family:monospace;font-size:13px">${escapeHtml(c.path)}</td>
        <td>${escapeHtml(c.description)}${ackNote}</td>
      </tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Schema Diff: ${escapeHtml(oldLabel)} → ${escapeHtml(newLabel)}</title>
  <style>
    body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0f172a;color:#f1f5f9;margin:0;padding:24px}
    h1{font-size:1.4rem;margin:0 0 4px}
    .subtitle{color:#94a3b8;font-size:0.85rem;margin-bottom:20px}
    .summary{display:flex;gap:12px;margin-bottom:20px;flex-wrap:wrap}
    .pill{padding:4px 12px;border-radius:20px;font-size:0.8rem;font-weight:600}
    .breaking{background:#7f1d1d;color:#fca5a5}
    .dangerous{background:#7c2d12;color:#fdba74}
    .safe{background:#14532d;color:#86efac}
    .deprecated{background:#713f12;color:#fde68a}
    table{width:100%;border-collapse:collapse}
    th{background:#1e293b;padding:8px 12px;text-align:left;font-size:0.78rem;color:#94a3b8;font-weight:500}
    td{padding:8px 12px;border-bottom:1px solid #1e293b;font-size:0.82rem;vertical-align:top}
    tr:hover td{background:#1e293b}
    .gen{color:#475569;font-size:0.72rem;margin-top:20px}
  </style>
</head>
<body>
  <h1>Schema Diff Report</h1>
  <div class="subtitle">${escapeHtml(oldLabel)} → ${escapeHtml(newLabel)}</div>
  <div class="summary">
    ${result.breakingCount  > 0 ? `<span class="pill breaking">${result.breakingCount} Breaking</span>`   : ''}
    ${result.dangerousCount > 0 ? `<span class="pill dangerous">${result.dangerousCount} Dangerous</span>` : ''}
    ${result.safeCount      > 0 ? `<span class="pill safe">${result.safeCount} Safe</span>`               : ''}
    ${result.deprecatedCount> 0 ? `<span class="pill deprecated">${result.deprecatedCount} Deprecated</span>` : ''}
    ${result.changes.length === 0 ? '<span style="color:#94a3b8">No changes</span>' : ''}
  </div>
  <table>
    <thead><tr><th>Severity</th><th>Path</th><th>Description</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="gen">Generated by RedfireForge — ${new Date().toISOString()}</div>
</body>
</html>`;
}
