/**
 * Assembles GraphqlStudioPageBodyProps from composed layer hooks.
 */
import type { ReactNode } from 'react';
import { buildGraphqlStudioPageToolbarProps } from '../utils/graphqlStudioPageToolbarProps';
import type { GraphqlStudioPageToolbarSections } from '../utils/graphqlStudioPageToolbarProps';
import { buildVarsModelUri } from '../utils/monacoGraphqlSetup';
import type { GraphqlStudioPageBodyProps } from '../components/GraphqlStudioPageBody';
import type { GraphqlStudioPageFoundation } from './useGraphqlStudioPageFoundation';
import type { GraphqlStudioPageTabsLayer } from './useGraphqlStudioPageTabsLayer';
import type { GraphqlStudioPageExecutionLayer } from './useGraphqlStudioPageExecutionLayer';
import type { GraphqlStudioPageInteractionLayer } from './useGraphqlStudioPageInteractionLayer';
import type { GraphqlStudioPageProps } from '../graphqlStudioPageTypes';

export interface BuildGraphqlStudioPageBodyPropsInput {
  foundation: GraphqlStudioPageFoundation;
  tabsLayer: GraphqlStudioPageTabsLayer;
  executionLayer: GraphqlStudioPageExecutionLayer;
  interactionLayer: GraphqlStudioPageInteractionLayer;
  globalAuthProfiles: GraphqlStudioPageProps['globalAuthProfiles'];
}

export function buildGraphqlStudioPageBodyProps({
  foundation,
  tabsLayer,
  executionLayer,
  interactionLayer,
  globalAuthProfiles,
}: BuildGraphqlStudioPageBodyPropsInput): GraphqlStudioPageBodyProps {
  const { uiState, splitPanes, connection, collections, runner, subscription, endpointProtocolStatus } = foundation;
  const { schemaLayer, batchLayer, batchAdvSettings, advancedSettings, history, responsePaneState, complexity, varsError, queryValidationErrorCount, assertionResultMap, handleExecute, handleCancel, handleResponseSubTabChange, activeTabUploadProgress } = executionLayer;
  const { handleRunCollection, itemLoaders, subscriptionOrchestration, handleSubscribe, handleDismissComplexityWarning, handleSaveToCollection } = interactionLayer;

  const activeTab = tabsLayer.activeTab!;
  const activeTabId = tabsLayer.activeTabId!;

  const toolbarSections: GraphqlStudioPageToolbarSections = buildGraphqlStudioPageToolbarProps({
    tab: {
      activeTab,
      activeTabId,
      tabs: tabsLayer.tabs,
      operations: tabsLayer.operations,
      selectedOperation: tabsLayer.selectedOperation,
      varsError,
      queryValidationErrorCount,
      fileEntries: uiState.fileEntries,
    },
    connection: {
      resolvedTabEndpoint: tabsLayer.resolvedTabEndpoint,
      resolvedTabAuth: tabsLayer.resolvedTabAuth,
      resolvedTabSkipTlsVerify: tabsLayer.resolvedTabSkipTlsVerify,
      resolvedTabTls: tabsLayer.resolvedTabTls,
      resolvedTabPollingEnabled: tabsLayer.resolvedTabPollingEnabled,
      resolvedTabPollingIntervalSeconds: tabsLayer.resolvedTabPollingIntervalSeconds,
      hasActiveTabEndpointOverride: tabsLayer.hasActiveTabEndpointOverride,
      hasActiveTabProfileLink: tabsLayer.hasActiveTabProfileLink,
      hasActiveTabPollingOverride: tabsLayer.hasActiveTabPollingOverride,
      hasPendingProfileEndpoint: tabsLayer.hasPendingProfileEndpoint,
      endpoint: connection.endpoint,
      pageDefaultEndpointResolved: foundation.pageDefaultEndpointResolved,
      recentEndpoints: connection.recentEndpoints,
      profiles: connection.profiles,
      activeEnvironment: connection.activeEnvironment,
      globalEnvMap: foundation.globalEnvMap,
      endpointProtocolStatus,
      pollErrorMessage: schemaLayer.pollErrorMessage,
      globalAuthProfiles: globalAuthProfiles ?? [],
      authBadgePresentation: tabsLayer.authBadgePresentation,
    },
    execution: {
      handleExecute,
      handleCancel,
      isActiveTabExecuting: responsePaneState.executing,
      handleSubscribe,
      handleStopSubscription: subscriptionOrchestration.handleStopSubscription,
      handleSelectOperation: tabsLayer.handleSelectOperation,
      handleSubscriptionTransportChange: tabsLayer.handleSubscriptionTransportChange,
      subscriptionState: subscription.state,
      complexityResult: complexity.complexityResult,
      activeTabApqInfo: executionLayer.activeTabApqInfo,
    },
    schema: {
      connectionBarSchemaStatus: schemaLayer.connectionBarSchemaStatus,
      schemaInfo: schemaLayer.schemaInfo,
      introspecting: schemaLayer.introspecting,
      handleIntrospect: schemaLayer.handleIntrospect,
    },
    connectionHandlers: {
      handleConnectionEndpointChange: tabsLayer.connectionHandlers.handleConnectionEndpointChange,
      clearActiveTabEndpoint: tabsLayer.clearActiveTabEndpoint,
      handleConnectionSkipTlsChange: tabsLayer.connectionHandlers.handleConnectionSkipTlsChange,
      handleConnectionTlsChange: tabsLayer.connectionHandlers.handleConnectionTlsChange,
      handleConnectionPollingChange: tabsLayer.connectionHandlers.handleConnectionPollingChange,
      clearActiveTabPolling: tabsLayer.clearActiveTabPolling,
      removeRecentEndpoint: connection.removeRecentEndpoint,
      focusAuthPanel: uiState.focusAuthPanel,
    },
    batch: {
      advSettings: advancedSettings.advSettings,
      advSettingsOpen: advancedSettings.advSettingsOpen,
      advSettingsBtnRef: advancedSettings.advSettingsBtnRef,
      setAdvSettingsOpen: advancedSettings.setAdvSettingsOpen,
      batchSettingsProps: batchAdvSettings.batchSettingsProps,
      batchSummaryLabel: batchAdvSettings.batchSummaryLabel,
      batchExecuting: batchLayer.batchExecuting,
      batchEndpointMismatch: batchLayer.batchEndpointMismatch,
      batchEndpointReady: batchLayer.batchEndpointReady,
      batchProfileLinkPending: batchLayer.batchProfileLinkPending,
      effectiveBatchedTabs: batchLayer.effectiveBatchedTabs,
      handleSendBatch: batchLayer.handleSendBatch,
      handleAdvSettingsSave: batchAdvSettings.handleAdvSettingsSave,
      handleAdvSettingsCancel: batchAdvSettings.handleAdvSettingsCancel,
    },
    dialogs: {
      complexityGatePending: batchLayer.complexityGatePending,
      complexityResult: complexity.complexityResult,
      pendingExecuteAfterGateRef: batchLayer.pendingExecuteAfterGateRef,
      sessionBypassComplexityGateRef: batchLayer.sessionBypassComplexityGateRef,
      skipComplexityGateRef: batchLayer.skipComplexityGateRef,
      setComplexityGatePending: batchLayer.setComplexityGatePending,
      setComplexityWarningPending: complexity.setComplexityWarningPending,
      isDuplicate: executionLayer.isDuplicate,
      duplicateSourceTabId: executionLayer.duplicateSourceTabId,
      resolveDedupChoice: executionLayer.execution.resolveDedupChoice,
    },
    modals: {
      profileModalOpen: connection.profileModalOpen,
      setProfileModalOpen: connection.setProfileModalOpen,
      envModalOpen: connection.envModalOpen,
      setEnvModalOpen: connection.setEnvModalOpen,
      saveProfile: connection.saveProfile,
      deleteProfile: connection.deleteProfile,
      clearConnectionIdsForProfile: tabsLayer.clearConnectionIdsForProfile,
      applyProfileToActiveTab: tabsLayer.applyProfileToActiveTab,
      prevBaseUrlRef: connection.prevBaseUrlRef,
      environments: connection.environments,
      createEnvironment: connection.createEnvironment,
      deleteEnvironment: connection.deleteEnvironment,
      setActiveEnvironment: connection.setActiveEnvironment,
      updateEnvironmentName: connection.updateEnvironmentName,
      updateVariables: connection.updateVariables,
      importEnvironment: connection.importEnvironment,
      exportEnvironment: connection.exportEnvironment,
    },
  });

  return {
    demoBridges: {
      upsertEnvironment: connection.upsertEnvironment,
      deleteEnvironmentByName: connection.deleteEnvironmentByName,
      applyTlsSettings: tabsLayer.connectionHandlers.handleConnectionTlsChange,
      setGqlQuery: tabsLayer.handleDemoSetGqlQuery,
      setRightView: uiState.setRightView,
      handleAdvSettingsChange: advancedSettings.handleAdvSettingsChange,
      setBatchUnsupportedToast: advancedSettings.setBatchUnsupportedToast,
    },
    executionLayers: executionLayer.execution.executionLayers as ReactNode,
    toolbarSections,
    tabBar: {
      tabs: tabsLayer.tabs,
      activeTabId,
      confirmingCloseTabId: tabsLayer.confirmingCloseTabId,
      pageDefaultEndpoint: connection.endpoint,
      pageDefaultEndpointResolved: foundation.pageDefaultEndpointResolved,
      globalAuthProfiles: globalAuthProfiles ?? [],
      onTabClick: tabsLayer.handleTabClick,
      onTabClose: tabsLayer.closeTab,
      onAddTab: tabsLayer.addTab,
      onRenameTab: tabsLayer.renameTab,
      profiles: connection.profiles,
      batchEnabled: advancedSettings.advSettings.batchEnabled,
      batchIncludedTabIds: batchLayer.batchedTabIdsSet,
    },
    main: {
      builderMode: uiState.builderMode,
      activityTab: foundation.activityTab,
      gqlActivitySplitRef: splitPanes.gqlActivitySplitRef,
      activityPanelWidth: splitPanes.activityPanelWidth,
      history,
      historyMaxItems: foundation.historyMaxItems,
      handleHistoryMaxItemsChange: foundation.handleHistoryMaxItemsChange,
      tabSchemaConnectionId: tabsLayer.tabSchemaConnectionId,
      handleLoadHistoryItem: itemLoaders.handleLoadHistoryItem,
      handleRunHistoryItem: itemLoaders.handleRunHistoryItem,
      setSaveToColItem: foundation.setSaveToColItem,
      mockServer: schemaLayer.mockServer,
      schemaInfo: schemaLayer.schemaInfo,
      collections,
      invalidItemIds: schemaLayer.invalidItemIds,
      handleRunCollection,
      handleLoadCollectionItem: itemLoaders.handleLoadCollectionItem,
      saveToColItem: foundation.saveToColItem,
      activeTab,
      activeEnvironment: connection.activeEnvironment,
      activityDividerProps: splitPanes.activityDividerProps,
      gqlSplitRef: splitPanes.gqlSplitRef,
      gqlLeftPaneRef: splitPanes.gqlLeftPaneRef,
      editorPaneWidth: splitPanes.editorPaneWidth,
      gqlPaneDividerProps: splitPanes.gqlPaneDividerProps,
      bottomPanelDividerProps: splitPanes.bottomPanelDividerProps,
      bottomPanelHeight: splitPanes.bottomPanelHeight,
      onSetBuilderMode: uiState.setBuilderMode,
      onEditInEditor: itemLoaders.handleEditInEditor,
      onBuilderExecute: itemLoaders.handleBuilderExecute,
      onQueryChange: tabsLayer.handleQueryChange,
      editorMountRef: tabsLayer.editorActions.editorMountRef,
      prettifyError: tabsLayer.editorActions.prettifyError,
      onPrettify: tabsLayer.editorActions.handlePrettify,
      insertToast: tabsLayer.editorActions.insertToast,
      complexityWarningPending: complexity.complexityWarningPending,
      complexityResult: complexity.complexityResult,
      onExecute: handleExecute,
      onDismissComplexityWarning: handleDismissComplexityWarning,
      onAssertionsChange: tabsLayer.handleAssertionsChange,
      bottomTab: uiState.bottomTab,
      onSetBottomTab: uiState.setBottomTab,
      runnerCollectionId: foundation.runnerCollectionId,
      runner,
      varsModelPath: buildVarsModelUri(activeTab.id),
      varsError,
      onVariablesChange: tabsLayer.handleVariablesChange,
      onHeadersChange: tabsLayer.handleHeadersChange,
      globalEnvMap: foundation.globalEnvMap,
      fileEntries: uiState.fileEntries,
      onFileEntriesChange: uiState.setFileEntries,
      activeTabUploadProgress,
      storedAuthForPanel: tabsLayer.storedAuthForPanel,
      resolvedAuthPreview: tabsLayer.resolvedAuthPreview,
      usesPageDefaultAuth: tabsLayer.usesPageDefaultAuth,
      hasActiveTabAuthOverride: tabsLayer.hasActiveTabAuthOverride,
      onAuthChange: tabsLayer.connectionHandlers.handleConnectionAuthChange,
      onResetAuthToInherit: tabsLayer.clearActiveTabAuth,
      linkedProfileName: tabsLayer.linkedProfileName,
      defaultAuthProfileId: tabsLayer.defaultAuthProfileId,
      rightView: uiState.rightView,
      onRightViewChange: uiState.setRightView,
      response: responsePaneState.response,
      isActiveTabExecuting: responsePaneState.executing,
      execStatus: responsePaneState.execStatus,
      schemaStatus: schemaLayer.schemaStatus,
      schemaErrorMessage: schemaLayer.schemaErrorMessage,
      onIntrospect: schemaLayer.handleIntrospect,
      introspecting: schemaLayer.introspecting,
      onInsertField: tabsLayer.editorActions.handleInsertField,
      snapshots: schemaLayer.snapshots,
      onSaveSnapshot: schemaLayer.handleSaveSnapshot,
      onDeleteSnapshot: schemaLayer.handleDeleteSnapshot,
      onClearOlderSnapshots: schemaLayer.handleClearOlderSnapshots,
      onOpenDiff: schemaLayer.handleOpenDiff,
      deprecatedUsages: schemaLayer.deprecatedUsages,
      onOpenCollectionItem: itemLoaders.handleOpenCollectionItem,
      subscription,
      selectedOperation: tabsLayer.selectedOperation,
      assertionResultMap,
      onExportSubscription: subscriptionOrchestration.handleExportSubscription,
      onStopSubscription: subscriptionOrchestration.handleStopSubscription,
      onResubscribeSubscription: handleSubscribe,
      onOpenBatchResults: batchLayer.batchResult ? batchLayer.openBatchResults : undefined,
      batchExecutingOnActiveTab: batchLayer.batchExecuting && activeTabId != null && batchLayer.batchedTabIdsSet.has(activeTabId),
      onResponseSubTabChange: handleResponseSubTabChange,
      onActivityTabChange: foundation.setActivityTab,
    },
    overlays: {
      batchResult: batchLayer.batchResult,
      batchResultsOpen: batchLayer.batchResultsOpen,
      dismissBatchResults: batchLayer.dismissBatchResults,
      schemaDiffToast: schemaLayer.schemaDiffToast,
      snapshots: schemaLayer.snapshots,
      toastBaselineSnapshotIdRef: schemaLayer.toastBaselineSnapshotIdRef,
      schemaInfo: schemaLayer.schemaInfo,
      handleOpenDiff: schemaLayer.handleOpenDiff,
      setRightView: uiState.setRightView,
      setSchemaDiffToast: schemaLayer.setSchemaDiffToast,
      apqUnsupportedToast: advancedSettings.apqUnsupportedToast,
      setApqUnsupportedToast: advancedSettings.setApqUnsupportedToast,
      batchUnsupportedToast: advancedSettings.batchUnsupportedToast,
      setBatchUnsupportedToast: advancedSettings.setBatchUnsupportedToast,
      diffModal: schemaLayer.diffModal,
      setDiffModal: schemaLayer.setDiffModal,
      invalidItemIds: schemaLayer.invalidItemIds,
      handleAcknowledge: schemaLayer.handleAcknowledge,
      handleUnacknowledge: schemaLayer.handleUnacknowledge,
      saveToColItem: foundation.saveToColItem,
      setSaveToColItem: foundation.setSaveToColItem,
      collectionTrees: collections.trees,
      onSaveToCollection: handleSaveToCollection,
      setActivityTab: foundation.setActivityTab,
    },
  };
}
