/**
 * Lesson: Local TLS Echo Server (Docker)
 *
 * Three-phase TLS education against a REAL local server in Docker:
 *
 *  Phase 1 — Skip Certificate Validation (rejectUnauthorized: false)
 *    Steps 1–3: fill wss:// URL, enable skip-cert, connect via Proxy
 *
 *  Phase 2 — CA Certificate Validation (custom root CA, full chain)
 *    Steps 4–5: paste CA cert, reconnect via Proxy
 *
 *  Phase 3 — Mutual TLS / mTLS (client certificate authentication)
 *    Steps 6–8: switch to mTLS server (port 8768), paste client cert+key, connect
 *
 * Docker stack:
 *   TLS echo   → wss://localhost:8766  (Phase 1 + 2) [docker-compose.tls.yml]
 *   mTLS echo  → wss://localhost:8768  (Phase 3)     [docker-compose.mtls.yml]
 *
 * Health probes:
 *   http://localhost:8767  (Phase 1+2 gate — ws-echo-tls:8080 on host)
 *   http://localhost:8769  (Phase 3 — ws-echo-mtls:8080 on host)
 *
 * Prerequisites:
 *   cd docker/websocket
 *   ./generate-cert.sh         # creates CA + server certs (one-time)
 *   ./generate-client-cert.sh  # creates client.crt + client.key (one-time)
 *   docker compose -f docker-compose.tls.yml  up -d
 *   docker compose -f docker-compose.mtls.yml up -d
 */
import type { DemoActionContext, DemoLesson } from '../../types';
import { closeExtraConnectionTabs, disconnectWebSocket, clearEvents, resetAuth, clearCustomHeaders } from '../setup-helpers';
import { WS } from '../../../../shared/selectors';

const TLS_URL   = 'wss://localhost:8766';
const MTLS_URL  = 'wss://localhost:8768';

// ── Embedded certificates (generated by generate-cert.sh / generate-client-cert.sh) ──

/** RedfireForge Dev Root CA — validates both the TLS and mTLS server leaf certs. */
const DEV_CA_CERT = `-----BEGIN CERTIFICATE-----
MIIDkzCCAnugAwIBAgIUS0bEZe+tpZQUkANR8jZ55X/XTtkwDQYJKoZIhvcNAQEL
BQAwWTEhMB8GA1UEAwwYUmVkZmlyZUZvcmdlIERldiBSb290IENBMRkwFwYDVQQK
DBBSZWRmaXJlRm9yZ2UgRGV2MRkwFwYDVQQLDBBXZWJTb2NrZXQgU3R1ZGlvMB4X
DTI2MDYxMjEzMTUwNloXDTI4MDkxNDEzMTUwNlowWTEhMB8GA1UEAwwYUmVkZmly
ZUZvcmdlIERldiBSb290IENBMRkwFwYDVQQKDBBSZWRmaXJlRm9yZ2UgRGV2MRkw
FwYDVQQLDBBXZWJTb2NrZXQgU3R1ZGlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAjiQjeEOw11OclqPg+NQLaHVu0Zw5UqIHSPeHxxnfIoBvs8Soh9EF
ugg0hXV4JqObcWlS8TW2kpw9t8lWzy+auLpzeR6BahNsT6ji7IkeQzYKPB2ak4Y/
neiwdqwpHBEOKogejzwL599JU1H8ANo05HNi60n1NfV7VSSoVz/YJf9NSGhv1/HY
wnXsbhXmiqd7GtxuzMQpt/hTFknYULQP6wwqpmqxuaIb7CBHMgu/ZLhiP11ac0IC
64CNq7fheS/YCEs1vyepj4PKrkfZWa/FXMfmq2Co6JsGai6a/OQuwcv5EKPMDEiW
A+RcR+Oq8SIvR+r/wOPDMTYg7RcjGtxaZQIDAQABo1MwUTAdBgNVHQ4EFgQUu5r2
z0IyCKHt0PzeJeRW/1tlKz0wHwYDVR0jBBgwFoAUu5r2z0IyCKHt0PzeJeRW/1tl
Kz0wDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAf4k+5OjQxAb7
iV7P207pFLIHWeGaf13egqoCqk129rycVdk2FGYHP+VoWBIHWERvNY+1KbBmd2QW
pIsK+HEmSa7LD/Q+xxed+/pWeDv76xsuD6jSHlahgrXSaj7SeSh+iX+zR173ZoVD
jm0/78lVUaPWTVnktx+2QaWGYczaS51ZfHKzxwEui2GmsmpxgalpYwXhqukihY77
VK0JqPU+hkrV1/qYmSoegRd6XrAVCYeeXGybR8R61yB6HmRR6Mb0s7jCWW7hduhs
5ZXMj5X8OHPkwXyAQk+b0bgLqrVIDWyIhEU7zwv0ZWyyu7FytH013ZAKzp1LIk4K
/5JrP2q4AA==
-----END CERTIFICATE-----`;

/** Client leaf cert signed by Dev Root CA — used for mTLS Phase 3. */
const DEV_CLIENT_CERT = `-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIUZaGfUGzGRCpGYp98xGzXRt8n9b0wDQYJKoZIhvcNAQEL
BQAwWTEhMB8GA1UEAwwYUmVkZmlyZUZvcmdlIERldiBSb290IENBMRkwFwYDVQQK
DBBSZWRmaXJlRm9yZ2UgRGV2MRkwFwYDVQQLDBBXZWJTb2NrZXQgU3R1ZGlvMB4X
DTI2MDYxNjAwNTU0MFoXDTI4MDkxODAwNTU0MFowWTEhMB8GA1UEAwwYUmVkZmly
ZUZvcmdlIFRlc3QgQ2xpZW50MRkwFwYDVQQKDBBSZWRmaXJlRm9yZ2UgRGV2MRkw
FwYDVQQLDBBXZWJTb2NrZXQgU3R1ZGlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEA15dLfD+pjlON4KXQ06BHNq0J0ayB4/phFLpC4p9LD0B8trsOy+R0
qz1FzcUl92PeTCnj3sCH1uRUIU/uCqxZtfgx5yjYgHocadjpNXc0QpTUgf+XDZMW
ibGGzTkTLaL9m7qGd/W43CVRasBh++O1P+fHphMf5r4r8/pFu5DKrr2VKX5Dc15i
ahEwDIQb760glHVHqU1zcYtJgmtUFQ3QsTfO7Oia+AnJwuaPjwIHB06nEyJu0dzE
ZJ25mmD//CrJMikH40zw1rWhcQ19rYY3PsJ4JCxB+y5ek9wS06GuhhU8eUrW5Ull
VAaI4p5ISqdVQ05DHFUU1+Go7xflKMCinwIDAQABo28wbTAJBgNVHRMEAjAAMAsG
A1UdDwQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAjAdBgNVHQ4EFgQUwgcnMJ8k
j3jpCS3QzssnX4mROI4wHwYDVR0jBBgwFoAUu5r2z0IyCKHt0PzeJeRW/1tlKz0w
DQYJKoZIhvcNAQELBQADggEBAIhkvZ7KsJTBFAwkt8h9BDnEYYwMNFz6bygS8PRE
JJW4zWrRbYqNm3/LEnJPZ7CaeP6RdCWjEM2m6HLunCU4uqByAYXZgnAIWobPIHOB
gLNDEcZci+mcrIEmM4cIP+qhRyZokBHmbWOfnlB+m3TYhszdebLoDOm5L5+SXqSJ
tO5Aw6JlR+T6BKeBxBQ14Q1NuUIIoiOOarb3ewagWeARxA7Svx2TYEuHAGx59gbG
brQJYxVmksvQ+GkPsrVZhZ7D5uMNdWnCREJTNz85xDM5B4JMkzputc7t9EcYnVTs
/c3C9XyXIv1dkQBzPHXEVmBhtG5UFPZu7izQ5iWUT0vVxvk=
-----END CERTIFICATE-----`;

/** Client private key — used with DEV_CLIENT_CERT for mTLS Phase 3. */
const DEV_CLIENT_KEY = `-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDXl0t8P6mOU43g
pdDToEc2rQnRrIHj+mEUukLin0sPQHy2uw7L5HSrPUXNxSX3Y95MKePewIfW5FQh
T+4KrFm1+DHnKNiAehxp2Ok1dzRClNSB/5cNkxaJsYbNORMtov2buoZ39bjcJVFq
wGH747U/58emEx/mvivz+kW7kMquvZUpfkNzXmJqETAMhBvvrSCUdUepTXNxi0mC
a1QVDdCxN87s6Jr4CcnC5o+PAgcHTqcTIm7R3MRknbmaYP/8KskyKQfjTPDWtaFx
DX2thjc+wngkLEH7Ll6T3BLToa6GFTx5StblSWVUBojinkhKp1VDTkMcVRTX4ajv
F+UowKKfAgMBAAECggEAU4ohyvSUTD1eRcWbBNYfojUtD91ru56CzdhbIJufJzrS
2K/lTOaquswUZ2bUjmdZdWPqE5/BQ2jYnMvvLp2YaaXSGIPAWRB4QB+4Rmp5iq9H
JVSYAL+VRSfQV2edYdq9sQF3J7bEujGPufDwRv32dtvmhhj1DKF2QKUjLkot78V6
H7hjD21Rh2xcNQLYbbJ/b8s5Nye9rSbZRUniDY4oCqxFZHRh24UDefDz+1Y8e+tk
NnSoLXg9kiQGjvCVl0D2ttB6EaWU35g3UCxZaJELdL7GhSwmo0WznAXB6xeP7KLW
TuqMGzib/jqd6XhAC6Y+VxgQyZL5dBVxiTD/INwL6QKBgQD8yZGn0jgbbITsZmC6
tzTjsKisfm7+IYUEry4dEBzKlZhx7vI0y/kjqQwXZkYfwgdqirW/e4KEi9s0yKHP
oYJDQd4VACnupnF5cx1jUkH2lLsehNoj+FLrUXpp/NEBQPraAnOk1L/beuUs0H7y
pxgdxnm6IRNPdpbAhO3p2mNbbQKBgQDaVLWW7HVzpo/83lPfqu/idnoqdg0sjQ7X
4aICNkjXUzHD1An+LixXMxntpaRd4PyETJOcO6omGMGf6qo5x/+SEWfxLq9q74G6
70tEZNvgZTchSrJHeArPh+y5RbAtKX6Orkal2BP2/mmq0g7Jb+xNYSokTH/4A9M+
UPTxmY4CuwKBgQDRi22YReSIpx5QsFUCshe/npNT2cK8GqEfTu/U26RiMjuaRk60
gVjWvKzvQLJkZPyszqr2PbXlleFyEdZAPUuz4QftNKON1p8947S6vlc7xfKOy+Xf
51slAfeNoCrI9Up8KYgfXNRlZaxPx81T7DtLg1kod36AYnd4wzhMn+G4yQKBgQCw
csdzGtTtS46QuYmlePt31XJ0AIYzHCkD1aleCksiIm1Uq3gMAXr6WiU5R6Yn7N2H
em/NUvb25QkO2dMK8ZSdkw2jAKzqSnhZAG2e77g3iPVeJYUhd2WdRWfOcACq7x8F
5tjXzWKNOh1h3XPv3lFmVAF/5oeBhG3jrf/XhdccYwKBgQCwxM0k3ol/pSA4A3cB
UQaAckMZy0HSWVjeUabOqbfZokh0j52zSvSa0fxaVkzWsY+9zmX1X8gkhUHqF/fV
BH7xY21Ej5idx/FgdROE9JBhkM+8hrWXtAZhvKOS7eDQBBhcC1PvhFqhCdGPM42q
iAU+tJGKIkZm8s8ILh0GJWVcfQ==
-----END PRIVATE KEY-----`;

// ── Guard helpers ──────────────────────────────────────────────────

/**
 * Opens the TLS modal if it is not already open.
 *
 * The Configure button (`data-testid="tls-toggle"`) never receives an
 * `aria-expanded` attribute, so checking that property always returns null.
 * Instead we check whether the modal body (`data-testid="tls-body"`) is
 * already present in the DOM — if so, the modal is open and we skip the click.
 */
async function ensureTlsPanelExpanded(ctx: DemoActionContext): Promise<void> {
  await ctx.waitFor(WS.TLS_TOGGLE, 2000);
  const alreadyOpen = !!document.querySelector(WS.TLS_BODY);
  if (!alreadyOpen) {
    const toggle = document.querySelector(WS.TLS_TOGGLE) as HTMLElement | null;
    if (toggle) {
      toggle.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true }));
      await ctx.delay(300);
    }
  }
}

/**
 * Closes the TLS modal if it is currently open, by clicking its Close button.
 * Must be called before connecting so the Connect tab is fully visible.
 */
async function closeTlsModal(ctx: DemoActionContext): Promise<void> {
  const closeBtn = document.querySelector('[data-testid="tls-close"]') as HTMLElement | null;
  if (closeBtn) {
    closeBtn.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true }));
    await ctx.delay(300);
  }
}

/**
 * Toggles the skip-cert checkbox to the desired state via a click dispatch.
 * React controlled checkboxes respond to click events: the click toggles the
 * DOM checked property and React's onClick handler fires, updating state.
 */
async function setSkipCert(ctx: DemoActionContext, checked: boolean): Promise<void> {
  await ctx.waitFor(`${WS.TLS_SKIP_CERT} input[type="checkbox"]`, 2000);
  const checkbox = document.querySelector(`${WS.TLS_SKIP_CERT} input[type="checkbox"]`) as HTMLInputElement | null;
  if (!checkbox || checkbox.checked === checked) return;
  checkbox.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true }));
  await ctx.delay(200);
}

/** Clears all three TLS PEM text fields (CA cert, client cert, client key). */
async function clearCertFields(ctx: DemoActionContext): Promise<void> {
  await ctx.fill(WS.TLS_CA_CERT, '');
  await ctx.fill(WS.TLS_CLIENT_CERT, '');
  await ctx.fill(WS.TLS_CLIENT_KEY, '');
  await ctx.delay(150);
}

// ── Setup / Cleanup ────────────────────────────────────────────────

async function localTlsSetup(ctx: DemoActionContext): Promise<void> {
  await ctx.delay(500);
  await ctx.click(WS.MODE_CLIENT);
  await ctx.delay(300);

  await disconnectWebSocket(ctx);
  await closeExtraConnectionTabs(ctx);
  await clearEvents(ctx);

  // Clear auth and custom headers — these trigger proxy mode and can cause 504s
  // when the Node.js backend is not running. We want a clean slate.
  await resetAuth(ctx);
  await clearCustomHeaders(ctx);

  await ctx.click(WS.LEFT_TAB_CONNECT);
  await ctx.delay(200);
  await ctx.click(WS.RIGHT_TAB_EVENTS);
  await ctx.delay(200);

  // Fill the wss:// URL to mount the TLS panel, reset its state, then CLEAR the
  // URL so step 1 shows the full "wss:// → TLS panel appears" moment visually.
  await ctx.fill(WS.URL_INPUT, TLS_URL);
  await ensureTlsPanelExpanded(ctx);
  await setSkipCert(ctx, false);
  await clearCertFields(ctx);
  await ctx.fill(WS.URL_INPUT, '');
  await ctx.delay(200);
}

async function localTlsCleanup(ctx: DemoActionContext): Promise<void> {
  await ctx.click(WS.MODE_CLIENT);
  await ctx.delay(300);
  await ctx.click(WS.LEFT_TAB_CONNECT);
  await ctx.delay(200);

  await disconnectWebSocket(ctx);
  await clearEvents(ctx);

  // Restore wss:// URL so the TLS panel renders, reset all state, then clear.
  await ctx.fill(WS.URL_INPUT, TLS_URL);
  await ensureTlsPanelExpanded(ctx);
  await setSkipCert(ctx, false);
  await clearCertFields(ctx);
  await ctx.fill(WS.URL_INPUT, '');
  await ctx.delay(200);
  await closeExtraConnectionTabs(ctx);
}

// ── Lesson Definition ──────────────────────────────────────────────

export const wsTlsLocalLesson: DemoLesson = {
  id: 'ws-tls-local',
  domainId: 'protocols',
  category: 'websocket',
  name: 'Local TLS Echo Server (Docker)',
  description:
    'Three phases of TLS against a real local server in Docker: skip-cert validation, CA certificate chain, and Mutual TLS (mTLS) with a client certificate.',
  estimatedMinutes: 8,
  tag: '🐳 Docker',
  initialTab: 'websocket-studio',

  dockerEndpoint: 'http://localhost:8767',
  dockerCommand:
    'cd docker/websocket && ./generate-cert.sh && ./generate-client-cert.sh && docker compose -f docker-compose.tls.yml -f docker-compose.mtls.yml up -d',

  setup: localTlsSetup,
  cleanup: localTlsCleanup,

  concept: {
    title: 'TLS in Three Phases — Local Docker Server',
    body: `This lesson uses a **real local TLS server** in Docker — no external dependencies, no external risk. It works on **both Web and Tauri desktop** — the transport mechanism differs by platform:

| Platform | Transport | How TLS options are applied |
|----------|-----------|----------------------------|
| **Web browser** | Node.js Proxy | \`npm run server\` opens the TLS connection server-side and bridges the browser |
| **Tauri desktop** | Native (Rust) | The Rust client applies TLS options directly — **no proxy required** |

The server uses a **self-signed certificate** from a dev Root CA, exactly what you encounter in staging environments with internal PKI. RedfireForge supports three TLS approaches via its **TLS / mTLS Configuration** panel:

| Phase | Approach | Use case |
|-------|----------|----------|
| **1** | **Skip certificate validation** — \`rejectUnauthorized: false\` | Local dev, quick iteration |
| **2** | **CA Certificate** — paste root CA PEM | Staging / internal PKI environments |
| **3** | **Mutual TLS (mTLS)** — client cert + key | APIs that verify client identity |

**Prerequisites — Web browser**
1. \`npm run server\` — starts Node.js proxy on port 3001 (required for browser TLS)
2. \`cd docker/websocket && ./generate-cert.sh && ./generate-client-cert.sh && docker compose -f docker-compose.tls.yml -f docker-compose.mtls.yml up -d\`

**Prerequisites — Tauri desktop** *(no proxy needed)*
1. \`cd docker/websocket && ./generate-cert.sh && ./generate-client-cert.sh && docker compose -f docker-compose.tls.yml -f docker-compose.mtls.yml up -d\``,
    diagram: `<svg viewBox="0 -10 720 390" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <marker id="tls-arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">
      <path d="M0,0 L0,6 L8,3 z" fill="var(--primary)"/>
    </marker>
    <marker id="tls-arrow-warn" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">
      <path d="M0,0 L0,6 L8,3 z" fill="var(--warning, #f59e0b)"/>
    </marker>
    <marker id="tls-arrow-tauri" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">
      <path d="M0,0 L0,6 L8,3 z" fill="var(--success, #10b981)"/>
    </marker>
  </defs>

  <!-- ══ LEFT COLUMN ══ -->

  <!-- Web Browser box -->
  <rect x="20" y="52" width="130" height="62" rx="6" fill="var(--primary)" opacity="0.15" stroke="var(--primary)" stroke-width="1.5"/>
  <text x="85" y="76" text-anchor="middle" fill="var(--text)" font-size="12" font-family="system-ui" font-weight="600">Web Browser</text>
  <text x="85" y="92" text-anchor="middle" fill="var(--text-muted)" font-size="9" font-family="system-ui">/api/ws/connect</text>
  <text x="85" y="106" text-anchor="middle" fill="var(--primary)" font-size="9" font-family="system-ui">→ via Proxy</text>

  <!-- Tauri Desktop box -->
  <rect x="20" y="243" width="130" height="62" rx="6" fill="var(--success, #10b981)" opacity="0.12" stroke="var(--success, #10b981)" stroke-width="1.5"/>
  <text x="85" y="267" text-anchor="middle" fill="var(--text)" font-size="12" font-family="system-ui" font-weight="600">Tauri Desktop</text>
  <text x="85" y="283" text-anchor="middle" fill="var(--text-muted)" font-size="9" font-family="system-ui">Rust WebSocket</text>
  <text x="85" y="297" text-anchor="middle" fill="var(--success, #10b981)" font-size="9" font-family="system-ui">→ Native (no proxy)</text>

  <!-- ══ MIDDLE COLUMN ══ -->

  <!-- Node.js Proxy box (browser only) -->
  <rect x="208" y="44" width="155" height="85" rx="6" fill="rgba(59,130,246,0.08)" stroke="var(--primary)" stroke-width="1.5" stroke-dasharray="4 2"/>
  <text x="285" y="67" text-anchor="middle" fill="var(--text)" font-size="12" font-family="system-ui" font-weight="600">Node.js Proxy</text>
  <text x="285" y="83" text-anchor="middle" fill="var(--text-muted)" font-size="9" font-family="system-ui">npm run server</text>
  <text x="285" y="98" text-anchor="middle" fill="var(--text-muted)" font-size="9" font-family="system-ui">port 3001</text>
  <text x="285" y="120" text-anchor="middle" fill="var(--primary)" font-size="9" font-family="system-ui" opacity="0.7">TLS settings applied here</text>

  <!-- "Direct — no proxy" label between proxy box and Tauri path -->
  <text x="285" y="210" text-anchor="middle" fill="var(--success, #10b981)" font-size="9" font-family="system-ui" opacity="0.7" font-style="italic">direct — no proxy</text>

  <!-- ══ RIGHT COLUMN ══ -->

  <!-- Phase 1+2 badge -->
  <rect x="452" y="5" width="70" height="18" rx="9" fill="var(--primary)" opacity="0.2"/>
  <text x="487" y="18" text-anchor="middle" fill="var(--primary)" font-size="10" font-weight="600">Phase 1+2</text>

  <!-- nginx TLS proxy box -->
  <rect x="450" y="28" width="205" height="65" rx="6" fill="var(--accent, #8b5cf6)" opacity="0.12" stroke="var(--accent, #8b5cf6)" stroke-width="1.5"/>
  <text x="552" y="50" text-anchor="middle" fill="var(--text)" font-size="12" font-family="system-ui" font-weight="600">nginx TLS Proxy</text>
  <text x="552" y="67" text-anchor="middle" fill="var(--text-muted)" font-size="9" font-family="system-ui">wss://localhost:8766</text>
  <text x="552" y="83" text-anchor="middle" fill="var(--text-muted)" font-size="9" font-family="system-ui" opacity="0.7">docker-compose.tls.yml</text>

  <!-- Phase 3 badge -->
  <rect x="452" y="215" width="60" height="18" rx="9" fill="var(--warning, #f59e0b)" opacity="0.2"/>
  <text x="482" y="228" text-anchor="middle" fill="var(--warning, #f59e0b)" font-size="10" font-weight="600">Phase 3</text>

  <!-- nginx mTLS proxy box -->
  <rect x="450" y="238" width="205" height="80" rx="6" fill="var(--warning, #f59e0b)" opacity="0.1" stroke="var(--warning, #f59e0b)" stroke-width="1.5"/>
  <text x="552" y="260" text-anchor="middle" fill="var(--text)" font-size="12" font-family="system-ui" font-weight="600">nginx mTLS Proxy</text>
  <text x="552" y="277" text-anchor="middle" fill="var(--text-muted)" font-size="9" font-family="system-ui">wss://localhost:8768</text>
  <text x="552" y="294" text-anchor="middle" fill="var(--warning, #f59e0b)" font-size="9" font-family="system-ui" font-weight="500">ssl_verify_client on</text>
  <text x="552" y="310" text-anchor="middle" fill="var(--text-muted)" font-size="9" font-family="system-ui" opacity="0.7">docker-compose.mtls.yml</text>

  <!-- ══ ARROWS — Browser path (blue, solid) ══ -->

  <!-- Web Browser → Node.js Proxy -->
  <line x1="150" y1="83" x2="208" y2="83" stroke="var(--primary)" stroke-width="1.5" marker-end="url(#tls-arrow)"/>

  <!-- Node.js Proxy → nginx TLS (Phase 1+2) -->
  <line x1="363" y1="68" x2="450" y2="53" stroke="var(--primary)" stroke-width="1.5" marker-end="url(#tls-arrow)"/>

  <!-- Node.js Proxy → nginx mTLS (Phase 3) -->
  <line x1="363" y1="108" x2="450" y2="255" stroke="var(--warning, #f59e0b)" stroke-width="1.5" marker-end="url(#tls-arrow-warn)"/>

  <!-- ══ ARROWS — Tauri path (green, dashed) ══ -->

  <!-- Tauri → nginx TLS (Phase 1+2): route right past proxy, then up -->
  <path d="M150,265 L408,265 L408,60 L450,60" fill="none" stroke="var(--success, #10b981)" stroke-width="1.5" stroke-dasharray="5 3" marker-end="url(#tls-arrow-tauri)"/>

  <!-- Tauri → nginx mTLS (Phase 3): straight across below proxy box -->
  <line x1="150" y1="277" x2="450" y2="277" stroke="var(--success, #10b981)" stroke-width="1.5" stroke-dasharray="5 3" marker-end="url(#tls-arrow-tauri)"/>

  <!-- ══ LEGEND ══ -->
  <line x1="20" y1="355" x2="45" y2="355" stroke="var(--primary)" stroke-width="1.5"/>
  <text x="50" y="358" fill="var(--text-muted)" font-size="9" font-family="system-ui">Web (via Node.js proxy)</text>
  <line x1="205" y1="355" x2="230" y2="355" stroke="var(--success, #10b981)" stroke-width="1.5" stroke-dasharray="5 3"/>
  <text x="235" y="358" fill="var(--text-muted)" font-size="9" font-family="system-ui">Tauri (native, direct)</text>

  <!-- Echo server label -->
  <text x="552" y="335" text-anchor="middle" fill="var(--text-muted)" font-size="9" font-family="system-ui">&#x2193; jmalloc/echo-server (ws://localhost:8080)</text>
</svg>`,
  },

  steps: [
    // ═══════════════════════════════════════════════════════════════
    // PHASE 1 — Skip Certificate Validation
    // ═══════════════════════════════════════════════════════════════

    // ── 1. Introduce wss:// URL ────────────────────────────────────
    {
      id: 'local-tls-url',
      title: 'Phase 1 — The Local TLS Server',
      description:
        'Type `wss://localhost:8766` — the local nginx reverse proxy with a self-signed certificate. Notice the **TLS / mTLS Configuration** panel appears the moment you enter a `wss://` URL. This is your signal that encrypted transport is involved and configuration is available.',
      highlight: WS.TLS_PANEL,
      preAction: async (ctx) => {
        await ctx.click(WS.MODE_CLIENT);
        await ctx.delay(200);
        await ctx.click(WS.LEFT_TAB_CONNECT);
        await ctx.delay(200);
      },
      action: async (ctx) => {
        // Type the URL character-by-character feel is handled by ctx.fill;
        // the TLS panel mounts as soon as value starts with wss://.
        await ctx.fill(WS.URL_INPUT, TLS_URL);
        await ctx.delay(500);
        await ensureTlsPanelExpanded(ctx);
        await ctx.delay(600);
      },
      pauseAfter: true,
    },

    // ── 2. Skip Certificate Validation ────────────────────────────
    {
      id: 'local-tls-skip-cert',
      title: 'Skip Certificate Validation',
      description:
        'Check **Skip certificate validation** — this sets `rejectUnauthorized: false` on the TLS handshake.\n\n' +
        '**What happens under the hood:**\n' +
        'Normally, the TLS layer checks three things before a connection is allowed: (1) the certificate is signed by a trusted CA, (2) the hostname in the certificate matches the server address, and (3) the certificate hasn\'t expired. With `rejectUnauthorized: false` all three checks are skipped — the connection proceeds even if the cert is self-signed, expired, or for the wrong host.\n\n' +
        '**Why the transport changes to Proxy:**\n' +
        'Web browsers enforce TLS certificate validation at the OS/network layer — there is no JavaScript API to bypass it. RedfireForge detects that a TLS override is active and automatically routes through its **Node.js Proxy** (`npm run server`), which opens the connection server-side using Node\'s `ws` library where `rejectUnauthorized: false` is supported. Watch the **transport badge** change from **Direct → Proxy** the instant you check the box. On Tauri desktop, the Rust client handles this natively — no proxy switch occurs.\n\n' +
        '**When to use it:**\n' +
        '- Local dev with a self-signed cert and no CA file handy\n' +
        '- Quick smoke-test of a new staging endpoint before certs are properly configured\n\n' +
        '**When NOT to use it:**\n' +
        'Never in production, and never when testing against a real server whose identity you should verify. A man-in-the-middle attacker can intercept all traffic when validation is disabled. Use **Phase 2 (CA Certificate)** to trust your own CA, or **Phase 3 (mTLS)** for mutual authentication.',
      highlight: WS.TLS_SKIP_CERT,
      preAction: async (ctx) => {
        await ctx.click(WS.LEFT_TAB_CONNECT);
        await ctx.delay(200);
        await ensureTlsPanelExpanded(ctx);
      },
      action: async (ctx) => {
        await setSkipCert(ctx, true);
        await ctx.delay(600);
        // Briefly highlight the transport badge so viewers see the Direct→Proxy change
        const badge = document.querySelector(WS.TRANSPORT_BADGE) as HTMLElement | null;
        if (badge) {
          badge.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
          badge.style.outline = '2px solid var(--accent-primary, #e96b3a)';
          badge.style.borderRadius = '4px';
          await ctx.delay(800);
          badge.style.outline = '';
          badge.style.borderRadius = '';
        }
      },
      pauseAfter: true,
    },

    // ── 3. Connect via Proxy + send echo ──────────────────────────
    {
      id: 'local-tls-connect',
      title: 'Connect & Echo — Phase 1 Confirmed',
      description:
        'Click **Connect**. The proxy accepts the self-signed cert and the connection establishes — the studio automatically switches to the **Compose** tab so you can immediately send a message. The echo server reflects it back, proving the encrypted round-trip. The demo then returns to the Connect tab so you can see the **Connected** status and the **Proxy** transport badge.',
      highlight: WS.CONNECT_BTN,
      preAction: async (ctx) => {
        await ctx.click(WS.LEFT_TAB_CONNECT);
        await disconnectWebSocket(ctx);
        // Close the TLS modal so the Connect button and status indicator are visible
        await closeTlsModal(ctx);
        await ctx.delay(200);
      },
      action: async (ctx) => {
        await ctx.click(WS.CONNECT_BTN);
        // Wait for the connection — the WS Studio auto-switches to Compose on connect.
        // We embrace that auto-switch and send the echo from the Compose tab.
        await ctx.delay(2500);
        const isConnected = !!document.querySelector(WS.STATUS_CONNECTED);
        if (isConnected) {
          // Already on Compose tab (auto-switched) — fill and send the echo
          await ctx.fill(WS.MESSAGE_INPUT, '{"phase":1,"method":"skip-cert","msg":"Hello over local TLS!"}');
          await ctx.delay(400);
          await ctx.click(WS.SEND_BTN);
          await ctx.delay(800);
          // Switch to Connect tab to show the Connected status + transport badge
          await ctx.click(WS.LEFT_TAB_CONNECT);
          await ctx.delay(1500);
        }
        // Briefly outline the transport badge so viewers see the Proxy label
        const badge = document.querySelector(WS.TRANSPORT_BADGE) as HTMLElement | null;
        if (badge) {
          badge.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
          badge.style.outline = '2px solid var(--accent-primary, #e96b3a)';
          badge.style.borderRadius = '4px';
          await ctx.delay(800);
          badge.style.outline = '';
          badge.style.borderRadius = '';
        }
      },
      verify: WS.STATUS_CONNECTED,
      pauseAfter: true,
    },

    // ═══════════════════════════════════════════════════════════════
    // PHASE 2 — CA Certificate Validation
    // ═══════════════════════════════════════════════════════════════

    // ── 4. Explain CA cert approach ───────────────────────────────
    {
      id: 'local-tls-ca-intro',
      title: 'Phase 2 — CA Certificate Validation',
      description:
        'Instead of bypassing certificate validation, paste the **Root CA** that signed the server\'s certificate. The proxy verifies the full chain: `server.crt` was signed by this CA, so the connection is trusted. This is the production-grade approach for environments with internal PKI — no risk of accepting a rogue cert.',
      highlight: WS.TLS_BODY,
      preAction: async (ctx) => {
        await ctx.click(WS.LEFT_TAB_CONNECT);
        await ctx.delay(200);
        await disconnectWebSocket(ctx);
        await ctx.delay(300);
        await ensureTlsPanelExpanded(ctx);
        // Uncheck skip-cert — Phase 2 uses CA cert, not skip-cert
        await setSkipCert(ctx, false);
        await ctx.delay(300);
      },
      action: async (ctx) => {
        // Paste the dev Root CA into the CA Certificate textarea
        await ctx.fill(WS.TLS_CA_CERT, DEV_CA_CERT);
        await ctx.delay(800);
      },
      pauseAfter: true,
    },

    // ── 5. Connect with CA cert ───────────────────────────────────
    {
      id: 'local-tls-ca-connect',
      title: 'Connect with CA Certificate',
      description:
        'Click **Connect**. The proxy validates the server\'s leaf cert against your pasted Root CA — the chain verifies and the connection succeeds. The studio auto-switches to **Compose** so you can send an echo; the demo then returns to the Connect tab to show the **Connected** status and **Proxy** badge. Key difference from Phase 1: certificate chain integrity is enforced — a rogue server with a different cert would be rejected.',
      highlight: WS.CONNECT_BTN,
      preAction: async (ctx) => {
        await ctx.click(WS.LEFT_TAB_CONNECT);
        await disconnectWebSocket(ctx);
        // Close the TLS modal so the Connect button and status indicator are visible
        await closeTlsModal(ctx);
        await ctx.delay(200);
      },
      action: async (ctx) => {
        await ctx.click(WS.CONNECT_BTN);
        // Wait for connection — WS Studio auto-switches to Compose on connect
        await ctx.delay(2500);
        const isConnected = !!document.querySelector(WS.STATUS_CONNECTED);
        if (isConnected) {
          // Already on Compose tab (auto-switched) — send echo
          await ctx.fill(WS.MESSAGE_INPUT, '{"phase":2,"method":"ca-cert","msg":"Chain validated!"}');
          await ctx.delay(400);
          await ctx.click(WS.SEND_BTN);
          await ctx.delay(800);
          // Switch to Connect tab to show Connected status + transport badge
          await ctx.click(WS.LEFT_TAB_CONNECT);
          await ctx.delay(1500);
        }
        const badge = document.querySelector(WS.TRANSPORT_BADGE) as HTMLElement | null;
        if (badge) badge.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
        await ctx.delay(400);
      },
      verify: WS.STATUS_CONNECTED,
      pauseAfter: true,
    },

    // ═══════════════════════════════════════════════════════════════
    // PHASE 3 — Mutual TLS (mTLS)
    // ═══════════════════════════════════════════════════════════════

    // ── 6. Introduce mTLS ─────────────────────────────────────────
    {
      id: 'local-tls-mtls-intro',
      title: 'Phase 3 — Mutual TLS (mTLS)',
      description:
        'Switch to the **mTLS server** at `wss://localhost:8768`. This nginx server has `ssl_verify_client on` — it requires the client to present a certificate signed by our Dev Root CA. Without a valid client cert, the connection is rejected at the TLS handshake. This is how high-security APIs authenticate callers at the transport layer, before any application data is exchanged.',
      highlight: WS.URL_INPUT,
      preAction: async (ctx) => {
        await ctx.click(WS.LEFT_TAB_CONNECT);
        await ctx.delay(200);
        await disconnectWebSocket(ctx);
        await ctx.delay(300);
      },
      action: async (ctx) => {
        // Switch URL to the mTLS server and clear Phase 2 CA cert state
        await ctx.fill(WS.URL_INPUT, MTLS_URL);
        await ctx.delay(500);
        await ensureTlsPanelExpanded(ctx);
        await setSkipCert(ctx, false);
        await clearCertFields(ctx);
        // Set the CA cert again (needed to validate the mTLS server's leaf cert too)
        await ctx.fill(WS.TLS_CA_CERT, DEV_CA_CERT);
        await ctx.delay(800);
      },
      pauseAfter: true,
    },

    // ── 7. Paste client cert + key ────────────────────────────────
    {
      id: 'local-tls-mtls-creds',
      title: 'Client Certificate & Private Key',
      description:
        'Paste the **Client Certificate** and **Client Private Key** into the mTLS fields. These were signed by the same Dev Root CA that the mTLS server trusts. The Node.js proxy will present them during the TLS handshake — the server verifies the cert, authenticating your client at the transport layer.',
      highlight: WS.TLS_BODY,
      preAction: async (ctx) => {
        await ctx.click(WS.LEFT_TAB_CONNECT);
        await ctx.delay(200);
        await ensureTlsPanelExpanded(ctx);
      },
      action: async (ctx) => {
        await ctx.fill(WS.TLS_CLIENT_CERT, DEV_CLIENT_CERT);
        await ctx.delay(600);
        await ctx.fill(WS.TLS_CLIENT_KEY, DEV_CLIENT_KEY);
        await ctx.delay(800);
      },
      pauseAfter: true,
    },

    // ── 8. Connect via mTLS ───────────────────────────────────────
    {
      id: 'local-tls-mtls-connect',
      title: 'Connect via mTLS — Phase 3 Confirmed',
      description:
        'Click **Connect**. The proxy presents the client cert to the mTLS server — it verifies it against the CA, and mutual authentication completes. The studio auto-switches to **Compose** to send an echo; the demo returns to Connect tab to show **Connected** status and **Proxy** badge. Both sides authenticated: you trust the server (CA cert) and the server trusts you (client cert).',
      highlight: WS.CONNECT_BTN,
      preAction: async (ctx) => {
        await ctx.click(WS.LEFT_TAB_CONNECT);
        await disconnectWebSocket(ctx);
        // Close the TLS modal so the Connect button and status indicator are visible
        await closeTlsModal(ctx);
        await ctx.delay(200);
      },
      action: async (ctx) => {
        await ctx.click(WS.CONNECT_BTN);
        // Wait for connection — WS Studio auto-switches to Compose on connect
        await ctx.delay(2500);
        const isConnected = !!document.querySelector(WS.STATUS_CONNECTED);
        if (isConnected) {
          // Already on Compose tab (auto-switched) — send echo
          await ctx.fill(WS.MESSAGE_INPUT, '{"phase":3,"method":"mtls","msg":"Both sides authenticated!"}');
          await ctx.delay(400);
          await ctx.click(WS.SEND_BTN);
          await ctx.delay(800);
          // Switch to Connect tab to show Connected status + transport badge
          await ctx.click(WS.LEFT_TAB_CONNECT);
          await ctx.delay(1500);
        }
        // Highlight transport badge
        const badge = document.querySelector(WS.TRANSPORT_BADGE) as HTMLElement | null;
        if (badge) badge.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
        await ctx.delay(400);
      },
      verify: WS.STATUS_CONNECTED,
      pauseAfter: true,
    },
  ],
};
